// ============================================================================
//      scripts/zm/zm_prison/qol_subs_lyrics_prison.gsc
//  SUBTITLES  -  timed lyrics for this map's Easter egg songs     (v2.17.43)
//  GENERATED by modding-jobs\subs-audit-001\build_lyrics.py - do not hand-edit;
//  fix the transcript or the generator and re-run it.
// ----------------------------------------------------------------------------
//  User, 2026-09-26: *"it didn't show the actual lyrics of the song ... make sure
//  it works for all the other easter egg songs in the game"*.
//
//  Each entry is "start|end|text" (tenths of a second from the moment the song
//  starts), plus "|clean text" where the line has a word the clean setting masks.
//  scripts/zm/zmqol_subtitles.gsc zmqol_subs_music() reads this through
//  level.zmqol_subs_lyrics_func, so the root script names nothing map-specific.
//
//  Machine-transcribed from the local song audio with Demucs and Whisper
//  large-v3, then corrected against published song text. Timing comes from
//  word timestamps and has not been checked by ear.
//  Lines per song: mus_zmb_secret_song 30, mus_zmb_secret_song_2 20.
// ============================================================================

main()
{
}

init()
{
    level.zmqol_subs_lyrics_func = ::zmqol_subs_lyrics;
}

zmqol_subs_lyrics( str_alias )
{
    a = [];

    switch ( str_alias )
    {
        case "mus_zmb_secret_song":
            a[a.size] = "86|127|You wired me awake and hit me with a hand of broken";
            a[a.size] = "128|136|Nails.";
            a[a.size] = "172|207|You tied my lead and pulled my chain to watch my blood";
            a[a.size] = "207|221|Begin to boil.";
            a[a.size] = "235|278|But I'm gonna break, I'm gonna break my";
            a[a.size] = "278|316|Gonna break my rusty cage and run.";
            a[a.size] = "323|363|I'm gonna break, I'm gonna break my";
            a[a.size] = "364|427|Gonna break my rusty cage and run.";
            a[a.size] = "494|524|Too cold to start a fire, I'm burning diesel";
            a[a.size] = "524|544|Burning dinosaur bones.";
            a[a.size] = "578|620|I'll take the river down to Stillwater and ride a pack of";
            a[a.size] = "620|629|Dogs.";
            a[a.size] = "644|681|I'm gonna break, I'm gonna break my";
            a[a.size] = "682|721|Gonna break my rusty cage and run";
            a[a.size] = "729|767|I'm gonna break, I'm gonna break my";
            a[a.size] = "768|800|Gonna break my rusty cage";
            a[a.size] = "834|845|And run.";
            a[a.size] = "945|975|When the forest burns along the road";
            a[a.size] = "996|1024|Like God's eyes in my headlights.";
            a[a.size] = "1046|1076|When the dogs are looking for their bones";
            a[a.size] = "1076|1128|And it's raining ice picks on your steel shore.";
            a[a.size] = "1155|1198|I'm gonna break, I'm gonna break my";
            a[a.size] = "1198|1244|Gonna break my rusty cage and run";
            a[a.size] = "1255|1300|I'm gonna break, I'm gonna break my";
            a[a.size] = "1302|1344|Gonna break my rusty cage and run";
            a[a.size] = "1354|1402|I'm gonna break, I'm gonna break my";
            a[a.size] = "1405|1443|Gonna break my rusty cage and run";
            a[a.size] = "1451|1524|I'm gonna break, I'm gonna break my rusty cage";
            a[a.size] = "1524|1536|Cage";
            a[a.size] = "1564|1580|And run";
            break;
        case "mus_zmb_secret_song_2":
            a[a.size] = "128|183|Where are we going from here?";
            a[a.size] = "185|215|Where do we go?";
            a[a.size] = "245|303|Are we all blinded by fear?";
            a[a.size] = "305|328|How do we";
            a[a.size] = "337|362|How do we know?";
            a[a.size] = "367|393|Where do we go?";
            a[a.size] = "397|423|Where do we go?";
            a[a.size] = "427|453|How do we know?";
            a[a.size] = "457|483|Where do we go?";
            a[a.size] = "492|544|Where are we going from here?";
            a[a.size] = "547|574|How do we know?";
            a[a.size] = "577|602|Where do we go?";
            a[a.size] = "844|904|Where are we going from here?";
            a[a.size] = "905|962|Do we let go of all we know?";
            a[a.size] = "971|1000|Are we all blinded by fear?";
            a[a.size] = "1009|1081|Where do we go when we let go?";
            a[a.size] = "1089|1143|I feel I'm falling from here.";
            a[a.size] = "1147|1172|Don't let me go.";
            a[a.size] = "1204|1265|Is it the calling we hear?";
            a[a.size] = "1268|1321|How do we know?";
            break;
    }

    return a;
}
