// ============================================================================
//  qol_subs_npc_prison.gsc  -  GENERATED by zm_qol - dev\subtitles\gen_subs_npc.py (2026-09-08)
//  SUBTITLES for the NON-player voices: the announcer, Maxis, Samantha, the
//  Richtofen in Stuhlinger's head, Brutus, the bus, the TVs and radios, the
//  ghost, the possessed zombies.
// ----------------------------------------------------------------------------
//  Every function below is the stock body copied VERBATIM out of the gsc-dump
//  (dev-only /# #/ blocks dropped, same-file calls qualified explicitly, as
//  qol_subs_tomb.gsc does) with ONE line added in front of each sound builtin
//  that plays a vox alias:
//      scripts\zm\zmqol_subtitles::zmqol_subs_npc( alias, source, position, listener )
//  The builtin decides who HEARS the line, so the same arguments decide who
//  READS it - see that function's banner. 🛑 Do not hand-edit: change the
//  generator's SPEC and re-run it; the dump is the source of truth.
//
//  Each copy prints "[zm_qol] subtitles: hook ran - <name>" first. STOCK_REFERENCE
//  7a: a hook is not proven until a boot shows that line.
// ============================================================================
#include common_scripts\utility;
#include maps\mp\_utility;
#include maps\mp\zombies\_zm_utility;

main()
{
    replaceFunc( maps\mp\zombies\_zm_ai_brutus::sndbrutusvox, ::zmqol_npc_sndbrutusvox );
    replaceFunc( maps\mp\zm_alcatraz_sq_nixie::nixie_115_audio, ::zmqol_npc_nixie_115_audio );
    replaceFunc( maps\mp\zm_alcatraz_sq_nixie::nixie_935_audio, ::zmqol_npc_nixie_935_audio );
    replaceFunc( maps\mp\zm_prison_sq_final::stage_one, ::zmqol_npc_stage_one );
    replaceFunc( maps\mp\zm_prison_sq_final::nixie_final_audio_cue_code, ::zmqol_npc_nixie_final_audio_cue_code );
    replaceFunc( maps\mp\zm_prison_sq_final::play_sq_audio_log, ::zmqol_npc_play_sq_audio_log );
    replaceFunc( maps\mp\zm_prison_spoon::tomahawk_the_spoon, ::zmqol_npc_tomahawk_the_spoon );
    replaceFunc( maps\mp\zm_prison_sq_bg::take_old_weapon_and_give_reward, ::zmqol_npc_take_old_weapon_and_give_reward );
}

init()
{
}

// ----- maps\mp\zombies\_zm_ai_brutus::sndbrutusvox  (stock verbatim + 1 caption line(s)) -----
zmqol_npc_sndbrutusvox( alias, num )
{
    println( "[zm_qol] subtitles: hook ran - sndbrutusvox" );

    self endon( "brutus_cleanup" );

    if ( !isdefined( alias ) )
        return;

    num_variants = maps\mp\zombies\_zm_spawner::get_number_variants( alias );

    if ( num_variants <= 0 )
        return;

    if ( isdefined( num ) && num <= num_variants )
        num_variants = num;

    if ( !level.sndbrutusistalking )
    {
        level.sndbrutusistalking = 1;
        alias = alias + "_" + randomintrange( 0, num_variants );
        playbacktime = soundgetplaybacktime( alias );

        if ( playbacktime >= 0 )
            playbacktime = playbacktime * 0.001;
        else
            playbacktime = 1;

        scripts\zm\zmqol_subtitles::zmqol_subs_npc( alias, self, undefined, undefined );
        self playsoundontag( alias, "J_head" );
        wait( playbacktime );
        level.sndbrutusistalking = 0;
    }
}

// ----- maps\mp\zm_alcatraz_sq_nixie::nixie_115_audio  (stock verbatim + 1 caption line(s)) -----
zmqol_npc_nixie_115_audio()
{
    println( "[zm_qol] subtitles: hook ran - nixie_115_audio" );

    m_nixie_tube = getent( "nixie_tube_1", "targetname" );
    n_random_line = randomint( 3 );
    scripts\zm\zmqol_subtitles::zmqol_subs_npc( "vox_brutus_scary_voice_" + n_random_line, m_nixie_tube, undefined, undefined );
    m_nixie_tube playsoundwithnotify( "vox_brutus_scary_voice_" + n_random_line, "scary_voice" );
    m_nixie_tube waittill( "scary_voice" );
}

// ----- maps\mp\zm_alcatraz_sq_nixie::nixie_935_audio  (stock verbatim + 1 caption line(s)) -----
zmqol_npc_nixie_935_audio()
{
    println( "[zm_qol] subtitles: hook ran - nixie_935_audio" );

    if ( !( isdefined( level.music_override ) && level.music_override ) )
    {
        level.music_override = 1;
        playsoundatposition( "mus_zmb_secret_song_2", ( 0, 0, 0 ) );
        wait 140;
        level.music_override = 0;
    }
    else
    {
        m_nixie_tube = getent( "nixie_tube_1", "targetname" );
        n_random_line = randomint( 3 );
        scripts\zm\zmqol_subtitles::zmqol_subs_npc( "vox_brutus_scary_voice_" + n_random_line, m_nixie_tube, undefined, undefined );
        m_nixie_tube playsoundwithnotify( "vox_brutus_scary_voice_" + n_random_line, "scary_voice" );
        m_nixie_tube waittill( "scary_voice" );
    }
}

// ----- maps\mp\zm_prison_sq_final::stage_one  (stock verbatim + 1 caption line(s)) -----
zmqol_npc_stage_one()
{
    println( "[zm_qol] subtitles: hook ran - stage_one" );

    if ( isdefined( level.gamedifficulty ) && level.gamedifficulty == 0 )
    {
        maps\mp\zm_prison_sq_final::sq_final_easy_cleanup();
        return;
    }

    precachemodel( "p6_zm_al_audio_headset_icon" );
    flag_wait( "quest_completed_thrice" );
    flag_wait( "spoon_obtained" );
    flag_wait( "warden_blundergat_obtained" );

    for ( i = 1; i < 4; i++ )
    {
        m_nixie_tube = getent( "nixie_tube_" + i, "targetname" );
        m_nixie_tube thread maps\mp\zm_prison_sq_final::nixie_tube_scramble_protected_effects( i );
    }

    level waittill_multiple( "nixie_tube_trigger_1", "nixie_tube_trigger_2", "nixie_tube_trigger_3" );
    level thread maps\mp\zm_prison_sq_final::nixie_final_codes( 386 );
    level thread maps\mp\zm_prison_sq_final::nixie_final_codes( 481 );
    level thread maps\mp\zm_prison_sq_final::nixie_final_codes( 101 );
    level thread maps\mp\zm_prison_sq_final::nixie_final_codes( 872 );
    level waittill_multiple( "nixie_final_" + 386, "nixie_final_" + 481, "nixie_final_" + 101, "nixie_final_" + 872 );
    maps\mp\zm_prison_sq_final::nixie_tube_off();
    m_nixie_tube = getent( "nixie_tube_1", "targetname" );
    scripts\zm\zmqol_subtitles::zmqol_subs_npc( "vox_brutus_nixie_right_0", m_nixie_tube, undefined, undefined );
    m_nixie_tube playsoundwithnotify( "vox_brutus_nixie_right_0", "scary_voice" );
    m_nixie_tube waittill( "scary_voice" );
    wait 3;
    level thread maps\mp\zm_prison_sq_final::stage_two();
}

// ----- maps\mp\zm_prison_sq_final::nixie_final_audio_cue_code  (stock verbatim + 1 caption line(s)) -----
zmqol_npc_nixie_final_audio_cue_code()
{
    println( "[zm_qol] subtitles: hook ran - nixie_final_audio_cue_code" );

    m_nixie_tube = getent( "nixie_tube_1", "targetname" );
    scripts\zm\zmqol_subtitles::zmqol_subs_npc( "vox_brutus_nixie_right_0", m_nixie_tube, undefined, undefined );
    m_nixie_tube playsoundwithnotify( "vox_brutus_nixie_right_0", "scary_voice" );
    m_nixie_tube waittill( "scary_voice" );
}

// ----- maps\mp\zm_prison_sq_final::play_sq_audio_log  (stock verbatim + 1 caption line(s)) -----
zmqol_npc_play_sq_audio_log( num, a_vo, b_use_trig )
{
    println( "[zm_qol] subtitles: hook ran - play_sq_audio_log" );

    v_pos = getstruct( "sq_at_" + num, "targetname" ).origin;

    if ( !isdefined( level.m_headphones ) )
    {
        level.m_headphones = spawn( "script_model", v_pos );
        level.m_headphones ghostindemo();
        level.m_headphones setmodel( "p6_zm_al_audio_headset_icon" );
        playfxontag( level._effect["powerup_on"], level.m_headphones, "tag_origin" );
        level.m_headphones thread maps\mp\zm_prison_sq_final::headphones_rotate();
        level.m_headphones playloopsound( "zmb_spawn_powerup_loop" );
        level.m_headphones trigger_off();
    }
    else
    {
        level.m_headphones trigger_on();
        level.m_headphones.origin = v_pos;
    }

    if ( b_use_trig )
    {
        trigger = spawn( "trigger_radius", level.m_headphones.origin - vectorscale( ( 0, 0, 1 ), 80.0 ), 0, 30, 150 );
        trigger waittill( "trigger" );
        trigger delete();
    }

    level.m_headphones trigger_off();
    level setclientfield( "toggle_futz", 1 );
    players = getplayers();

    foreach ( player in players )
        maps\mp\_visionset_mgr::vsmgr_activate( "visionset", "zm_audio_log", player );

    for ( i = 0; i < a_vo.size; i++ )
    {
        scripts\zm\zmqol_subtitles::zmqol_subs_npc( a_vo[i], level.m_headphones, undefined, undefined );
        level.m_headphones playsoundwithnotify( a_vo[i], "at_done" );
        level.m_headphones waittill( "at_done" );
        wait 0.5;
    }

    level setclientfield( "toggle_futz", 0 );
    players = getplayers();

    foreach ( player in players )
        maps\mp\_visionset_mgr::vsmgr_deactivate( "visionset", "zm_audio_log", player );
}

// ----- maps\mp\zm_prison_spoon::tomahawk_the_spoon  (stock verbatim + 1 caption line(s)) -----
zmqol_npc_tomahawk_the_spoon( grenade, n_grenade_charge_power )
{
    println( "[zm_qol] subtitles: hook ran - tomahawk_the_spoon" );

    if ( self hasweapon( "spoon_zm_alcatraz" ) || self hasweapon( "spork_zm_alcatraz" ) )
        return false;

    m_spoon = getent( "pickup_spoon", "targetname" );

    if ( distancesquared( m_spoon.origin, grenade.origin ) < 40000 )
    {
        m_tomahawk = maps\mp\zombies\_zm_weap_tomahawk::tomahawk_spawn( grenade.origin );
        m_tomahawk.n_grenade_charge_power = n_grenade_charge_power;
        m_player_spoon = spawn( "script_model", grenade.origin );
        m_player_spoon setmodel( "t6_wpn_zmb_spoon_world" );
        m_player_spoon linkto( m_tomahawk );
        self maps\mp\zombies\_zm_stats::increment_client_stat( "prison_ee_spoon_acquired", 0 );
        self thread maps\mp\zombies\_zm_weap_tomahawk::tomahawk_return_player( m_tomahawk );
        self thread maps\mp\zm_prison_spoon::give_player_spoon_upon_receipt( m_tomahawk, m_player_spoon );
        self thread maps\mp\zm_prison_spoon::dip_the_spoon();
        flag_set( "spoon_obtained" );
        scripts\zm\zmqol_subtitles::zmqol_subs_npc( "vox_brutus_easter_egg_101_0", undefined, undefined, self );
        self playsoundtoplayer( "vox_brutus_easter_egg_101_0", self );
        return true;
    }

    return false;
}

// ----- maps\mp\zm_prison_sq_bg::take_old_weapon_and_give_reward  (stock verbatim + 1 caption line(s)) -----
zmqol_npc_take_old_weapon_and_give_reward( current_weapon, reward_weapon, weapon_limit_override )
{
    println( "[zm_qol] subtitles: hook ran - take_old_weapon_and_give_reward" );

    if ( !isdefined( weapon_limit_override ) )
        weapon_limit_override = 0;

    if ( weapon_limit_override == 1 )
        self takeweapon( current_weapon );
    else
    {
        primaries = self getweaponslistprimaries();

        if ( isdefined( primaries ) && primaries.size >= 2 )
            self takeweapon( current_weapon );
    }

    self giveweapon( reward_weapon );
    self switchtoweapon( reward_weapon );
    flag_set( "warden_blundergat_obtained" );
    scripts\zm\zmqol_subtitles::zmqol_subs_npc( "vox_brutus_easter_egg_872_0", undefined, undefined, self );
    self playsoundtoplayer( "vox_brutus_easter_egg_872_0", self );
}
