// ============================================================================
//  qol_subs_npc_highrise.gsc  -  GENERATED by zm_qol - dev\subtitles\gen_subs_npc.py (2026-09-08)
//  SUBTITLES for the NON-player voices: the announcer, Maxis, Samantha, the
//  Richtofen in Stuhlinger's head, Brutus, the bus, the TVs and radios, the
//  ghost, the possessed zombies.
// ----------------------------------------------------------------------------
//  Every function below is the stock body copied VERBATIM out of the gsc-dump
//  (dev-only /# #/ blocks dropped, same-file calls qualified explicitly, as
//  qol_subs_tomb.gsc does) with ONE line added in front of each sound builtin
//  that plays a vox alias:
//      scripts\zm\zmqol_subtitles::zmqol_subs_npc( alias, source, position, listener )
//  The builtin decides who HEARS the line, so the same arguments decide who
//  READS it - see that function's banner. 🛑 Do not hand-edit: change the
//  generator's SPEC and re-run it; the dump is the source of truth.
//
//  Each copy prints "[zm_qol] subtitles: hook ran - <name>" first. STOCK_REFERENCE
//  7a: a hook is not proven until a boot shows that line.
// ============================================================================
#include common_scripts\utility;
#include maps\mp\_utility;
#include maps\mp\zombies\_zm_utility;

main()
{
    replaceFunc( maps\mp\zm_highrise_sq::maxissay, ::zmqol_npc_maxissay );
    replaceFunc( maps\mp\zm_highrise_sq::richtofensay, ::zmqol_npc_richtofensay );
    replaceFunc( maps\mp\zm_highrise::survivor_vox, ::zmqol_npc_survivor_vox );
    replaceFunc( maps\mp\zm_highrise::custom_zombie_audio_func, ::zmqol_npc_custom_zombie_audio_func );
    replaceFunc( maps\mp\zombies\_zm_ai_leaper::leaper_round_spawning, ::zmqol_npc_leaper_round_spawning );
    replaceFunc( maps\mp\zombies\_zm_ai_leaper::leaper_round_tracker, ::zmqol_npc_leaper_round_tracker );
}

init()
{
    thread zmqol_npc_repoint();
}

//  STOCK_REFERENCE 7a mode 2/3: these stock functions are also reached through
//  a level.* pointer captured at map init, so the pointer is re-pointed at the
//  copy once the players are in, in case the replaceFunc alone does not take.
zmqol_npc_repoint()
{
    flag_wait( "initial_players_connected" );

    if ( isdefined( level._custom_zombie_audio_func ) )
        level._custom_zombie_audio_func = ::zmqol_npc_custom_zombie_audio_func;

    println( "[zm_qol] subtitles: NPC pointer re-points done" );
}

// ----- maps\mp\zm_highrise_sq::maxissay  (stock verbatim + 1 caption line(s)) -----
zmqol_npc_maxissay( line )
{
    println( "[zm_qol] subtitles: hook ran - maxissay" );

    level endon( "end_game" );
    level endon( "intermission" );

    if ( is_true( level.maxcompleted ) )
        return;

    if ( is_true( level.intermission ) )
        return;

    while ( is_true( level.maxis_talking ) )
        wait 0.05;

    level.maxis_talking = 1;
    players = getplayers();

    foreach ( player in players )
    {
        scripts\zm\zmqol_subtitles::zmqol_subs_npc( line, undefined, undefined, player );
        player setclientfieldtoplayer( "clientfield_sq_vo", level.sq_clientfield_vo[line] );
    }

    wait 10;
    level.maxis_talking = 0;
}

// ----- maps\mp\zm_highrise_sq::richtofensay  (stock verbatim + 1 caption line(s)) -----
zmqol_npc_richtofensay( vox_line, time )
{
    println( "[zm_qol] subtitles: hook ran - richtofensay" );

    level endon( "end_game" );
    level endon( "intermission" );

    if ( is_true( level.intermission ) )
        return;

    if ( is_true( level.richcompleted ) )
        return;

    level endon( "richtofen_c_complete" );

    if ( !isdefined( time ) )
        time = 2;

    while ( is_true( level.richtofen_talking_to_samuel ) )
        wait 1;

    if ( isdefined( level.rich_sq_player ) && is_player_valid( level.rich_sq_player ) )
    {
        scripts\zm\zmqol_subtitles::zmqol_subs_npc( vox_line, undefined, undefined, level.rich_sq_player );
        level.rich_sq_player playsoundtoplayer( vox_line, level.rich_sq_player );

        if ( !is_true( level.richtofen_talking_to_samuel ) )
            level thread maps\mp\zm_highrise_sq::richtofen_talking( time );
    }
}

// ----- maps\mp\zm_highrise::survivor_vox  (stock verbatim + 1 caption line(s)) -----
zmqol_npc_survivor_vox()
{
    println( "[zm_qol] subtitles: hook ran - survivor_vox" );

    trigger = spawn( "trigger_radius_use", ( 2398.5, -366, 1332.5 ), 0, 40, 72 );
    trigger setcursorhint( "HINT_NOICON" );
    trigger sethintstring( "" );
    trigger triggerignoreteam();
    level waittill( "power_on" );
    initiated = 0;

    while ( !initiated )
    {
        trigger waittill( "trigger", player );
        playsoundatposition( "zmb_zombie_arc", trigger.origin );
        start_time = gettime();
        end_time = start_time + 5000;

        while ( player usebuttonpressed() && player istouching( trigger ) && is_player_valid( player ) )
        {
            if ( gettime() > end_time )
                initiated = 1;

            wait 0.05;
        }
    }

    sur_num = 1;
    index = 0;
    count = 0;
    playsoundatposition( "zmb_buildable_piece_add", trigger.origin );

    while ( true )
    {
        trigger waittill( "trigger", player );

        if ( is_player_valid( player ) )
        {
            if ( sur_num == 1 )
                count = 7;
            else if ( sur_num == 2 )
                count = 5;
            else if ( sur_num == 3 )
                count = 6;
            else if ( sur_num == 4 )
                count = 4;
            else if ( sur_num == 5 )
                count = 1;

            for ( index = 0; index < count; index++ )
            {
                scripts\zm\zmqol_subtitles::zmqol_subs_npc( "vox_sur" + sur_num + "_tv_distress_" + index, trigger, undefined, undefined );
                trigger playsoundwithnotify( "vox_sur" + sur_num + "_tv_distress_" + index, "vox_sur" + sur_num + "_tv_distress_" + index + "done" );
                trigger waittill( "vox_sur" + sur_num + "_tv_distress_" + index + "done" );
                trigger waittill( "trigger", player );
            }
        }

        sur_num++;

        if ( sur_num > 5 )
            sur_num = 1;

        wait 5;
    }
}

// ----- maps\mp\zm_highrise::custom_zombie_audio_func  (stock verbatim + 1 caption line(s)) -----
zmqol_npc_custom_zombie_audio_func( alias, alias_type )
{
    println( "[zm_qol] subtitles: hook ran - custom_zombie_audio_func" );

    if ( alias_type != "behind" )
    {
        if ( isdefined( level.isstuhlingeringame ) && level.isstuhlingeringame )
        {
            if ( randomint( 100 ) > 100 - maps\mp\zm_highrise::get_custom_zombie_sound_play_frequency() )
            {
                players = get_players();

                foreach ( player in players )
                {
                    if ( isdefined( player.characterindex ) && player.characterindex == 1 )
                    {
                        level.last_custom_zombie_sound_time = gettime();
                        alias_to_play = maps\mp\zm_highrise::choose_a_line_to_play();
                        scripts\zm\zmqol_subtitles::zmqol_subs_npc( alias_to_play, undefined, undefined, player );
                        self playsoundtoplayer( alias_to_play, player );
                        continue;
                    }

                    self playsoundtoplayer( alias, player );
                }

                return;
            }
        }
    }

    self playsound( alias );
}

// ----- maps\mp\zombies\_zm_ai_leaper::leaper_round_spawning  (stock verbatim + 1 caption line(s)) -----
zmqol_npc_leaper_round_spawning()
{
    println( "[zm_qol] subtitles: hook ran - leaper_round_spawning" );

    level endon( "intermission" );
    level endon( "leaper_round_ending" );
    level.leaper_targets = getplayers();

    for ( i = 0; i < level.leaper_targets.size; i++ )
        level.leaper_targets[i].hunted_by = 0;


    if ( level.intermission )
        return;

    level.leaper_intermission = 1;
    level thread maps\mp\zombies\_zm_ai_leaper::leaper_round_accuracy_tracking();
    level thread maps\mp\zombies\_zm_ai_leaper::leaper_round_aftermath();
    players = get_players();
    wait 1;
    scripts\zm\zmqol_subtitles::zmqol_subs_npc( "vox_zmba_event_dogstart_0", undefined, ( 0, 0, 0 ), undefined );
    playsoundatposition( "vox_zmba_event_dogstart_0", ( 0, 0, 0 ) );
    wait 1;

    if ( level.leaper_round_count < 3 )
        max = players.size * level.leapers_per_player;
    else
        max = players.size * level.leapers_per_player;

    level.zombie_total = max;
    maps\mp\zombies\_zm_ai_leaper::leaper_health_increase();
    level.leaper_count = 0;

    while ( true )
    {
        b_hold_spawning_when_leapers_are_all_dead = 1;

        if ( level.leaper_count >= max && b_hold_spawning_when_leapers_are_all_dead )
        {
            wait 0.5;
            continue;
        }

        num_player_valid = get_number_of_valid_players();
        per_player = 2;

        while ( get_current_zombie_count() >= num_player_valid * per_player )
        {
            wait 2;
            num_player_valid = get_number_of_valid_players();
        }

        players = get_players();
        favorite_enemy = maps\mp\zombies\_zm_ai_leaper::get_favorite_enemy();
        spawn_point = maps\mp\zombies\_zm_ai_leaper::leaper_spawn_logic( level.enemy_dog_spawns, favorite_enemy );
        ai = spawn_zombie( level.leaper_spawners[0] );

        if ( isdefined( ai ) )
        {
            ai.favoriteenemy = favorite_enemy;
            ai.spawn_point = spawn_point;
            spawn_point thread maps\mp\zombies\_zm_ai_leaper::leaper_spawn_fx( ai, spawn_point );
            level.zombie_total--;
            level.leaper_count++;
        }

        maps\mp\zombies\_zm_ai_leaper::waiting_for_next_leaper_spawn( level.leaper_count, max );
    }
}

// ----- maps\mp\zombies\_zm_ai_leaper::leaper_round_tracker  (stock verbatim + 0 caption line(s)) -----
zmqol_npc_leaper_round_tracker()
{
    println( "[zm_qol] subtitles: hook ran - leaper_round_tracker" );

    level.leaper_round_count = 1;
    level.next_leaper_round = level.round_number + randomintrange( 4, 7 );
    old_spawn_func = level.round_spawn_func;
    old_wait_func = level.round_wait_func;

    while ( true )
    {
        level waittill( "between_round_over" );

        if ( level.round_number == level.next_leaper_round )
        {
            level.music_round_override = 1;
            old_spawn_func = level.round_spawn_func;
            old_wait_func = level.round_wait_func;
            maps\mp\zombies\_zm_ai_leaper::leaper_round_start();
            level.round_spawn_func = ::zmqol_npc_leaper_round_spawning;
            level.round_wait_func = maps\mp\zombies\_zm_ai_leaper::leaper_round_wait;
            level.next_leaper_round = level.round_number + randomintrange( 4, 6 );
        }
        else if ( flag( "leaper_round" ) )
        {
            maps\mp\zombies\_zm_ai_leaper::leaper_round_stop();
            level.round_spawn_func = old_spawn_func;
            level.round_wait_func = old_wait_func;
            level.music_round_override = 0;
            level.leaper_round_count = level.leaper_round_count + 1;
        }
    }
}
