// ============================================================================
//      scripts/zm/zm_highrise/qol_subs_lyrics_highrise.gsc
//  SUBTITLES  -  timed lyrics for this map's Easter egg songs     (v2.17.43)
//  GENERATED by modding-jobs\subs-audit-001\build_lyrics.py - do not hand-edit;
//  fix the transcript or the generator and re-run it.
// ----------------------------------------------------------------------------
//  User, 2026-09-26: *"it didn't show the actual lyrics of the song ... make sure
//  it works for all the other easter egg songs in the game"*.
//
//  Each entry is "start|end|text" (tenths of a second from the moment the song
//  starts), plus "|clean text" where the line has a word the clean setting masks.
//  scripts/zm/zmqol_subtitles.gsc zmqol_subs_music() reads this through
//  level.zmqol_subs_lyrics_func, so the root script names nothing map-specific.
//
//  Machine-transcribed from the local song audio with Demucs and Whisper
//  large-v3, then corrected against published song text. Timing comes from
//  word timestamps and has not been checked by ear.
//  Lines per song: mus_zmb_secret_song 40.
// ============================================================================

main()
{
}

init()
{
    level.zmqol_subs_lyrics_func = ::zmqol_subs_lyrics;
}

zmqol_subs_lyrics( str_alias )
{
    a = [];

    switch ( str_alias )
    {
        case "mus_zmb_secret_song":
            a[a.size] = "28|54|Xenopsylla Cheopis";
            a[a.size] = "55|82|MDCLXV";
            a[a.size] = "84|135|We used the helicase to bind the CXV";
            a[a.size] = "135|159|Non-responsive";
            a[a.size] = "163|216|And their ferritin is high in vivo";
            a[a.size] = "217|266|But still seem to be alive.";
            a[a.size] = "269|320|Controls are feeling fine despite the awful sounds";
            a[a.size] = "335|376|Brought the incidence of tallowy offal down";
            a[a.size] = "377|394|We all fall down.";
            a[a.size] = "395|421|We fall down.";
            a[a.size] = "427|453|We all fall down.";
            a[a.size] = "454|480|We fall down.";
            a[a.size] = "505|558|The martyr's brethren were not to be set free";
            a[a.size] = "565|616|In vitro planet Earth, in vivo you and me";
            a[a.size] = "616|683|He had them watch me and lock everything around.";
            a[a.size] = "683|734|He told me, you seem awful down.";
            a[a.size] = "734|754|We all fall down.";
            a[a.size] = "754|781|We fall down.";
            a[a.size] = "782|810|We all fall down.";
            a[a.size] = "811|841|We fall down.";
            a[a.size] = "856|920|It will end in flashes and we'll choke on ashes.";
            a[a.size] = "922|959|And we'll all fall down";
            a[a.size] = "991|1026|Long lives the phantom.";
            a[a.size] = "1026|1088|I hear him sing and scream out his anthem";
            a[a.size] = "1111|1166|I feel the shadows crying, running";
            a[a.size] = "1166|1185|Coming for me.";
            a[a.size] = "1185|1210|Too dark to see.";
            a[a.size] = "1211|1237|We all fall down.";
            a[a.size] = "1237|1261|We fall down.";
            a[a.size] = "1265|1292|We all fall down.";
            a[a.size] = "1293|1321|We fall down.";
            a[a.size] = "1331|1397|It will end in flashes and we'll choke on ashes.";
            a[a.size] = "1397|1438|And we'll all fall down.";
            a[a.size] = "1448|1505|It will end in ashes of their lies.";
            a[a.size] = "1514|1567|We can still see flashes in our eyes.";
            a[a.size] = "1570|1636|But until it crashes and the atom smashes.";
            a[a.size] = "1636|1693|All our minds will just fade away.";
            a[a.size] = "1694|1730|It will end in flashes.";
            a[a.size] = "1732|1756|And we'll choke on ashes";
            a[a.size] = "1757|1776|And we'll fall.";
            break;
    }

    return a;
}
