// T6 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool
#include character\clientscripts\c_zom_zombie_scientist;

main()
{
    character\clientscripts\c_zom_zombie_scientist::main();
    self._aitype = "zm_highrise_basic_02";
}

#using_animtree("zm_highrise_basic");

precache( ai_index )
{
    // DLC5 Moon Wave Gun death animations; keep before precacheanimstatedef.
    dummy_anim_ref = %ai_zombie_microwave_death_a;
    dummy_anim_ref = %ai_zombie_microwave_death_b;
    dummy_anim_ref = %ai_zombie_microwave_death_c;
    dummy_anim_ref = %ai_zombie_microwave_death_walking_a;
    dummy_anim_ref = %ai_zombie_microwave_death_walking_b;
    dummy_anim_ref = %ai_zombie_microwave_death_walking_c;
    dummy_anim_ref = %ai_zombie_crawl_microwave_death_a;
    dummy_anim_ref = %ai_zombie_crawl_microwave_death_b;
    dummy_anim_ref = %ai_zombie_crawl_microwave_death_c;
    dummy_anim_ref = %ai_zombie_crawl_microwave_death_walking_a;
    dummy_anim_ref = %ai_zombie_crawl_microwave_death_walking_b;
    dummy_anim_ref = %ai_zombie_crawl_microwave_death_walking_c;    character\clientscripts\c_zom_zombie_scientist::precache();
    usefootsteptable( ai_index, "default_ai" );
    precacheanimstatedef( ai_index, #animtree, "zm_highrise_basic" );
    setdemolockonvalues( ai_index, 100, 60, -15, 60, 30, -5, 60 );
}
