// T6 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool
#include character\clientscripts\c_zom_zombie5_01;
#include character\clientscripts\c_zom_zombie5_02;
#include character\clientscripts\c_zom_zombie5_03;

main()
{
    switch ( self getcharacterindex() )
    {
        case 0:
            character\clientscripts\c_zom_zombie5_01::main();
            break;
        case 1:
            character\clientscripts\c_zom_zombie5_02::main();
            break;
        case 2:
            character\clientscripts\c_zom_zombie5_03::main();
            break;
    }

    self._aitype = "zm_transit_basic_05";
}

#using_animtree("zm_transit_basic");

precache( ai_index )
{
    dummy_anim_ref = %ai_zombie_microwave_death_a;
    dummy_anim_ref = %ai_zombie_microwave_death_b;
    dummy_anim_ref = %ai_zombie_microwave_death_c;
    dummy_anim_ref = %ai_zombie_microwave_death_walking_a;
    dummy_anim_ref = %ai_zombie_microwave_death_walking_b;
    dummy_anim_ref = %ai_zombie_microwave_death_walking_c;
    dummy_anim_ref = %ai_zombie_crawl_microwave_death_a;
    dummy_anim_ref = %ai_zombie_crawl_microwave_death_b;
    dummy_anim_ref = %ai_zombie_crawl_microwave_death_c;
    dummy_anim_ref = %ai_zombie_crawl_microwave_death_walking_a;
    dummy_anim_ref = %ai_zombie_crawl_microwave_death_walking_b;
    dummy_anim_ref = %ai_zombie_crawl_microwave_death_walking_c;
    dummy_anim_ref = %ai_zombie_freeze_death_a;
    dummy_anim_ref = %ai_zombie_freeze_death_b;
    dummy_anim_ref = %ai_zombie_freeze_death_c;
    dummy_anim_ref = %ai_zombie_freeze_death_d;
    dummy_anim_ref = %ai_zombie_freeze_death_e;
    dummy_anim_ref = %ai_zombie_crawl_freeze_death_01;
    dummy_anim_ref = %ai_zombie_crawl_freeze_death_02;

    // Electric Cherry stun (2026-09-28): the five clips stock's core
    // _zm_perk_electric_cherry::electric_cherry_stun() needs on this tree. Mob's
    // aitype carries them natively; the parser checks the list compiled INTO the
    // aitype, so zm_afterlife_stun in the .asd dies at BG_AnimStateDef_Parse
    // without these (see zone_source\disabled_ww_animtrees README).
    dummy_anim_ref = %ai_zombie_afterlife_stun_a;
    dummy_anim_ref = %ai_zombie_afterlife_stun_b;
    dummy_anim_ref = %ai_zombie_afterlife_stun_c;
    dummy_anim_ref = %ai_zombie_afterlife_stun_d;
    dummy_anim_ref = %ai_zombie_afterlife_stun_e;

    character\clientscripts\c_zom_zombie5_01::precache();
    character\clientscripts\c_zom_zombie5_02::precache();
    character\clientscripts\c_zom_zombie5_03::precache();
    usefootsteptable( ai_index, "default_ai" );
    precacheanimstatedef( ai_index, #animtree, "zm_transit_basic" );
    setdemolockonvalues( ai_index, 100, 60, -15, 60, 30, -5, 60 );
}
