#!/usr/bin/env python3
"""
make_octagonal_map_zone.py - regenerate zone_source/octagonal_map/zm_octagonal.zone

WHAT IT IS FOR
--------------
Octagonal Ascension ships standalone, so its release mod.ff carries everything
the map needs: the mystery box, the window barriers, the perk machines, 35
weapons, the Hellhound chain, the player models. v2.17.1 pasted that whole
fastfile into zm_qol's shared mod.ff, which loads AHEAD OF EVERY STOCK MAP
ZONE, and Origins stopped booting:

    COM_ERROR: Attempting to override asset 'zmcore_basicwoodbarrier'
               from zone 'mod' with zone 'zm_tomb'

The payload now goes into zm_octagonal.ff, which only loads when that map does.
This script splits the release's asset list into those two halves and writes the
map-side zone. The frontend half is hand-maintained in
zone_source/mod_custom_maps.zone.

Two things get left out of the map zone:

  * the 19 frontend assets mod_custom_maps.zone declares, and the four generics
    (overlay_low_health, $white, white) common_zm already provides everywhere;
  * anything zm_qol's own mod.ff owns - mod.ff loads first, so a name in both
    is the same COM_ERROR with the zones swapped.

And 685 implicit dependencies that mod.ff owns - camos, attachments, muzzle
flash fx, weapon techsets - are emitted as REFERENCES (a leading comma), so the
map reads the mod's copies instead of shipping stock ones over the top of them.
Regenerate that list with modding-jobs/octagonal-ascension-003/clashes.py after
any relink, then run this script again.

USAGE
    python make_octagonal_map_zone.py --payload   <release mod.zone dump>
                                      --mod-list  <Unlinker --list of mod.ff>
                                      --map-zone  <1.2beta zm_octagonal.zone>
                                      --refs      <clash reference list>
                                      --out       zone_source/octagonal_map
"""

import argparse
import os
import re

# Declared in mod.ff by zone_source/mod_custom_maps.zone.
IN_MOD_FF = {
    ("image", "loadscreen"),
    ("stringtable", "zm/gametypestable.csv"),
    ("stringtable", "zm/mapstable.csv"),
    ("image", "menu_zm_map_signpost_octagonal"),
    ("material", "menu_zm_map_signpost_octagonal"),
    ("image", "menu_zm_map_octagonal"),
    ("image", "menu_zm_map_octagonal_blur"),
    ("material", "menu_zm_octagonal_map"),
    ("material", "menu_zm_octagonal_map_blur"),
    ("image", "menu_zm_map_octagonal_zclassic"),
    ("material", "menu_zm_octagonal_zclassic_octagonal"),
    ("material", "loadscreen_zm_octagonal_zstandard_zm_octagonal"),
    ("material", "loadscreen_zm_octagonal_zclassic_zm_octagonal"),
    ("material", "loadscreen_zm_octagonal_zstandard_"),
    ("material", "loadscreen_zm_octagonal_zclassic_"),
    ("material", "loadscreen_zm_octagonal_zclassic_mp_castaway"),
    ("material", "loadscreen_zm_octagonal_zstandard_mp_castaway"),
    ("material", "loadscreen_zm_octagonal_zclassic_octagonal"),
    ("material", "loadscreen_zm_octagonal_zstandard_octagonal"),
}

# common_zm.ff owns all four and loads on every map, this one included.
DROPPED = {
    ("image", "overlay_low_health"),
    ("material", "overlay_low_health"),
    ("image", "$white"),
    ("material", "white"),
}

# The zombies image banks the payload's textures read their pixels from. The
# 1.2beta map zone only asks for the castaway and frontend banks, because the
# release kept these assets in its mod.ff, which asked for these five.
EXTRA_IPAKS = ["mp", "so", "patch", "zm", "patch_zm"]

BANNER = """
// ============================================================================
//  THE CUSTOM MAP'S PAYLOAD LIVES HERE, NOT IN zm_qol's mod.ff.
//
//  Octagonal Ascension ships standalone, so its release mod.ff carries
//  everything the map needs to run. zm_qol pasted that whole fastfile into its
//  own mod.ff in v2.17.1, and mod.ff loads AHEAD OF EVERY STOCK MAP ZONE:
//
//      COM_ERROR: Attempting to override asset 'zmcore_basicwoodbarrier'
//                 from zone 'mod' with zone 'zm_tomb'
//
//  Origins would not boot. This fastfile only loads when this map loads, so the
//  same assets are harmless here.
//
//  GENERATED by make_octagonal_map_zone.py - do NOT hand-edit. Build it with
//  build_octagonal_map.bat, which needs the 1.2beta source capture.
// ============================================================================
"""

REF_BANNER = """
// --- REFERENCES, NOT COPIES ------------------------------------------------
//  Implicit dependencies of the payload that zm_qol's mod.ff already owns:
//  camos, attachments, muzzle-flash fx, weapon techsets. mod.ff loads first, so
//  owning them here would override the mod's own copies on this map and only
//  this map - the Wave Gun would flash with stock fx on Octagonal and with
//  zm_qol's everywhere else. A leading comma declares the name without the data.
"""

ASSET_LINE = re.compile(r"^([a-z0-9_]+), (.*)$")


def read_owned(path):
    """(type, name) a fastfile dump actually OWNS, references excluded."""
    owned = set()
    with open(path, encoding="utf-8", errors="replace") as fh:
        for line in fh:
            m = ASSET_LINE.match(line.rstrip("\n"))
            if m and not m.group(2).startswith(","):
                owned.add((m.group(1), m.group(2)))
    return owned


def split_zone_line(line):
    """-> (type, name, is_reference) or None for comments and directives."""
    body = line.split("//")[0].strip()
    if not body or body.startswith(">") or "," not in body:
        return None
    asset_type, rest = body.split(",", 1)
    return asset_type.strip(), rest.strip().lstrip(","), rest.startswith(",")


def main():
    proj = os.path.dirname(os.path.abspath(__file__))
    ap = argparse.ArgumentParser()
    ap.add_argument("--payload", required=True)
    ap.add_argument("--mod-list", required=True)
    ap.add_argument("--map-zone", required=True)
    ap.add_argument("--refs")
    ap.add_argument("--out", default=os.path.join(proj, "zone_source",
                                                  "octagonal_map"))
    args = ap.parse_args()

    mod_ff = read_owned(args.mod_list)
    os.makedirs(args.out, exist_ok=True)

    map_lines = open(args.map_zone, encoding="utf-8",
                     errors="replace").read().splitlines()
    map_assets = set()
    for line in map_lines:
        parsed = split_zone_line(line)
        if parsed:
            map_assets.add(parsed[:2])

    kept = []
    skipped = {"menu": 0, "generic": 0, "in_mod_ff": 0, "in_map": 0}
    for line in open(args.payload, encoding="utf-8", errors="replace"):
        line = line.rstrip("\n")
        parsed = split_zone_line(line)
        if not parsed:
            continue
        asset_type, name, is_reference = parsed
        key = (asset_type, name)
        if key in IN_MOD_FF:
            skipped["menu"] += 1
        elif key in DROPPED:
            skipped["generic"] += 1
        elif not is_reference and key in mod_ff:
            skipped["in_mod_ff"] += 1
        elif key in map_assets:
            skipped["in_map"] += 1
        else:
            kept.append(line)

    header = [l for l in map_lines if l.strip().startswith(">")]
    body = [l for l in map_lines if not l.strip().startswith(">")]
    have = {l.strip() for l in header}
    for bank in EXTRA_IPAKS:
        directive = ">level.ipak_read,{}".format(bank)
        if directive not in have:
            header.append(directive)

    out = os.path.join(args.out, "zm_octagonal.zone")
    with open(out, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(header) + "\n")
        fh.write(BANNER)
        refs = 0
        if args.refs and os.path.isfile(args.refs):
            fh.write(REF_BANNER)
            for line in open(args.refs, encoding="utf-8"):
                line = line.strip()
                if not line:
                    continue
                asset_type, name = line.split(",", 1)
                fh.write("{},,{}\n".format(asset_type, name))
                refs += 1
        fh.write("\n".join(kept))
        fh.write("\n\n// --- the map's own assets, unchanged from 1.2beta ---\n")
        fh.write("\n".join(body) + "\n")

    print("payload assets kept:              {}".format(len(kept)))
    print("references emitted:               {}".format(refs))
    print("left to mod_custom_maps.zone:     {menu}".format(**skipped))
    print("left to common_zm:                {generic}".format(**skipped))
    print("already owned by mod.ff:          {in_mod_ff}".format(**skipped))
    print("already in the map's own zone:    {in_map}".format(**skipped))
    print("wrote {}".format(out))


if __name__ == "__main__":
    main()
