// ============================================================================
//  qol_subs_npc_tomb.gsc  -  GENERATED by zm_qol - dev\subtitles\gen_subs_npc.py (2026-09-08)
//  SUBTITLES for the NON-player voices: the announcer, Maxis, Samantha, the
//  Richtofen in Stuhlinger's head, Brutus, the bus, the TVs and radios, the
//  ghost, the possessed zombies.
// ----------------------------------------------------------------------------
//  Every function below is the stock body copied VERBATIM out of the gsc-dump
//  (dev-only /# #/ blocks dropped, same-file calls qualified explicitly, as
//  qol_subs_tomb.gsc does) with ONE line added in front of each sound builtin
//  that plays a vox alias:
//      scripts\zm\zmqol_subtitles::zmqol_subs_npc( alias, source, position, listener )
//  The builtin decides who HEARS the line, so the same arguments decide who
//  READS it - see that function's banner. 🛑 Do not hand-edit: change the
//  generator's SPEC and re-run it; the dump is the source of truth.
//
//  Each copy prints "[zm_qol] subtitles: hook ran - <name>" first. STOCK_REFERENCE
//  7a: a hook is not proven until a boot shows that line.
// ============================================================================
#include common_scripts\utility;
#include maps\mp\_utility;
#include maps\mp\zombies\_zm_utility;

main()
{
    replaceFunc( maps\mp\zm_tomb_vo::samanthasayvoplay, ::zmqol_npc_samanthasayvoplay );
    replaceFunc( maps\mp\zm_tomb_vo::maxissayvoplay, ::zmqol_npc_maxissayvoplay );
    replaceFunc( maps\mp\zm_tomb_vo::play_maxis_audio_log, ::zmqol_npc_play_maxis_audio_log );
    replaceFunc( maps\mp\zm_tomb_vo::watch_one_shot_samantha_clue, ::zmqol_npc_watch_one_shot_samantha_clue );
    replaceFunc( maps\mp\zm_tomb_vo::play_sam_promises_conversation, ::zmqol_npc_play_sam_promises_conversation );
    replaceFunc( maps\mp\zm_tomb_ee_main::zombie_blood_hint_watch, ::zmqol_npc_zombie_blood_hint_watch );
    replaceFunc( maps\mp\zm_tomb_ee_side::tablet_cleanliness_chastise, ::zmqol_npc_tablet_cleanliness_chastise );
    replaceFunc( maps\mp\zm_tomb_capture_zones::generator_initiated_vo, ::zmqol_npc_generator_initiated_vo );
    replaceFunc( maps\mp\zm_tomb_capture_zones::zone_capture_complete_vo, ::zmqol_npc_zone_capture_complete_vo );
    replaceFunc( maps\mp\zm_tomb_capture_zones::generator_interrupted_vo, ::zmqol_npc_generator_interrupted_vo );
    replaceFunc( maps\mp\zm_tomb_capture_zones::generator_compromised_vo, ::zmqol_npc_generator_compromised_vo );
    replaceFunc( maps\mp\zm_tomb_capture_zones::generator_deactivated_vo, ::zmqol_npc_generator_deactivated_vo );
    replaceFunc( maps\mp\zm_tomb_giant_robot::play_timeout_warning_vo, ::zmqol_npc_play_timeout_warning_vo );
    replaceFunc( maps\mp\zm_tomb_ee_main_step_3::ready_to_activate, ::zmqol_npc_ready_to_activate );
    replaceFunc( maps\mp\zm_tomb_ee_main_step_3::activate_fire_link, ::zmqol_npc_activate_fire_link );
    replaceFunc( maps\mp\zm_tomb_ee_main_step_3::fire_link_cooldown, ::zmqol_npc_fire_link_cooldown );
    replaceFunc( maps\mp\zm_tomb_ee_main_step_5::quadrotor_pickup_think, ::zmqol_npc_quadrotor_pickup_think );
}

init()
{
}

// ----- maps\mp\zm_tomb_vo::samanthasayvoplay  (stock verbatim + 1 caption line(s)) -----
zmqol_npc_samanthasayvoplay( e_source, vox_line )
{
    println( "[zm_qol] subtitles: hook ran - samanthasayvoplay" );

    scripts\zm\zmqol_subtitles::zmqol_subs_npc( vox_line, e_source, undefined, undefined );
    e_source playsoundwithnotify( vox_line, "sound_done" + vox_line );
    e_source waittill( "sound_done" + vox_line );
    level.sam_talking = 0;
    level notify( "SamanthaSay_vo_finished" );
}

// ----- maps\mp\zm_tomb_vo::maxissayvoplay  (stock verbatim + 1 caption line(s)) -----
zmqol_npc_maxissayvoplay( m_vo_spot, vox_line )
{
    println( "[zm_qol] subtitles: hook ran - maxissayvoplay" );

    scripts\zm\zmqol_subtitles::zmqol_subs_npc( vox_line, m_vo_spot, undefined, undefined );
    m_vo_spot playsoundwithnotify( vox_line, "sound_done" + vox_line );
    m_vo_spot waittill_either( "sound_done" + vox_line, "death" );
    level.maxis_talking = 0;
    level notify( "MaxisSay_vo_finished" );
}

// ----- maps\mp\zm_tomb_vo::play_maxis_audio_log  (stock verbatim + 1 caption line(s)) -----
zmqol_npc_play_maxis_audio_log( v_trigger_origin, n_audiolog_id )
{
    println( "[zm_qol] subtitles: hook ran - play_maxis_audio_log" );

    a_audiolog = maps\mp\zm_tomb_vo::get_audiolog_vo();
    a_audiolog_to_play = a_audiolog[n_audiolog_id];

    if ( n_audiolog_id == 4 )
        flag_set( "maxis_audiolog_gr0_playing" );
    else if ( n_audiolog_id == 5 )
        flag_set( "maxis_audiolog_gr1_playing" );
    else if ( n_audiolog_id == 6 )
        flag_set( "maxis_audiolog_gr2_playing" );

    e_vo_origin = spawn( "script_origin", v_trigger_origin );
    flag_set( "maxis_audio_log_" + n_audiolog_id );
    a_s_triggers = getstructarray( "maxis_audio_log", "targetname" );

    foreach ( s_trigger in a_s_triggers )
    {
        if ( s_trigger.script_int == n_audiolog_id )
            break;
    }

    level thread maps\mp\zombies\_zm_unitrigger::unregister_unitrigger( s_trigger.unitrigger_stub );

    for ( i = 0; i < a_audiolog_to_play.size; i++ )
    {
        scripts\zm\zmqol_subtitles::zmqol_subs_npc( a_audiolog_to_play[i], e_vo_origin, undefined, undefined );
        e_vo_origin playsoundwithnotify( a_audiolog_to_play[i], a_audiolog_to_play[i] + "_done" );
        e_vo_origin waittill( a_audiolog_to_play[i] + "_done" );
    }

    e_vo_origin delete();

    if ( n_audiolog_id == 4 )
        flag_clear( "maxis_audiolog_gr0_playing" );
    else if ( n_audiolog_id == 5 )
        flag_clear( "maxis_audiolog_gr1_playing" );
    else if ( n_audiolog_id == 6 )
        flag_clear( "maxis_audiolog_gr2_playing" );

    level thread maps\mp\zombies\_zm_unitrigger::register_static_unitrigger( s_trigger.unitrigger_stub, maps\mp\zm_tomb_vo::maxis_audio_log_think );
}

// ----- maps\mp\zm_tomb_vo::watch_one_shot_samantha_clue  (stock verbatim + 1 caption line(s)) -----
zmqol_npc_watch_one_shot_samantha_clue( str_line, str_notify, str_endon )
{
    println( "[zm_qol] subtitles: hook ran - watch_one_shot_samantha_clue" );

    if ( isdefined( str_endon ) )
        level endon( str_endon );

    if ( !isdefined( level.next_samantha_clue_time ) )
        level.next_samantha_clue_time = gettime();

    while ( true )
    {
        level waittill( str_notify, e_player );
        wait 10;

        if ( isdefined( e_player ) && ( isdefined( e_player.vo_promises_playing ) && e_player.vo_promises_playing ) )
            continue;

        while ( isdefined( level.sam_talking ) && level.sam_talking )
            wait_network_frame();

        if ( level.next_samantha_clue_time > gettime() )
            continue;

        if ( !isplayer( e_player ) )
        {
            a_players = getplayers();

            foreach ( player in a_players )
            {
                if ( player.zombie_vars["zombie_powerup_zombie_blood_on"] )
                {
                    e_player = player;
                    break;
                }
            }
        }

        if ( isdefined( e_player ) && isplayer( e_player ) && e_player.zombie_vars["zombie_powerup_zombie_blood_on"] && flag( "samantha_intro_done" ) )
        {
            flag_waitopen( "story_vo_playing" );
            flag_set( "story_vo_playing" );

            while ( isdefined( e_player.isspeaking ) && e_player.isspeaking )
                wait_network_frame();

            if ( !is_player_valid( e_player ) )
                continue;

            maps\mp\zm_tomb_vo::set_players_dontspeak( 1 );
            level.sam_talking = 1;
            scripts\zm\zmqol_subtitles::zmqol_subs_npc( str_line, undefined, undefined, e_player );
            e_player playsoundtoplayer( str_line, e_player );
            n_duration = soundgetplaybacktime( str_line );
            wait( n_duration / 1000 );
            level.sam_talking = 0;
            level.next_samantha_clue_time = gettime() + 300000;
            flag_clear( "story_vo_playing" );
            maps\mp\zm_tomb_vo::set_players_dontspeak( 0 );
            return;
        }
    }
}

// ----- maps\mp\zm_tomb_vo::play_sam_promises_conversation  (stock verbatim + 2 caption line(s)) -----
zmqol_npc_play_sam_promises_conversation( a_promises )
{
    println( "[zm_qol] subtitles: hook ran - play_sam_promises_conversation" );

    for ( i = 0; i < a_promises.size; i++ )
    {
        self endon( "zombie_blood_over" );
        self endon( "disconnect" );

        if ( issubstr( a_promises[i], "sam_sam" ) || issubstr( a_promises[i], "samantha" ) )
        {
            self thread maps\mp\zm_tomb_vo::sam_promises_conversation_ended_early( a_promises[i] );
            scripts\zm\zmqol_subtitles::zmqol_subs_npc( a_promises[i], undefined, undefined, self );
            self playsoundtoplayer( a_promises[i], self );
            n_duration = soundgetplaybacktime( a_promises[i] );
            wait( n_duration / 1000 );
            self notify( "promises_VO_end_early" );
        }
        else
        {
            scripts\zm\zmqol_subtitles::zmqol_subs_npc( a_promises[i], self, undefined, undefined );
            self playsoundwithnotify( a_promises[i], "player_done" );
            self waittill( "player_done" );
        }

        wait 0.3;
    }
}

// ----- maps\mp\zm_tomb_ee_main::zombie_blood_hint_watch  (stock verbatim + 2 caption line(s)) -----
zmqol_npc_zombie_blood_hint_watch()
{
    println( "[zm_qol] subtitles: hook ran - zombie_blood_hint_watch" );

    n_curr_step = level.n_ee_step;
    a_player_hint[0] = 0;
    a_player_hint[1] = 0;
    a_player_hint[2] = 0;
    a_player_hint[3] = 0;

    while ( !flag( "ee_samantha_released" ) )
    {
        level waittill( "player_zombie_blood", e_player );

        if ( n_curr_step != level.n_ee_step )
        {
            n_curr_step = level.n_ee_step;

            for ( i = 0; i < a_player_hint.size; i++ )
                a_player_hint[i] = 0;
        }

        if ( !a_player_hint[e_player.characterindex] )
        {
            wait( randomfloatrange( 3, 7 ) );

            if ( isdefined( e_player.vo_promises_playing ) && e_player.vo_promises_playing )
                continue;

            while ( isdefined( level.sam_talking ) && level.sam_talking )
                wait 0.05;

            if ( isdefined( e_player ) && isplayer( e_player ) && e_player.zombie_vars["zombie_powerup_zombie_blood_on"] )
            {
                a_player_hint[e_player.characterindex] = 1;
                maps\mp\zm_tomb_vo::set_players_dontspeak( 1 );
                level.sam_talking = 1;
                str_vox = maps\mp\zm_tomb_ee_main::get_zombie_blood_hint_vox();
                scripts\zm\zmqol_subtitles::zmqol_subs_npc( str_vox, undefined, undefined, e_player );
                e_player playsoundtoplayer( str_vox, e_player );
                n_duration = soundgetplaybacktime( str_vox );
                wait( n_duration / 1000 );
                level.sam_talking = 0;
                maps\mp\zm_tomb_vo::set_players_dontspeak( 0 );
            }
        }
        else if ( randomint( 100 ) < 20 )
        {
            wait( randomfloatrange( 3, 7 ) );

            if ( isdefined( e_player.vo_promises_playing ) && e_player.vo_promises_playing )
                continue;

            while ( isdefined( level.sam_talking ) && level.sam_talking )
                wait 0.05;

            if ( isdefined( e_player ) && isplayer( e_player ) && e_player.zombie_vars["zombie_powerup_zombie_blood_on"] )
            {
                str_vox = maps\mp\zm_tomb_ee_main::get_zombie_blood_hint_generic_vox();

                if ( isdefined( str_vox ) )
                {
                    maps\mp\zm_tomb_vo::set_players_dontspeak( 1 );
                    level.sam_talking = 1;
                    scripts\zm\zmqol_subtitles::zmqol_subs_npc( str_vox, undefined, undefined, e_player );
                    e_player playsoundtoplayer( str_vox, e_player );
                    n_duration = soundgetplaybacktime( str_vox );
                    wait( n_duration / 1000 );
                    level.sam_talking = 0;
                    maps\mp\zm_tomb_vo::set_players_dontspeak( 0 );
                }
            }
        }
    }
}

// ----- maps\mp\zm_tomb_ee_side::tablet_cleanliness_chastise  (stock verbatim + 1 caption line(s)) -----
zmqol_npc_tablet_cleanliness_chastise( e_player, b_cleaned )
{
    println( "[zm_qol] subtitles: hook ran - tablet_cleanliness_chastise" );

    if ( !isdefined( b_cleaned ) )
        b_cleaned = 0;

    if ( !isdefined( e_player ) || isdefined( level.sam_talking ) && level.sam_talking || flag( "story_vo_playing" ) )
        return;

    flag_set( "story_vo_playing" );
    e_player maps\mp\zm_tomb_vo::set_player_dontspeak( 1 );
    level.sam_talking = 1;
    str_line = "vox_sam_generic_chastise_7";

    if ( b_cleaned )
        str_line = "vox_sam_generic_chastise_8";

    if ( isdefined( e_player ) )
    {
        scripts\zm\zmqol_subtitles::zmqol_subs_npc( str_line, undefined, undefined, e_player );
        e_player playsoundtoplayer( str_line, e_player );
    }

    n_duration = soundgetplaybacktime( str_line );
    wait( n_duration / 1000 );
    level.sam_talking = 0;
    flag_clear( "story_vo_playing" );

    if ( isdefined( e_player ) )
        e_player maps\mp\zm_tomb_vo::set_player_dontspeak( 0 );
}

// ----- maps\mp\zm_tomb_capture_zones::generator_initiated_vo  (stock verbatim + 1 caption line(s)) -----
zmqol_npc_generator_initiated_vo()
{
    println( "[zm_qol] subtitles: hook ran - generator_initiated_vo" );

    e_vo_origin = spawn( "script_origin", self.origin );
    level.maxis_generator_vo = 1;
    scripts\zm\zmqol_subtitles::zmqol_subs_npc( "vox_maxi_generator_initiate_0", e_vo_origin, undefined, undefined );
    e_vo_origin playsoundwithnotify( "vox_maxi_generator_initiate_0", "vox_maxi_generator_initiate_0_done" );
    e_vo_origin waittill( "vox_maxi_generator_initiate_0_done" );
    level.maxis_generator_vo = 0;
    e_vo_origin delete();
}

// ----- maps\mp\zm_tomb_capture_zones::zone_capture_complete_vo  (stock verbatim + 2 caption line(s)) -----
zmqol_npc_zone_capture_complete_vo()
{
    println( "[zm_qol] subtitles: hook ran - zone_capture_complete_vo" );

    e_vo_origin = spawn( "script_origin", self.origin );
    scripts\zm\zmqol_subtitles::zmqol_subs_npc( "vox_maxi_generator_process_complete_0", e_vo_origin, undefined, undefined );
    e_vo_origin playsoundwithnotify( "vox_maxi_generator_process_complete_0", "vox_maxi_generator_process_complete_0_done" );
    e_vo_origin waittill( "vox_maxi_generator_process_complete_0_done" );
    scripts\zm\zmqol_subtitles::zmqol_subs_npc( "vox_maxi_generator_" + self.script_int + "_activated_0", e_vo_origin, undefined, undefined );
    e_vo_origin playsoundwithnotify( "vox_maxi_generator_" + self.script_int + "_activated_0", "vox_maxi_generator_" + self.script_int + "_activated_0_done" );
    e_vo_origin waittill( "vox_maxi_generator_" + self.script_int + "_activated_0_done" );
    e_vo_origin delete();
}

// ----- maps\mp\zm_tomb_capture_zones::generator_interrupted_vo  (stock verbatim + 1 caption line(s)) -----
zmqol_npc_generator_interrupted_vo()
{
    println( "[zm_qol] subtitles: hook ran - generator_interrupted_vo" );

    e_vo_origin = spawn( "script_origin", self.origin );
    scripts\zm\zmqol_subtitles::zmqol_subs_npc( "vox_maxi_generator_interrupted_0", e_vo_origin, undefined, undefined );
    e_vo_origin playsoundwithnotify( "vox_maxi_generator_interrupted_0", "vox_maxi_generator_interrupted_0_done" );
    e_vo_origin waittill( "vox_maxi_generator_interrupted_0_done" );
    e_vo_origin delete();
}

// ----- maps\mp\zm_tomb_capture_zones::generator_compromised_vo  (stock verbatim + 1 caption line(s)) -----
zmqol_npc_generator_compromised_vo()
{
    println( "[zm_qol] subtitles: hook ran - generator_compromised_vo" );

    e_vo_origin = spawn( "script_origin", self.origin );
    scripts\zm\zmqol_subtitles::zmqol_subs_npc( "vox_maxi_generator_" + self.script_int + "_compromised_0", e_vo_origin, undefined, undefined );
    e_vo_origin playsoundwithnotify( "vox_maxi_generator_" + self.script_int + "_compromised_0", "vox_maxi_generator_" + self.script_int + "_compromised_0_done" );
    e_vo_origin waittill( "vox_maxi_generator_" + self.script_int + "_compromised_0_done" );
    e_vo_origin delete();
}

// ----- maps\mp\zm_tomb_capture_zones::generator_deactivated_vo  (stock verbatim + 1 caption line(s)) -----
zmqol_npc_generator_deactivated_vo()
{
    println( "[zm_qol] subtitles: hook ran - generator_deactivated_vo" );

    e_vo_origin = spawn( "script_origin", self.origin );
    scripts\zm\zmqol_subtitles::zmqol_subs_npc( "vox_maxi_generator_" + self.script_int + "_deactivated_0", e_vo_origin, undefined, undefined );
    e_vo_origin playsoundwithnotify( "vox_maxi_generator_" + self.script_int + "_deactivated_0", "vox_maxi_generator_" + self.script_int + "_deactivated_0_done" );
    e_vo_origin waittill( "vox_maxi_generator_" + self.script_int + "_deactivated_0_done" );
    e_vo_origin delete();
}

// ----- maps\mp\zm_tomb_giant_robot::play_timeout_warning_vo  (stock verbatim + 3 caption line(s)) -----
zmqol_npc_play_timeout_warning_vo( n_robot_id )
{
    println( "[zm_qol] subtitles: hook ran - play_timeout_warning_vo" );

    flag_set( "timeout_vo_robot_" + n_robot_id );
    s_origin = getstruct( "eject_warning_fx_robot_" + n_robot_id, "targetname" );
    e_vo_origin = spawn_model( "tag_origin", s_origin.origin );
    scripts\zm\zmqol_subtitles::zmqol_subs_npc( "vox_maxi_purge_robot_0", e_vo_origin, undefined, undefined );
    e_vo_origin playsoundwithnotify( "vox_maxi_purge_robot_0", "vox_maxi_purge_robot_0_done" );
    e_vo_origin waittill( "vox_maxi_purge_robot_0_done" );
    a_players = getplayers();

    foreach ( player in a_players )
    {
        if ( isdefined( player.in_giant_robot_head ) && player.in_giant_robot_head == n_robot_id )
        {
            if ( !( isdefined( player.giant_robot_transition ) && player.giant_robot_transition ) )
            {
                if ( !( isdefined( player.dontspeak ) && player.dontspeak ) )
                {
                    player maps\mp\zombies\_zm_audio::create_and_play_dialog( "general", "purge_robot" );
                    break;
                }
            }
        }
    }

    while ( isdefined( player ) && ( isdefined( player.isspeaking ) && player.isspeaking ) )
        wait 0.1;

    wait 1.0;
    scripts\zm\zmqol_subtitles::zmqol_subs_npc( "vox_maxi_purge_countdown_0", e_vo_origin, undefined, undefined );
    e_vo_origin playsoundwithnotify( "vox_maxi_purge_countdown_0", "vox_maxi_purge_countdown_0_done" );
    e_vo_origin waittill( "vox_maxi_purge_countdown_0_done" );
    wait 1.0;
    level notify( "timeout_warning_vo_complete_" + n_robot_id );
    scripts\zm\zmqol_subtitles::zmqol_subs_npc( "vox_maxi_purge_now_0", e_vo_origin, undefined, undefined );
    e_vo_origin playsoundwithnotify( "vox_maxi_purge_now_0", "vox_maxi_purge_now_0_done" );
    e_vo_origin waittill( "vox_maxi_purge_now_0_done" );
    e_vo_origin delete();
    flag_clear( "timeout_vo_robot_" + n_robot_id );
}

// ----- maps\mp\zm_tomb_ee_main_step_3::ready_to_activate  (stock verbatim + 2 caption line(s)) -----
zmqol_npc_ready_to_activate( unitrigger_stub )
{
    println( "[zm_qol] subtitles: hook ran - ready_to_activate" );

    self endon( "death" );
    scripts\zm\zmqol_subtitles::zmqol_subs_npc( "vox_maxi_robot_sync_0", self, undefined, undefined );
    self playsoundwithnotify( "vox_maxi_robot_sync_0", "sync_done" );
    self waittill( "sync_done" );
    wait 0.5;
    scripts\zm\zmqol_subtitles::zmqol_subs_npc( "vox_maxi_robot_await_0", self, undefined, undefined );
    self playsoundwithnotify( "vox_maxi_robot_await_0", "ready_to_use" );
    self waittill( "ready_to_use" );
    maps\mp\zombies\_zm_unitrigger::register_static_unitrigger( unitrigger_stub, ::zmqol_npc_activate_fire_link );
}

// ----- maps\mp\zm_tomb_ee_main_step_3::activate_fire_link  (stock verbatim + 1 caption line(s)) -----
zmqol_npc_activate_fire_link()
{
    println( "[zm_qol] subtitles: hook ran - activate_fire_link" );

    self endon( "kill_trigger" );

    while ( true )
    {
        self waittill( "trigger", player );
        self playsound( "zmb_squest_robot_button" );

        if ( flag( "three_robot_round" ) )
        {
            level thread zmqol_npc_fire_link_cooldown( self );
            self playsound( "zmb_squest_robot_button_activate" );
            self playloopsound( "zmb_squest_robot_button_timer", 0.5 );
            flag_waitopen( "fire_link_enabled" );
            self stoploopsound( 0.5 );
            self playsound( "zmb_squest_robot_button_deactivate" );
        }
        else
        {
            scripts\zm\zmqol_subtitles::zmqol_subs_npc( "vox_maxi_robot_abort_0", self, undefined, undefined );
            self playsound( "vox_maxi_robot_abort_0" );
            self playsound( "zmb_squest_robot_button_deactivate" );
            wait 3;
        }
    }
}

// ----- maps\mp\zm_tomb_ee_main_step_3::fire_link_cooldown  (stock verbatim + 2 caption line(s)) -----
zmqol_npc_fire_link_cooldown( t_button )
{
    println( "[zm_qol] subtitles: hook ran - fire_link_cooldown" );

    level notify( "fire_link_cooldown" );
    level endon( "fire_link_cooldown" );
    flag_set( "fire_link_enabled" );

    if ( isdefined( t_button ) )
    {
        scripts\zm\zmqol_subtitles::zmqol_subs_npc( "vox_maxi_robot_activated_0", t_button, undefined, undefined );
        t_button playsound( "vox_maxi_robot_activated_0" );
    }

    wait 25;

    if ( isdefined( t_button ) )
    {
        scripts\zm\zmqol_subtitles::zmqol_subs_npc( "vox_maxi_robot_deactivated_0", t_button, undefined, undefined );
        t_button playsound( "vox_maxi_robot_deactivated_0" );
    }

    flag_clear( "fire_link_enabled" );
}

// ----- maps\mp\zm_tomb_ee_main_step_5::quadrotor_pickup_think  (stock verbatim + 1 caption line(s)) -----
zmqol_npc_quadrotor_pickup_think()
{
    println( "[zm_qol] subtitles: hook ran - quadrotor_pickup_think" );

    self endon( "kill_trigger" );
    m_quadrotor = getent( "quadrotor_pickup", "targetname" );

    while ( true )
    {
        self waittill( "trigger", player );
        scripts\zm\zmqol_subtitles::zmqol_subs_npc( "vox_maxi_drone_upgraded_0", player, undefined, undefined );
        player playsound( "vox_maxi_drone_upgraded_0" );
        flag_clear( "ee_quadrotor_disabled" );
        flag_set( "ee_maxis_drone_retrieved" );
        m_quadrotor delete();
    }
}
