// ============================================================================
//      scripts/zm/zm_tomb/qol_subs_lyrics_tomb.gsc
//  SUBTITLES  -  timed lyrics for this map's Easter egg songs     (v2.17.43)
//  GENERATED by modding-jobs\subs-audit-001\build_lyrics.py - do not hand-edit;
//  fix the transcript or the generator and re-run it.
// ----------------------------------------------------------------------------
//  User, 2026-09-26: *"it didn't show the actual lyrics of the song ... make sure
//  it works for all the other easter egg songs in the game"*.
//
//  Each entry is "start|end|text" (tenths of a second from the moment the song
//  starts), plus "|clean text" where the line has a word the clean setting masks.
//  scripts/zm/zmqol_subtitles.gsc zmqol_subs_music() reads this through
//  level.zmqol_subs_lyrics_func, so the root script names nothing map-specific.
//
//  Machine-transcribed from the local song audio with Demucs and Whisper
//  large-v3, then corrected against published song text. Timing comes from
//  word timestamps and has not been checked by ear.
//  Lines per song: mus_zmb_secret_song 40, mus_zmb_secret_song_a7x 36, mus_zmb_secret_song_aether 0.
// ============================================================================

main()
{
}

init()
{
    level.zmqol_subs_lyrics_func = ::zmqol_subs_lyrics;
}

zmqol_subs_lyrics( str_alias )
{
    a = [];

    switch ( str_alias )
    {
        case "mus_zmb_secret_song":
            a[a.size] = "90|150|In disguise in the skies burns a fire in my eyes";
            a[a.size] = "151|179|And I'm holding the world in my hand";
            a[a.size] = "180|226|So contorted and twisted, condemned and submissive";
            a[a.size] = "227|252|When they kneel they'll know where I stand.";
            a[a.size] = "252|341|Yeah, I'm on my own, coming home";
            a[a.size] = "347|390|Painfully and slow";
            a[a.size] = "391|443|I'll bring them down on my own, yeah";
            a[a.size] = "612|679|First to go, first to go, last to know";
            a[a.size] = "680|694|Always the only one I control";
            a[a.size] = "698|774|Lashing out, giving in, then letting go to begin again";
            a[a.size] = "780|799|Letting go";
            a[a.size] = "818|843|Letting go now.";
            a[a.size] = "863|896|Letting go, my mind's corrupt";
            a[a.size] = "897|943|Our souls corrode, it's how we'll all end up.";
            a[a.size] = "943|1024|Burning down, caving in, die by fire and";
            a[a.size] = "1026|1067|Begin again; what breaks my pride will break your skull";
            a[a.size] = "1067|1110|I bring the end just like an archangel";
            a[a.size] = "1227|1269|The wheel won't be turning for long now.";
            a[a.size] = "1325|1348|Coming home";
            a[a.size] = "1364|1392|Letting go, letting go now";
            a[a.size] = "1751|1802|And time is slowed, it's how we'll all end up";
            a[a.size] = "1807|1880|Caving in, die by fire and begin again";
            a[a.size] = "1881|1922|What breaks my pride will break your skull";
            a[a.size] = "1923|1962|I bring the end just like an archangel";
            a[a.size] = "1963|2002|Why do we end up here?";
            a[a.size] = "2004|2032|Live in fire and feel so cold";
            a[a.size] = "2033|2113|We burn together forever, waiting for the one";
            a[a.size] = "2532|2550|Letting go";
            a[a.size] = "2569|2597|Letting go now.";
            a[a.size] = "2615|2673|Letting go, our time is up, dust from our bones";
            a[a.size] = "2674|2696|This time we don't wake up.";
            a[a.size] = "2698|2762|Finding out where you've been, wait in silence";
            a[a.size] = "2762|2776|And begin again";
            a[a.size] = "2777|2821|I'll take my time to make you fall.";
            a[a.size] = "2828|2842|Pass through your head";
            a[a.size] = "2842|2863|At just the right angle";
            a[a.size] = "2867|2885|Falling down.";
            a[a.size] = "2886|2945|Giving in, burn the liars and begin again";
            a[a.size] = "2946|2988|What fills your pride will make you fall.";
            a[a.size] = "2988|3027|I am the end, the fucking archangel|I am the end, the f***ing archangel";
            break;
        case "mus_zmb_secret_song_a7x":
            a[a.size] = "818|854|Let's take a moment and break the ice";
            a[a.size] = "855|897|So my intentions are known";
            a[a.size] = "899|930|See, I have pity in watching you suffer.";
            a[a.size] = "933|973|I know the feeling of being damned alone";
            a[a.size] = "977|1015|I've got a storybook of my own.";
            a[a.size] = "1022|1050|Don't you see I am your pride?";
            a[a.size] = "1051|1088|Agent of wealth, bearer of needs.";
            a[a.size] = "1090|1109|And you know it's right.";
            a[a.size] = "1110|1168|I am your war, arming the strong, aiding the weak";
            a[a.size] = "1186|1219|Know me by name, Shepherd of Fire";
            a[a.size] = "1252|1278|Well, I can promise you paradise.";
            a[a.size] = "1285|1314|No need to serve on your knees.";
            a[a.size] = "1324|1363|And when you're lost in the darkest of hours";
            a[a.size] = "1366|1405|Take a moment and tell me who you see.";
            a[a.size] = "1409|1443|Won't tell you who not to be";
            a[a.size] = "1451|1463|Now you know.";
            a[a.size] = "1464|1482|I am your pride";
            a[a.size] = "1483|1519|Agent of wealth, bearer of needs.";
            a[a.size] = "1524|1540|And you know it's right.";
            a[a.size] = "1541|1600|I am your war, arming the strong, aiding the weak";
            a[a.size] = "1616|1647|Know me by name, Shepherd of Fire";
            a[a.size] = "2194|2228|Disciple of the Cross and champion in suffering";
            a[a.size] = "2229|2266|Immerse yourself into the Kingdom of Redemption.";
            a[a.size] = "2270|2301|Pardon your mind from the chains of the divine";
            a[a.size] = "2302|2328|Make way, the Shepherd of Fire";
            a[a.size] = "2338|2402|Through the ages of time, I've been known for my hate.";
            a[a.size] = "2410|2448|But I'm a dealer of simple choices.";
            a[a.size] = "2448|2472|For me, it's never too late.";
            a[a.size] = "2472|2532|I am your pride, agent of wealth, bearer of needs";
            a[a.size] = "2534|2552|And you know it's right.";
            a[a.size] = "2553|2562|I am your war";
            a[a.size] = "2562|2567|Arming the strong";
            a[a.size] = "2572|2606|Aiding the weak";
            a[a.size] = "2607|2680|I am your wrath, I am your guilt, I am your lust";
            a[a.size] = "2681|2761|I am your law, I am your scar, I am your trust";
            a[a.size] = "2762|2813|Know me by name, Shepherd of Fire";
            break;
    }

    return a;
}
