// ============================================================================
//  zmqol_subs_npc_common.gsc  -  GENERATED by zm_qol - dev\subtitles\gen_subs_npc.py (2026-09-08)
//  SUBTITLES for the NON-player voices: the announcer, Maxis, Samantha, the
//  Richtofen in Stuhlinger's head, Brutus, the bus, the TVs and radios, the
//  ghost, the possessed zombies.
// ----------------------------------------------------------------------------
//  Every function below is the stock body copied VERBATIM out of the gsc-dump
//  (dev-only /# #/ blocks dropped, same-file calls qualified explicitly, as
//  qol_subs_tomb.gsc does) with ONE line added in front of each sound builtin
//  that plays a vox alias:
//      scripts\zm\zmqol_subtitles::zmqol_subs_npc( alias, source, position, listener )
//  The builtin decides who HEARS the line, so the same arguments decide who
//  READS it - see that function's banner. 🛑 Do not hand-edit: change the
//  generator's SPEC and re-run it; the dump is the source of truth.
//
//  Each copy prints "[zm_qol] subtitles: hook ran - <name>" first. STOCK_REFERENCE
//  7a: a hook is not proven until a boot shows that line.
// ============================================================================
#include common_scripts\utility;
#include maps\mp\_utility;
#include maps\mp\zombies\_zm_utility;

main()
{
    replaceFunc( maps\mp\zombies\_zm_audio_announcer::playleaderdialogonplayer, ::zmqol_npc_playleaderdialogonplayer );
}

init()
{
}

// ----- maps\mp\zombies\_zm_audio_announcer::playleaderdialogonplayer  (stock verbatim + 1 caption line(s)) -----
zmqol_npc_playleaderdialogonplayer( dialog, team, waittime )
{
    println( "[zm_qol] subtitles: hook ran - playleaderdialogonplayer" );

    self endon( "disconnect" );

    if ( level.allowzmbannouncer )
    {
        if ( !isdefined( game["zmbdialog"][dialog] ) )
        {
            return;
        }
    }

    self.zmbdialogactive = 1;

    if ( isdefined( self.zmbdialoggroups[dialog] ) )
    {
        group = dialog;
        dialog = self.zmbdialoggroups[group];
        self.zmbdialoggroups[group] = undefined;
        self.zmbdialoggroup = group;
    }

    if ( level.allowzmbannouncer )
    {
        alias = game["zmbdialog"]["prefix"] + "_" + game["zmbdialog"][dialog];
        variant = self maps\mp\zombies\_zm_audio_announcer::getleaderdialogvariant( alias );

        if ( !isdefined( variant ) )
            full_alias = alias;
        else
            full_alias = alias + "_" + variant;

        scripts\zm\zmqol_subtitles::zmqol_subs_npc( full_alias, undefined, undefined, self );
        self playlocalsound( full_alias );
    }

    if ( isdefined( waittime ) )
        wait( waittime );
    else
        wait 4.0;

    self.zmbdialogactive = 0;
    self.zmbdialoggroup = "";

    if ( self.zmbdialogqueue.size > 0 && level.allowzmbannouncer )
    {
        nextdialog = self.zmbdialogqueue[0];

        for ( i = 1; i < self.zmbdialogqueue.size; i++ )
            self.zmbdialogqueue[i - 1] = self.zmbdialogqueue[i];

        self.zmbdialogqueue[i - 1] = undefined;
        self thread zmqol_npc_playleaderdialogonplayer( nextdialog, team );
    }
}
