"""Generate T6 vertex shader HLSL for the Wave Gun swell.

Constant buffer layouts are copied member-for-member (with packoffset) from
the retail char_cloth / effectsimple shader reflection dumps so the RDEF the
engine and OAT see matches retail. Bodies are transcribed from the retail
DXBC disassembly (job wavegun-swell-002/shader). SWELL=1 adds the torso-ball
SwellOffset() push (v2.15.51) after the world transform, the stomach-limited
version of BO1 Moon's "world position += world normal * scriptVector3.x".
"""
import re, os
J2 = r'H:\Plutonium\modding-jobs\wavegun-swell-002\shader'

def parse(path):
    bufs = {}
    cur = None
    for l in open(path):
        m = re.match(r'cbuffer (\w+)', l)
        if m:
            cur = m.group(1); bufs[cur] = []; continue
        m = re.match(r'\s+(float[0-9x]*|bool|int|uint)\s+(\w+)(\[(\d+)\])?\s+@\s+(\d+)\s+size\s+(\d+)', l)
        if m and cur:
            bufs[cur].append((m.group(1), m.group(2), int(m.group(4)) if m.group(4) else 0, int(m.group(5)), int(m.group(6))))
    return bufs

b1 = parse(os.path.join(J2, 'cbuffers-char_cloth.txt'))
pob = [('PerObjectConsts', l) for l in open(os.path.join(J2, 'cbuffer-perobject.txt'))]
b2 = {'PerObjectConsts': []}
for _, l in pob:
    m = re.match(r'\s+(float[0-9x]*|bool|int|uint)\s+(\w+)(\[(\d+)\])?\s+@\s+(\d+)\s+size\s+(\d+)', l)
    if m:
        b2['PerObjectConsts'].append((m.group(1), m.group(2), int(m.group(4)) if m.group(4) else 0, int(m.group(5)), int(m.group(6))))

def decl(members):
    out = []
    for typ, name, arr, off, size in members:
        reg = off // 16
        comp = 'xyzw'[(off % 16) // 4]
        po = f'c{reg}.{comp}' if (off % 16) else f'c{reg}'
        a = f'[{arr}]' if arr else ''
        out.append(f'    {typ} {name}{a} : packoffset({po});')
    return '\n'.join(out)

header = f'''// Generated by gen_hlsl.py - T6 constant buffer layouts copied from retail reflection.
cbuffer PerSceneConsts : register(b0)
{{
{decl(b1['PerSceneConsts'])}
}};

cbuffer PerObjectConsts : register(b1)
{{
{decl(b2['PerObjectConsts'])}
}};

cbuffer dlights : register(b3)
{{
{decl(b1['dlights'])}
}};

float3 DecodeNormal(float3 v)
{{
    // retail: (v >= 0.5) ? v * 2 - 2 : v * 2
    return (v >= 0.5) ? (v * 2.0 - 2.0) : (v * 2.0);
}}

// Wave Gun swell (v2.15.51). Runs on the WORLD position the shader already
// has. Zombies are skinned on the CPU, so IN.pos arrives in eye-relative
// world space and worldMatrix is identity (the fog code measures
// length(wp) as the distance from the eye - that is the proof). So the
// centre must be eye-relative too: scriptVector3.yzw is the J_SpineLower
// tag minus the local player's eye, sent by the client ramp every tick;
// scriptVector3.x is the amount (0 -> 4 over 2.5 s, BO1's values). BO1
// pushed every vertex out along its normal by the same amount, so hands,
// head and legs ballooned as much as the belly. This is a torso ball: an
// ellipsoid 30 units wide and 22 tall around that point, growing over the
// ramp, whose push along the normal falls smoothly to ZERO at its edge.
// Hands, feet, legs and the attached head/eyes are outside it and do not
// move. Zero amount = zero offset, so an actor that never swells renders
// exactly as retail.
float3 SwellOffset(float3 wp, float3 n)
{{
    float amt = scriptVector3.x;
    float f = saturate(amt * 0.25);
    float3 d = wp - scriptVector3.yzw;
    float dm = length(d * float3(1.0 / 30.0, 1.0 / 30.0, 1.0 / 22.0));
    float t = saturate(dm / lerp(0.7, 1.0, f));
    float w = 1.0 - t * t * (3.0 - 2.0 * t);
    return n * (amt * 2.5 * w);
}}
'''
open('hlsl/t6_consts.hlsli', 'w').write(header)

lit = '''#include "t6_consts.hlsli"

struct VS_IN
{
    float4 pos : POSITION0;
    float4 col : COLOR0;
    float2 uv  : TEXCOORD0;
    float3 nrm : NORMAL0;
    float3 tan : TEXCOORD2;
};

struct VS_OUT
{
    float3 fogCol : TEXCOORD0;
    float4 wpos   : TEXCOORD1;
    float4 col    : TEXCOORD2;
    float4 nrm    : TEXCOORD3;
    float4 tan    : TEXCOORD4;
    float2 uv     : TEXCOORD5;
#ifdef SHADOW
    float4 shadow : TEXCOORD6;
#endif
    float4 grid   : TEXCOORD7;
    float3 sh     : TEXCOORD8;
    float4 pos    : SV_Position;
};

VS_OUT main(VS_IN IN)
{
    VS_OUT OUT;

    float4 wp = mul(float4(IN.pos.xyz, 1.0), worldMatrix);

    float3 n = normalize(mul(DecodeNormal(IN.nrm), (float3x3)worldMatrix));
    float3 t = normalize(mul(DecodeNormal(IN.tan), (float3x3)worldMatrix));

#ifdef SWELL
    // BO1 Moon pimp_shader_sw4_3d_char_cloth_bloat pushed each vertex out along
    // its world normal by scriptVector3.x. SwellOffset (t6_consts.hlsli) is
    // that push limited to a ball around the stomach (v2.15.51).
    wp.xyz += SwellOffset(wp.xyz, n);
#endif

    float dist = length(wp.xyz);
    float3 wdir = wp.xyz / dist;

    float4 fc = lerp(fogColor, sunFogColor, saturate(sunFog.y * dot(sunFogDir, wdir) + sunFog.x));
    OUT.fogCol = fc.xyz;

    float tt = fogConsts.w * wp.z + fogConsts.x;
    float a = (tt < 0.0) ? exp(min(tt, 64.0)) : (tt + 1.0);
    a = a - fogConsts2.x;
    float d = wp.z * fogConsts.w;
    bool small = abs(d) < 0.0001;
    d = small ? 1.0 : d;
    float q = a / d;
    q = small ? saturate(fogConsts2.x) : q;
    q = q * fogConsts.y;
    q = q * dist + fogConsts.z;
    float fogAmt = 1.0 - min(exp2(q), 1.0);
    OUT.wpos = float4(wp.xyz, 1.0 - fogAmt * fc.w);

    OUT.col = IN.col;
    OUT.nrm = float4(n, 0.0);
    OUT.tan = float4(t, sign(sign(IN.pos.w)));
    OUT.uv = IN.uv;
#ifdef SHADOW
    OUT.shadow = mul(float4(wp.xyz, 1.0), shadowLookupMatrix);
#endif
    OUT.grid = gridLightingCoordsAndVis;

    float4 qv = float4(n.z * n.x, n.y * n.z, n.x * n.y, n.x * n.x - n.y * n.y);
    float nz2 = n.z * n.z;
    float g = dot(gridLightingSH2, qv) + dot(gridLightingSH1, float4(n, 1.0)) + gridLightingSH0.w * nz2;
    float3 grid = max(g * gridLightingSH0.xyz, 0.1);
    float r = dot(reflectionLightingSH2, qv) + dot(reflectionLightingSH1, float4(n, 1.0)) + reflectionLightingSH0.w * nz2;
    float3 refl = max(r * reflectionLightingSH0.xyz, 0.1);
    OUT.sh = grid / refl;

    OUT.pos = mul(float4(wp.xyz, 1.0), viewProjectionMatrix);
    return OUT;
}
'''
open('hlsl/char_cloth_vs.hlsl', 'w').write(lit)

depth = '''#include "t6_consts.hlsli"

struct VS_IN
{
    float3 pos : POSITION0;
#ifdef SWELL
    float3 nrm : NORMAL0;
#endif
};

float4 main(VS_IN IN) : SV_Position
{
    float4 wp = mul(float4(IN.pos, 1.0), worldMatrix);
#ifdef SWELL
    // torso-ball swell in eye-relative world space, see SwellOffset (v2.15.51)
    float3 n = normalize(mul(DecodeNormal(IN.nrm), (float3x3)worldMatrix));
    wp.xyz += SwellOffset(wp.xyz, n);
#endif
    return mul(float4(wp.xyz, 1.0), viewProjectionMatrix);
}
'''
open('hlsl/transformonly_vs.hlsl', 'w').write(depth)
print('wrote hlsl/*')
