"""Generate T6 vertex shader HLSL for the Wave Gun swell.

Constant buffer layouts are copied member-for-member (with packoffset) from
the retail char_cloth / effectsimple shader reflection dumps so the RDEF the
engine and OAT see matches retail. Bodies are transcribed from the retail
DXBC disassembly (job wavegun-swell-002/shader). SWELL=1 adds BO1 Moon's
"world position += world normal * scriptVector3.x" after the world transform.
"""
import re, os
J2 = r'H:\Plutonium\modding-jobs\wavegun-swell-002\shader'

def parse(path):
    bufs = {}
    cur = None
    for l in open(path):
        m = re.match(r'cbuffer (\w+)', l)
        if m:
            cur = m.group(1); bufs[cur] = []; continue
        m = re.match(r'\s+(float[0-9x]*|bool|int|uint)\s+(\w+)(\[(\d+)\])?\s+@\s+(\d+)\s+size\s+(\d+)', l)
        if m and cur:
            bufs[cur].append((m.group(1), m.group(2), int(m.group(4)) if m.group(4) else 0, int(m.group(5)), int(m.group(6))))
    return bufs

b1 = parse(os.path.join(J2, 'cbuffers-char_cloth.txt'))
pob = [('PerObjectConsts', l) for l in open(os.path.join(J2, 'cbuffer-perobject.txt'))]
b2 = {'PerObjectConsts': []}
for _, l in pob:
    m = re.match(r'\s+(float[0-9x]*|bool|int|uint)\s+(\w+)(\[(\d+)\])?\s+@\s+(\d+)\s+size\s+(\d+)', l)
    if m:
        b2['PerObjectConsts'].append((m.group(1), m.group(2), int(m.group(4)) if m.group(4) else 0, int(m.group(5)), int(m.group(6))))

def decl(members):
    out = []
    for typ, name, arr, off, size in members:
        reg = off // 16
        comp = 'xyzw'[(off % 16) // 4]
        po = f'c{reg}.{comp}' if (off % 16) else f'c{reg}'
        a = f'[{arr}]' if arr else ''
        out.append(f'    {typ} {name}{a} : packoffset({po});')
    return '\n'.join(out)

header = f'''// Generated by gen_hlsl.py - T6 constant buffer layouts copied from retail reflection.
cbuffer PerSceneConsts : register(b0)
{{
{decl(b1['PerSceneConsts'])}
}};

cbuffer PerObjectConsts : register(b1)
{{
{decl(b2['PerObjectConsts'])}
}};

cbuffer dlights : register(b3)
{{
{decl(b1['dlights'])}
}};

float3 DecodeNormal(float3 v)
{{
    // retail: (v >= 0.5) ? v * 2 - 2 : v * 2
    return (v >= 0.5) ? (v * 2.0 - 2.0) : (v * 2.0);
}}

// Wave Gun swell (v2.17.46) - BO1 Moon's bloat, one line, nothing else.
// pimp_shader_sw4_3d_char_cloth_bloat pushed each vertex out along its world
// normal by scriptVector3.x; the client ramps it 0 -> 4 over 2.5 s. This is the
// same instruction stream as the working Der Riese build 11 (disassembled,
// modding-jobs\wavegun-build11-001\disasm) and as our own v2.15.49.
//
// v2.15.51-v2.17.45 limited the push to a ball around the stomach because the
// uniform push tore the mesh at every hard edge. The tear was in the MESH, not
// the formula: a stock zombie splits the normal at each seam. The Wave Gun now
// swaps the corpse to a copy whose normals are welded (zqwg_*, zapgun.gsc
// zmqol_mgun_swell_swap), so Moon's push inflates it as one skin - the
// Der Riese build's route. Zero amount = zero offset, so every zombie that is
// not being microwaved renders exactly as retail.
float3 SwellOffset(float3 wp, float3 n)
{{
    return n * scriptVector3.x;
}}
'''
open('hlsl/t6_consts.hlsli', 'w').write(header)

lit = '''#include "t6_consts.hlsli"

struct VS_IN
{
    float4 pos : POSITION0;
    float4 col : COLOR0;
    float2 uv  : TEXCOORD0;
    float3 nrm : NORMAL0;
    float3 tan : TEXCOORD2;
};

struct VS_OUT
{
    float3 fogCol : TEXCOORD0;
    float4 wpos   : TEXCOORD1;
    float4 col    : TEXCOORD2;
    float4 nrm    : TEXCOORD3;
    float4 tan    : TEXCOORD4;
    float2 uv     : TEXCOORD5;
#ifdef SHADOW
    float4 shadow : TEXCOORD6;
#endif
    float4 grid   : TEXCOORD7;
    float3 sh     : TEXCOORD8;
    float4 pos    : SV_Position;
};

VS_OUT main(VS_IN IN)
{
    VS_OUT OUT;

    float4 wp = mul(float4(IN.pos.xyz, 1.0), worldMatrix);

    float3 n = normalize(mul(DecodeNormal(IN.nrm), (float3x3)worldMatrix));
    float3 t = normalize(mul(DecodeNormal(IN.tan), (float3x3)worldMatrix));

#ifdef SWELL
    // BO1 Moon pimp_shader_sw4_3d_char_cloth_bloat: push each vertex out along
    // its world normal by scriptVector3.x (SwellOffset, t6_consts.hlsli).
    wp.xyz += SwellOffset(wp.xyz, n);
#endif

    float dist = length(wp.xyz);
    float3 wdir = wp.xyz / dist;

    float4 fc = lerp(fogColor, sunFogColor, saturate(sunFog.y * dot(sunFogDir, wdir) + sunFog.x));
    OUT.fogCol = fc.xyz;

    float tt = fogConsts.w * wp.z + fogConsts.x;
    float a = (tt < 0.0) ? exp(min(tt, 64.0)) : (tt + 1.0);
    a = a - fogConsts2.x;
    float d = wp.z * fogConsts.w;
    bool small = abs(d) < 0.0001;
    d = small ? 1.0 : d;
    float q = a / d;
    q = small ? saturate(fogConsts2.x) : q;
    q = q * fogConsts.y;
    q = q * dist + fogConsts.z;
    float fogAmt = 1.0 - min(exp2(q), 1.0);
    OUT.wpos = float4(wp.xyz, 1.0 - fogAmt * fc.w);

    OUT.col = IN.col;
    OUT.nrm = float4(n, 0.0);
    OUT.tan = float4(t, sign(sign(IN.pos.w)));
    OUT.uv = IN.uv;
#ifdef SHADOW
    OUT.shadow = mul(float4(wp.xyz, 1.0), shadowLookupMatrix);
#endif
    OUT.grid = gridLightingCoordsAndVis;

    float4 qv = float4(n.z * n.x, n.y * n.z, n.x * n.y, n.x * n.x - n.y * n.y);
    float nz2 = n.z * n.z;
    float g = dot(gridLightingSH2, qv) + dot(gridLightingSH1, float4(n, 1.0)) + gridLightingSH0.w * nz2;
    float3 grid = max(g * gridLightingSH0.xyz, 0.1);
    float r = dot(reflectionLightingSH2, qv) + dot(reflectionLightingSH1, float4(n, 1.0)) + reflectionLightingSH0.w * nz2;
    float3 refl = max(r * reflectionLightingSH0.xyz, 0.1);
    OUT.sh = grid / refl;

    OUT.pos = mul(float4(wp.xyz, 1.0), viewProjectionMatrix);
    return OUT;
}
'''
open('hlsl/char_cloth_vs.hlsl', 'w').write(lit)

depth = '''#include "t6_consts.hlsli"

struct VS_IN
{
    float3 pos : POSITION0;
#ifdef SWELL
    float3 nrm : NORMAL0;
#endif
};

float4 main(VS_IN IN) : SV_Position
{
    float4 wp = mul(float4(IN.pos, 1.0), worldMatrix);
#ifdef SWELL
    // BO1 Moon's bloat, see SwellOffset (t6_consts.hlsli)
    float3 n = normalize(mul(DecodeNormal(IN.nrm), (float3x3)worldMatrix));
    wp.xyz += SwellOffset(wp.xyz, n);
#endif
    return mul(float4(wp.xyz, 1.0), viewProjectionMatrix);
}
'''
open('hlsl/transformonly_vs.hlsl', 'w').write(depth)
print('wrote hlsl/*')
