// ============================================================================
//  qol_subs_npc_nuked.gsc  -  GENERATED by zm_qol - dev\subtitles\gen_subs_npc.py (2026-09-08)
//  SUBTITLES for the NON-player voices: the announcer, Maxis, Samantha, the
//  Richtofen in Stuhlinger's head, Brutus, the bus, the TVs and radios, the
//  ghost, the possessed zombies.
// ----------------------------------------------------------------------------
//  Every function below is the stock body copied VERBATIM out of the gsc-dump
//  (dev-only /# #/ blocks dropped, same-file calls qualified explicitly, as
//  qol_subs_tomb.gsc does) with ONE line added in front of each sound builtin
//  that plays a vox alias:
//      scripts\zm\zmqol_subtitles::zmqol_subs_npc( alias, source, position, listener )
//  The builtin decides who HEARS the line, so the same arguments decide who
//  READS it - see that function's banner. 🛑 Do not hand-edit: change the
//  generator's SPEC and re-run it; the dump is the source of truth.
//
//  Each copy prints "[zm_qol] subtitles: hook ran - <name>" first. STOCK_REFERENCE
//  7a: a hook is not proven until a boot shows that line.
// ============================================================================
#include common_scripts\utility;
#include maps\mp\_utility;
#include maps\mp\zombies\_zm_utility;

main()
{
    replaceFunc( maps\mp\zm_nuked::moon_transmission_vo, ::zmqol_npc_moon_transmission_vo );
}

init()
{
}

// ----- maps\mp\zm_nuked::moon_transmission_vo  (stock verbatim + 5 caption line(s)) -----
zmqol_npc_moon_transmission_vo()
{
    //  v2.15.44 - survival maps cannot run the full easter egg, so quest voices stay silent there.
    //  Classic keeps the stock behavior below. (Generator SPEC marks this entry "survival_silent".)
    if ( !is_classic() )
        return;

    println( "[zm_qol] subtitles: hook ran - moon_transmission_vo" );

    start_round = 3;
    end_round = 25;
    moon_transmission_struct = getstruct( "moon_transmission_struct", "targetname" );
    maps\mp\zm_nuked::wait_for_round_range( 3 );
    scripts\zm\zmqol_subtitles::zmqol_subs_npc( "vox_nuked_tbase_transmission_0", undefined, moon_transmission_struct.origin, undefined );
    playsoundatposition( "vox_nuked_tbase_transmission_0", moon_transmission_struct.origin );
    maps\mp\zm_nuked::wait_for_round_range( randomintrange( 4, 9 ) );
    scripts\zm\zmqol_subtitles::zmqol_subs_npc( "vox_nuked_tbase_transmission_1", undefined, moon_transmission_struct.origin, undefined );
    playsoundatposition( "vox_nuked_tbase_transmission_1", moon_transmission_struct.origin );
    maps\mp\zm_nuked::wait_for_round_range( randomintrange( 10, 17 ) );
    scripts\zm\zmqol_subtitles::zmqol_subs_npc( "vox_nuked_tbase_transmission_2", undefined, moon_transmission_struct.origin, undefined );
    playsoundatposition( "vox_nuked_tbase_transmission_2", moon_transmission_struct.origin );
    maps\mp\zm_nuked::wait_for_round_range( randomintrange( 18, 22 ) );
    scripts\zm\zmqol_subtitles::zmqol_subs_npc( "vox_nuked_tbase_transmission_3", undefined, moon_transmission_struct.origin, undefined );
    playsoundatposition( "vox_nuked_tbase_transmission_3", moon_transmission_struct.origin );
    maps\mp\zm_nuked::wait_for_round_range( 25 );
    scripts\zm\zmqol_subtitles::zmqol_subs_npc( "vox_nuked_tbase_transmission_4", undefined, moon_transmission_struct.origin, undefined );
    playsoundatposition( "vox_nuked_tbase_transmission_4", moon_transmission_struct.origin );
    flag_set( "moon_transmission_over" );
}
