// ============================================================================
//      scripts/zm/zm_transit/qol_subs_lyrics_transit.gsc
//  SUBTITLES  -  timed lyrics for this map's Easter egg songs     (v2.17.43)
//  GENERATED by modding-jobs\subs-audit-001\build_lyrics.py - do not hand-edit;
//  fix the transcript or the generator and re-run it.
// ----------------------------------------------------------------------------
//  User, 2026-09-26: *"it didn't show the actual lyrics of the song ... make sure
//  it works for all the other easter egg songs in the game"*.
//
//  Each entry is "start|end|text" (tenths of a second from the moment the song
//  starts), plus "|clean text" where the line has a word the clean setting masks.
//  scripts/zm/zmqol_subtitles.gsc zmqol_subs_music() reads this through
//  level.zmqol_subs_lyrics_func, so the root script names nothing map-specific.
//
//  Machine-transcribed from the local song audio with Demucs and Whisper
//  large-v3, then corrected against published song text. Timing comes from
//  word timestamps and has not been checked by ear.
//  Lines per song: mus_zmb_secret_song 50.
// ============================================================================

main()
{
}

init()
{
    level.zmqol_subs_lyrics_func = ::zmqol_subs_lyrics;
}

zmqol_subs_lyrics( str_alias )
{
    a = [];

    switch ( str_alias )
    {
        case "mus_zmb_secret_song":
            a[a.size] = "34|73|Like a dream when I'm falling and calling out";
            a[a.size] = "73|103|My resistance is silent";
            a[a.size] = "105|143|I can feel but I still can't control myself.";
            a[a.size] = "143|188|Please forgive me now.";
            a[a.size] = "213|225|Now.";
            a[a.size] = "260|295|Shadow, nothing, all I am.";
            a[a.size] = "296|328|Stalking, killing, all I can.";
            a[a.size] = "328|371|I was spawned from eternal night by infernal rite";
            a[a.size] = "371|398|And I need your carrion.";
            a[a.size] = "400|425|Neurons fire when I violate";
            a[a.size] = "425|442|Pupils dilate";
            a[a.size] = "442|471|And I feel your carrion.";
            a[a.size] = "474|515|I could scream but I know I won't hear myself.";
            a[a.size] = "515|544|I'm a slave to synapses";
            a[a.size] = "544|585|In my dream is the sound of a lullaby.";
            a[a.size] = "586|631|Calling me the one.";
            a[a.size] = "645|671|I'm undone.";
            a[a.size] = "681|751|And the law runs from the chosen one.";
            a[a.size] = "751|808|Vermin martyr, just as planned";
            a[a.size] = "808|842|Asking why must I be damned";
            a[a.size] = "842|884|I was spawned from eternal night by infernal rite";
            a[a.size] = "884|911|And I need your carrion.";
            a[a.size] = "913|937|Neurons fire when I violate";
            a[a.size] = "938|954|Pupils dilate";
            a[a.size] = "955|982|And I feel your carrion.";
            a[a.size] = "983|1009|I bring doom and defile light";
            a[a.size] = "1010|1055|Your entire life will now cease to carry on.";
            a[a.size] = "1056|1082|I've returned and I'm not alone.";
            a[a.size] = "1082|1100|Never to atone.";
            a[a.size] = "1100|1114|And forever carry";
            a[a.size] = "1121|1187|On and on until everyone is gone";
            a[a.size] = "1190|1206|Hear them begging.";
            a[a.size] = "1207|1225|And they're pleading.";
            a[a.size] = "1226|1243|And they're crying.";
            a[a.size] = "1244|1259|See them bleeding.";
            a[a.size] = "1260|1295|And they run and run.";
            a[a.size] = "1297|1329|Till they cannot carry on.";
            a[a.size] = "1329|1367|Carry on. Carry on.";
            a[a.size] = "1367|1385|Carry on.";
            a[a.size] = "1749|1773|Carrion";
            a[a.size] = "1883|1988|Carrion, and I need your carrion";
            a[a.size] = "1988|2029|Carrion, and I feel your carrion";
            a[a.size] = "2044|2141|Carrion, and I need your carrion";
            a[a.size] = "2142|2205|Carrion, I was spawned from eternal night";
            a[a.size] = "2206|2263|By infernal rite, and I need your carrion";
            a[a.size] = "2263|2279|Neurons fire when I violate";
            a[a.size] = "2296|2316|And I feel your carrion";
            a[a.size] = "2323|2375|I bring doom and defile light; your entire life";
            a[a.size] = "2376|2431|Will now cease to carry on; I've returned, not alone";
            a[a.size] = "2432|2464|Never to atone, and forever carry";
            break;
    }

    return a;
}
