// ============================================================================
//  qol_subs_npc_transit.gsc  -  GENERATED by zm_qol - dev\subtitles\gen_subs_npc.py (2026-09-08)
//  SUBTITLES for the NON-player voices: the announcer, Maxis, Samantha, the
//  Richtofen in Stuhlinger's head, Brutus, the bus, the TVs and radios, the
//  ghost, the possessed zombies.
// ----------------------------------------------------------------------------
//  Every function below is the stock body copied VERBATIM out of the gsc-dump
//  (dev-only /# #/ blocks dropped, same-file calls qualified explicitly, as
//  qol_subs_tomb.gsc does) with ONE line added in front of each sound builtin
//  that plays a vox alias:
//      scripts\zm\zmqol_subtitles::zmqol_subs_npc( alias, source, position, listener )
//  The builtin decides who HEARS the line, so the same arguments decide who
//  READS it - see that function's banner. 🛑 Do not hand-edit: change the
//  generator's SPEC and re-run it; the dump is the source of truth.
//
//  Each copy prints "[zm_qol] subtitles: hook ran - <name>" first. STOCK_REFERENCE
//  7a: a hook is not proven until a boot shows that line.
// ============================================================================
#include common_scripts\utility;
#include maps\mp\_utility;
#include maps\mp\zombies\_zm_utility;

main()
{
    replaceFunc( maps\mp\zm_transit_sq::maxissay, ::zmqol_npc_maxissay );
    replaceFunc( maps\mp\zm_transit_sq::richtofensay, ::zmqol_npc_richtofensay );
    replaceFunc( maps\mp\zm_transit_sq::wait_for_richtoffen_intro, ::zmqol_npc_wait_for_richtoffen_intro );
    replaceFunc( maps\mp\zm_transit_sq::survivor_vox, ::zmqol_npc_survivor_vox );
    replaceFunc( maps\mp\zm_transit_power::bus_station_pa_vox, ::zmqol_npc_bus_station_pa_vox );
    replaceFunc( maps\mp\zm_transit::powerup_intro_vox, ::zmqol_npc_powerup_intro_vox );
    replaceFunc( maps\mp\zm_transit_classic::zm_traversal_override, ::zmqol_npc_zm_traversal_override );
}

init()
{
    thread zmqol_npc_repoint();
}

//  STOCK_REFERENCE 7a mode 2/3: these stock functions are also reached through
//  a level.* pointer captured at map init, so the pointer is re-pointed at the
//  copy once the players are in, in case the replaceFunc alone does not take.
zmqol_npc_repoint()
{
    flag_wait( "initial_players_connected" );

    if ( isdefined( level.zm_traversal_override ) )
        level.zm_traversal_override = ::zmqol_npc_zm_traversal_override;

    println( "[zm_qol] subtitles: NPC pointer re-points done" );
}

// ----- maps\mp\zm_transit_sq::maxissay  (stock verbatim + 2 caption line(s)) -----
zmqol_npc_maxissay( line, org, playonent, playonenttag, ignore_power_state )
{
    println( "[zm_qol] subtitles: hook ran - maxissay" );

    level endon( "end_game" );
    level endon( "intermission" );

    if ( isdefined( level.intermission ) && level.intermission )
        return;

    if ( isdefined( level.maxcompleted ) && level.maxcompleted )
        return;

    if ( ( flag( "power_on" ) || flag( "switches_on" ) ) && !( isdefined( ignore_power_state ) && ignore_power_state ) )
        return;

    while ( isdefined( level.maxis_talking ) && level.maxis_talking )
        wait 0.05;

    level.maxis_talking = 1;

    if ( isdefined( playonent ) )
    {
        scripts\zm\zmqol_subtitles::zmqol_subs_npc( line, playonent, undefined, undefined );
        playonent playsoundontag( line, playonenttag );
    }
    else
    {
        scripts\zm\zmqol_subtitles::zmqol_subs_npc( line, undefined, org, undefined );
        playsoundatposition( line, org );
    }

    wait 10;
    level.maxis_talking = 0;
}

// ----- maps\mp\zm_transit_sq::richtofensay  (stock verbatim + 1 caption line(s)) -----
zmqol_npc_richtofensay( vox_line, intro, ignore_power_state, time )
{
    println( "[zm_qol] subtitles: hook ran - richtofensay" );

    level endon( "end_game" );
    level endon( "intermission" );

    if ( isdefined( level.intermission ) && level.intermission )
        return;

    if ( isdefined( level.richcompleted ) && level.richcompleted )
        return;

    level endon( "richtofen_c_complete" );

    if ( !isdefined( time ) )
        time = 45;

    while ( isdefined( level.richtofen_talking_to_samuel ) && level.richtofen_talking_to_samuel || !( isdefined( level.richtofen_sq_intro_said ) && level.richtofen_sq_intro_said ) )
        wait 1;

    if ( isdefined( level.rich_sq_player ) && is_player_valid( level.rich_sq_player ) )
    {

        if ( ( !flag( "power_on" ) || !flag( "switches_on" ) ) && !( isdefined( ignore_power_state ) && ignore_power_state ) )
            return;

        scripts\zm\zmqol_subtitles::zmqol_subs_npc( vox_line, undefined, undefined, level.rich_sq_player );
        level.rich_sq_player playsoundtoplayer( vox_line, level.rich_sq_player );

        if ( !( isdefined( level.richtofen_talking_to_samuel ) && level.richtofen_talking_to_samuel ) )
            level thread maps\mp\zm_transit_sq::richtofen_talking( time );
    }
}

// ----- maps\mp\zm_transit_sq::wait_for_richtoffen_intro  (stock verbatim + 1 caption line(s)) -----
zmqol_npc_wait_for_richtoffen_intro()
{
    println( "[zm_qol] subtitles: hook ran - wait_for_richtoffen_intro" );

    level endon( "intermission" );
    power_occupied = 1;

    while ( power_occupied )
    {
        inzone = 0;

        foreach ( zone in level.power_station_zones )
        {
            if ( isdefined( maps\mp\zombies\_zm_zonemgr::player_in_zone( zone ) ) && maps\mp\zombies\_zm_zonemgr::player_in_zone( zone ) )
                inzone = 1;
        }

        if ( !inzone )
            power_occupied = 0;

        wait 0.1;
    }

    wait 5;

    if ( !isdefined( level.rich_sq_player ) || ( !flag( "power_on" ) || !flag( "switches_on" ) ) )
        return;

    if ( isdefined( level.intermission ) && level.intermission )
        return;

    scripts\zm\zmqol_subtitles::zmqol_subs_npc( "vox_zmba_sidequest_power_on_0", undefined, undefined, level.rich_sq_player );
    level.rich_sq_player playsoundtoplayer( "vox_zmba_sidequest_power_on_0", level.rich_sq_player );
    maps\mp\zm_transit_sq::richtofen_talking( 45 );
    level.richtofen_sq_intro_said = 1;
}

// ----- maps\mp\zm_transit_sq::survivor_vox  (stock verbatim + 2 caption line(s)) -----
zmqol_npc_survivor_vox()
{
    println( "[zm_qol] subtitles: hook ran - survivor_vox" );

    initiated = 0;

    while ( !initiated )
    {
        players = get_players();

        foreach ( player in players )
        {
            if ( distance2dsquared( player.origin, ( 8000, -6656, 160 ) ) < 1225 )
            {
                if ( player usebuttonpressed() )
                {
                    playsoundatposition( "zmb_zombie_arc", ( 8000, -6656, 160 ) );
                    start_time = gettime();
                    end_time = start_time + 5000;

                    while ( player usebuttonpressed() && distance2dsquared( player.origin, ( 8000, -6656, 160 ) ) < 1225 && is_player_valid( player ) )
                    {
                        if ( gettime() > end_time )
                            initiated = 1;

                        wait 0.05;
                    }

                    playsoundatposition( "zmb_buildable_piece_add", ( 8000, -6656, 160 ) );
                }
            }
        }

        wait 1;
    }

    playsoundatposition( "zmb_weap_wall", ( 8000, -6656, 160 ) );
    i = -1;

    while ( true )
    {
        players = get_players();

        foreach ( player in players )
        {
            if ( distance2dsquared( player.origin, ( 8000, -6656, 160 ) ) < 1225 )
            {
                if ( player usebuttonpressed() && is_player_valid( player ) )
                {
                    if ( flag( "power_on" ) )
                    {
                        if ( i == -1 || i > 4 )
                        {
                            scripts\zm\zmqol_subtitles::zmqol_subs_npc( "vox_maxi_tv_distress_0", undefined, ( 8000, -6656, 160 ), undefined );
                            playsoundatposition( "vox_maxi_tv_distress_0", ( 8000, -6656, 160 ) );
                        }
                        else if ( i < 4 )
                        {
                            scripts\zm\zmqol_subtitles::zmqol_subs_npc( level.survivor_vox[i], undefined, ( 8000, -6656, 160 ), undefined );
                            playsoundatposition( level.survivor_vox[i], ( 8000, -6656, 160 ) );
                        }

                        i++;
                    }

                    wait 60;
                }
            }
        }

        wait 1;
    }
}

// ----- maps\mp\zm_transit_power::bus_station_pa_vox  (stock verbatim + 1 caption line(s)) -----
zmqol_npc_bus_station_pa_vox()
{
    println( "[zm_qol] subtitles: hook ran - bus_station_pa_vox" );

    level endon( "power_off" );

    while ( true )
    {
        level.station_pa_vox = array_randomize( level.station_pa_vox );

        foreach ( line in level.station_pa_vox )
        {
            scripts\zm\zmqol_subtitles::zmqol_subs_npc( line, undefined, ( -6848, 5056, 56 ), undefined );
            playsoundatposition( line, ( -6848, 5056, 56 ) );
            wait( randomintrange( 12, 15 ) );
        }

        wait 1;
    }
}

// ----- maps\mp\zm_transit::powerup_intro_vox  (stock verbatim + 1 caption line(s)) -----
zmqol_npc_powerup_intro_vox( powerup )
{
    println( "[zm_qol] subtitles: hook ran - powerup_intro_vox" );

    say_intro = 0;
    players = get_players();

    foreach ( player in players )
    {
        if ( player maps\mp\zombies\_zm_stats::get_global_stat( "POWERUP_INTRO_PLAYED" ) == 1 )
            continue;
        else
        {
            player maps\mp\zombies\_zm_stats::set_global_stat( "powerup_intro_played", 1 );
            say_intro = 1;
        }
    }

    level.powerup_intro_vox = undefined;
    powerup_name = powerup.powerup_name;
    powerup thread maps\mp\zombies\_zm_powerups::powerup_delete();
    powerup notify( "powerup_grabbed" );

    if ( !say_intro )
    {
        level thread maps\mp\zombies\_zm_audio_announcer::leaderdialog( powerup_name );
        level.powerup_vo_available = undefined;
        return;
    }

    flag_clear( "zombie_drop_powerups" );
    level.powerup_intro = 1;
    org = spawn( "script_origin", get_players()[0].origin );
    scripts\zm\zmqol_subtitles::zmqol_subs_npc( "vox_zmba_first_drop_0", org, undefined, undefined );
    org playsoundwithnotify( "vox_zmba_first_drop_0", "first_powerup_intro_done" );
    org waittill( "first_powerup_intro_done" );
    level thread maps\mp\zombies\_zm_audio_announcer::leaderdialog( powerup_name );
    org delete();
    flag_set( "zombie_drop_powerups" );
    level.powerup_intro = 0;
    level.powerup_vo_available = undefined;
}

// ----- maps\mp\zm_transit_classic::zm_traversal_override  (stock verbatim + 1 caption line(s)) -----
zmqol_npc_zm_traversal_override( traversealias )
{
    println( "[zm_qol] subtitles: hook ran - zm_traversal_override" );

    suffix = "";
    sndalias = undefined;
    chance = 0;
    sndchance = 0;

    if ( !( isdefined( self.isscreecher ) && self.isscreecher ) && !( isdefined( self.is_avogadro ) && self.is_avogadro ) )
    {
        if ( isdefined( self.traversestartnode ) && isdefined( self.traversestartnode.script_string ) && self.traversestartnode.script_string == "ignore_traverse_override" )
            return traversealias;

        switch ( traversealias )
        {
            case "jump_down_48":
                if ( isdefined( self.has_legs ) && self.has_legs )
                {
                    suffix = "_stumble";
                    chance = 0;
                }

                break;
            case "jump_down_127":
            case "jump_down_190":
            case "jump_down_222":
            case "jump_down_90":
                if ( isdefined( self.has_legs ) && self.has_legs )
                {
                    suffix = "_stumble";
                    chance = 30;
                }

                break;
            case "jump_up_127":
            case "jump_up_190":
            case "jump_up_222":
            case "jump_up_48":
                sndalias = "vox_zmba_zombie_pickup_" + randomint( 2 );
                suffix = "_grabbed";
                chance = 6;
                sndchance = 3;
                break;
        }

        if ( chance != 0 && randomint( 100 ) <= chance )
        {
            if ( isdefined( sndalias ) && randomint( 100 ) <= sndchance )
            {
                scripts\zm\zmqol_subtitles::zmqol_subs_npc( sndalias, undefined, self.origin, undefined );
                playsoundatposition( sndalias, self.origin );
            }

            traversealias = traversealias + suffix;
        }
    }

    return traversealias;
}
