// ============================================================================
//      scripts/zm/zm_buried/qol_subs_lyrics_buried.gsc
//  SUBTITLES  -  timed lyrics for this map's Easter egg songs     (v2.17.43)
//  GENERATED by modding-jobs\subs-audit-001\build_lyrics.py - do not hand-edit;
//  fix the transcript or the generator and re-run it.
// ----------------------------------------------------------------------------
//  User, 2026-09-26: *"it didn't show the actual lyrics of the song ... make sure
//  it works for all the other easter egg songs in the game"*.
//
//  Each entry is "start|end|text" (tenths of a second from the moment the song
//  starts), plus "|clean text" where the line has a word the clean setting masks.
//  scripts/zm/zmqol_subtitles.gsc zmqol_subs_music() reads this through
//  level.zmqol_subs_lyrics_func, so the root script names nothing map-specific.
//
//  Machine-transcribed from the local song audio with Demucs and Whisper
//  large-v3, then corrected against published song text. Timing comes from
//  word timestamps and has not been checked by ear.
//  Lines per song: mus_richtofens_delight 0, mus_samanthas_desire 0, mus_zmb_secret_song 68.
// ============================================================================

main()
{
}

init()
{
    level.zmqol_subs_lyrics_func = ::zmqol_subs_lyrics;
}

zmqol_subs_lyrics( str_alias )
{
    a = [];

    switch ( str_alias )
    {
        case "mus_zmb_secret_song":
            a[a.size] = "151|257|In this solemn field of silence, I can barely feel the";
            a[a.size] = "258|272|Pain.";
            a[a.size] = "309|360|Blind and deaf to all the violence";
            a[a.size] = "360|427|And I've always felt this way.";
            a[a.size] = "449|467|La";
            a[a.size] = "484|518|La, la";
            a[a.size] = "528|546|La";
            a[a.size] = "554|559|La";
            a[a.size] = "565|595|La, la, la, la";
            a[a.size] = "595|604|La, la, la";
            a[a.size] = "615|667|On the wind a smell of misery.";
            a[a.size] = "675|737|Fear and death perfume the air.";
            a[a.size] = "770|821|It begins again in mystery.";
            a[a.size] = "829|892|And I always end up there";
            a[a.size] = "908|954|Always unsuspecting";
            a[a.size] = "954|1017|So easy to lure them away from.";
            a[a.size] = "1025|1066|All the angels within.";
            a[a.size] = "1071|1092|I am burning.";
            a[a.size] = "1092|1125|From something I'm becoming";
            a[a.size] = "1137|1175|Unstoppable";
            a[a.size] = "1178|1208|And I'm coming from the something I'm running from";
            a[a.size] = "1209|1245|Becoming one, always running";
            a[a.size] = "1248|1286|Like something might be coming.";
            a[a.size] = "1288|1329|To follow me";
            a[a.size] = "1329|1363|And I'm running from the something I'm coming from";
            a[a.size] = "1364|1398|Becoming one, I am";
            a[a.size] = "1400|1432|Letting go of all I know.";
            a[a.size] = "1432|1480|From this buried well of consciousness.";
            a[a.size] = "1486|1549|I can barely hear the rain.";
            a[a.size] = "1588|1634|Everyone becomes anonymous.";
            a[a.size] = "1649|1707|All their faces seem the same.";
            a[a.size] = "1721|1771|Always unrelenting";
            a[a.size] = "1772|1828|Descending into our own nightmare.";
            a[a.size] = "1841|1874|From this twisted fantasy.";
            a[a.size] = "1879|1923|Falling far away from.";
            a[a.size] = "1923|1983|The beauty of annihilation.";
            a[a.size] = "2039|2057|I am running.";
            a[a.size] = "2058|2094|From something I'm becoming";
            a[a.size] = "2099|2140|Unstoppable";
            a[a.size] = "2141|2176|And I'm coming from the something I'm running from";
            a[a.size] = "2177|2212|Becoming one, always running";
            a[a.size] = "2216|2247|Like something might be coming.";
            a[a.size] = "2247|2297|To follow me";
            a[a.size] = "2298|2332|And I'm running from the something I'm coming from";
            a[a.size] = "2332|2365|Becoming one, I've become";
            a[a.size] = "2371|2404|Something they all run from.";
            a[a.size] = "2409|2445|I want you to be gone.";
            a[a.size] = "2446|2479|But I know you've just begun.";
            a[a.size] = "2488|2527|Why am I numb";
            a[a.size] = "2528|2558|To everything I have done.";
            a[a.size] = "2567|2596|There's no going back for me.";
            a[a.size] = "2609|2672|Becoming has taken its toll on me.";
            a[a.size] = "2677|2697|I am running.";
            a[a.size] = "2698|2731|From something I'm becoming";
            a[a.size] = "2739|2780|Unstoppable";
            a[a.size] = "2781|2818|And I'm coming from the something I'm running from";
            a[a.size] = "2853|2892|Like something might be coming.";
            a[a.size] = "2893|2934|To follow me";
            a[a.size] = "2935|2970|And I'm running from the something I'm coming from";
            a[a.size] = "2971|3007|Becoming one, always running";
            a[a.size] = "3015|3041|Something I'm becoming.";
            a[a.size] = "3048|3089|Unstoppable";
            a[a.size] = "3089|3113|And I'm running from the something I'm coming from";
            a[a.size] = "3113|3159|Becoming one, always running";
            a[a.size] = "3163|3229|Like something might be coming So follow me and I'm";
            a[a.size] = "3230|3279|And I'm running from the something I'm coming from";
            a[a.size] = "3280|3345|Becoming one; I am running from the other ones";
            a[a.size] = "3346|3397|And the other ones I'm running from";
            break;
    }

    return a;
}
