// ============================================================================
//  qol_subs_npc_buried.gsc  -  GENERATED by zm_qol - dev\subtitles\gen_subs_npc.py (2026-09-08)
//  SUBTITLES for the NON-player voices: the announcer, Maxis, Samantha, the
//  Richtofen in Stuhlinger's head, Brutus, the bus, the TVs and radios, the
//  ghost, the possessed zombies.
// ----------------------------------------------------------------------------
//  Every function below is the stock body copied VERBATIM out of the gsc-dump
//  (dev-only /# #/ blocks dropped, same-file calls qualified explicitly, as
//  qol_subs_tomb.gsc does) with ONE line added in front of each sound builtin
//  that plays a vox alias:
//      scripts\zm\zmqol_subtitles::zmqol_subs_npc( alias, source, position, listener )
//  The builtin decides who HEARS the line, so the same arguments decide who
//  READS it - see that function's banner. 🛑 Do not hand-edit: change the
//  generator's SPEC and re-run it; the dump is the source of truth.
//
//  Each copy prints "[zm_qol] subtitles: hook ran - <name>" first. STOCK_REFERENCE
//  7a: a hook is not proven until a boot shows that line.
// ============================================================================
#include common_scripts\utility;
#include maps\mp\_utility;
#include maps\mp\zombies\_zm_utility;

main()
{
    replaceFunc( maps\mp\zm_buried_sq::maxissayvoplay, ::zmqol_npc_maxissayvoplay );
    replaceFunc( maps\mp\zm_buried_sq::richtofensay, ::zmqol_npc_richtofensay );
    replaceFunc( maps\mp\zm_buried_sq::richtofen_zombie_vo_watcher, ::zmqol_npc_richtofen_zombie_vo_watcher );
    replaceFunc( maps\mp\zombies\_zm_ai_ghost::ghost_talk_to_target, ::zmqol_npc_ghost_talk_to_target );
    replaceFunc( maps\mp\zombies\_zm_ai_ghost::ghost_round_presentation_sound, ::zmqol_npc_ghost_round_presentation_sound );
}

init()
{
}

// ----- maps\mp\zm_buried_sq::maxissayvoplay  (stock verbatim + 1 caption line(s)) -----
zmqol_npc_maxissayvoplay( m_vo_spot, vox_line )
{
    //  v2.15.44 - survival maps cannot run the full easter egg, so quest voices stay silent there.
    //  Classic keeps the stock behavior below. (Generator SPEC marks this entry "survival_silent".)
    if ( !is_classic() )
        return;

    println( "[zm_qol] subtitles: hook ran - maxissayvoplay" );

    scripts\zm\zmqol_subtitles::zmqol_subs_npc( vox_line, m_vo_spot, undefined, undefined );
    m_vo_spot playsoundwithnotify( vox_line, "sound_done" + vox_line );
    m_vo_spot waittill( "sound_done" + vox_line );
    level.maxis_talking = 0;
    level notify( "MaxisSay_vo_finished" );
}

// ----- maps\mp\zm_buried_sq::richtofensay  (stock verbatim + 2 caption line(s)) -----
zmqol_npc_richtofensay( vox_line, time, play_in_3d )
{
    //  v2.15.44 - survival maps cannot run the full easter egg, so quest voices stay silent there.
    //  Classic keeps the stock behavior below. (Generator SPEC marks this entry "survival_silent".)
    if ( !is_classic() )
        return;

    println( "[zm_qol] subtitles: hook ran - richtofensay" );

    level endon( "end_game" );
    level endon( "intermission" );

    if ( isdefined( level.intermission ) && level.intermission )
        return;

    if ( isdefined( level.richcompleted ) && level.richcompleted && !( isdefined( level.metagame_sq_complete ) && level.metagame_sq_complete ) )
        return;

    level endon( "richtofen_c_complete" );

    if ( !isdefined( time ) )
        time = 2;

    while ( isdefined( level.richtofen_talking_to_samuel ) && level.richtofen_talking_to_samuel )
        wait 1;


    while ( isdefined( level.rich_sq_player ) && ( isdefined( level.rich_sq_player.isspeaking ) && level.rich_sq_player.isspeaking ) )
        wait 0.05;

    if ( !isdefined( level.rich_sq_player ) || !is_player_valid( level.rich_sq_player ) )
        return;

    if ( isdefined( level.metagame_sq_richtofen_complete ) && level.metagame_sq_richtofen_complete )
    {
        maps\mp\zm_buried_sq::stuhlingerpossessed();
        delay_thread( time, maps\mp\zm_buried_sq::stuhlingerpossessed, 0 );
    }

    if ( isdefined( play_in_3d ) && play_in_3d )
    {
        scripts\zm\zmqol_subtitles::zmqol_subs_npc( vox_line, level.rich_sq_player, undefined, undefined );
        level.rich_sq_player playsound( vox_line );
    }
    else
    {
        scripts\zm\zmqol_subtitles::zmqol_subs_npc( vox_line, undefined, undefined, level.rich_sq_player );
        level.rich_sq_player playsoundtoplayer( vox_line, level.rich_sq_player );
    }

    if ( !( isdefined( level.richtofen_talking_to_samuel ) && level.richtofen_talking_to_samuel ) )
        level thread maps\mp\zm_buried_sq::richtofen_talking( time );
}

// ----- maps\mp\zm_buried_sq::richtofen_zombie_vo_watcher  (stock verbatim + 1 caption line(s)) -----
zmqol_npc_richtofen_zombie_vo_watcher()
{
    println( "[zm_qol] subtitles: hook ran - richtofen_zombie_vo_watcher" );

    self endon( "death" );
    players = get_players();
    can_see = 0;

    while ( !can_see )
    {
        wait 2;

        foreach ( player in players )
        {
            if ( distance2dsquared( self.origin, player.origin ) < 262144 && sighttracepassed( self gettagorigin( "tag_eye" ), player.origin, 0, undefined ) )
                can_see = 1;
        }
    }

    str_vox = randomint( level._sq_m_possessed_zombie_vo.size );
    scripts\zm\zmqol_subtitles::zmqol_subs_npc( level._sq_m_possessed_zombie_vo[str_vox], self, undefined, undefined );
    self playsound( level._sq_m_possessed_zombie_vo[str_vox] );
}

// ----- maps\mp\zombies\_zm_ai_ghost::ghost_talk_to_target  (stock verbatim + 1 caption line(s)) -----
zmqol_npc_ghost_talk_to_target( player )
{
    println( "[zm_qol] subtitles: hook ran - ghost_talk_to_target" );

    self endon( "death" );
    level endon( "intermission" );
    vox_index = randomint( level.ghost_vox.size );
    vox_line = level.ghost_vox[vox_index];
    scripts\zm\zmqol_subtitles::zmqol_subs_npc( vox_line, undefined, undefined, player );
    self playsoundtoplayer( vox_line, player );
    player.ghost_talking = 1;
    wait 6;
    player.ghost_talking = 0;
}

// ----- maps\mp\zombies\_zm_ai_ghost::ghost_round_presentation_sound  (stock verbatim + 1 caption line(s)) -----
zmqol_npc_ghost_round_presentation_sound()
{
    println( "[zm_qol] subtitles: hook ran - ghost_round_presentation_sound" );

    level endon( "intermission" );
    self endon( "death" );

    while ( true )
    {
        players = getplayers();

        foreach ( player in players )
        {
            if ( is_player_valid( player ) )
            {
                vox_index = randomint( level.ghost_vox.size );
                vox_line = level.ghost_vox[vox_index];
                scripts\zm\zmqol_subtitles::zmqol_subs_npc( vox_line, undefined, undefined, player );
                self playsoundtoplayer( vox_line, player );
            }
        }

        wait( randomintrange( 2, 6 ) );
    }
}
