// T6 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool
#include common_scripts\utility;
#include maps\mp\_utility;
#include maps\mp\zombies\_zm_utility;
#include maps\mp\zombies\_zm_perks;
#include maps\mp\_visionset_mgr;
#include maps\mp\zombies\_zm_spawner;
#include maps\mp\zombies\_zm_laststand;
#include maps\mp\zombies\_zm_audio;
#include maps\mp\zombies\_zm_zonemgr;
#include maps\mp\zombies\_zm_equipment;
#include maps\mp\zombies\_zm_score;
#include maps\mp\zombies\_zm_ai_basic;
#include maps\mp\zombies\_zm_perk_vulture;

enable_vulture_perk_for_level()
{
    maps\mp\zombies\_zm_perks::register_perk_basic_info( "specialty_nomotionsensor", "vulture", 3000, &"ZOMBIE_PERK_VULTURE", "zombie_perk_bottle_vulture" );
    maps\mp\zombies\_zm_perks::register_perk_precache_func( "specialty_nomotionsensor", ::vulture_precache );
    maps\mp\zombies\_zm_perks::register_perk_clientfields( "specialty_nomotionsensor", ::vulture_register_clientfield, ::vulture_set_clientfield );
    maps\mp\zombies\_zm_perks::register_perk_threads( "specialty_nomotionsensor", ::give_vulture_perk, ::take_vulture_perk );
    maps\mp\zombies\_zm_perks::register_perk_machine( "specialty_nomotionsensor", ::vulture_perk_machine_setup, ::vulture_perk_machine_think );
    maps\mp\zombies\_zm_perks::register_perk_host_migration_func( "specialty_nomotionsensor", ::vulture_host_migration_func );
}

vulture_precache()
{
    precacheitem( "zombie_perk_bottle_vulture" );
    precacheshader( "specialty_vulture_zombies" );
    precachestring( &"ZOMBIE_PERK_VULTURE" );
    precachemodel( "p6_zm_vending_vultureaid" );
    precachemodel( "p6_zm_vending_vultureaid_on" );
    precachemodel( "p6_zm_perk_vulture_ammo" );
    precachemodel( "p6_zm_perk_vulture_points" );
    level._effect["vulture_light"] = loadfx( "misc/fx_zombie_cola_jugg_on" );
    level._effect["vulture_perk_zombie_stink"] = loadfx( "maps/zombie/fx_zm_vulture_perk_stink" );
    level._effect["vulture_perk_zombie_stink_trail"] = loadfx( "maps/zombie/fx_zm_vulture_perk_stink_trail" );
    level._effect["vulture_perk_bonus_drop"] = loadfx( "misc/fx_zombie_powerup_vulture" );
    level._effect["vulture_drop_picked_up"] = loadfx( "misc/fx_zombie_powerup_grab" );
    level._effect["vulture_perk_wallbuy_static"] = loadfx( "maps/zombie/fx_zm_vulture_wallbuy_rifle" );
    level._effect["vulture_perk_wallbuy_dynamic"] = loadfx( "maps/zombie/fx_zm_vulture_glow_question" );
    level._effect["vulture_perk_machine_glow_doubletap"] = loadfx( "maps/zombie/fx_zm_vulture_glow_dbltap" );
    level._effect["vulture_perk_machine_glow_juggernog"] = loadfx( "maps/zombie/fx_zm_vulture_glow_jugg" );
    level._effect["vulture_perk_machine_glow_revive"] = loadfx( "maps/zombie/fx_zm_vulture_glow_revive" );
    level._effect["vulture_perk_machine_glow_speed"] = loadfx( "maps/zombie/fx_zm_vulture_glow_speed" );
    level._effect["vulture_perk_machine_glow_marathon"] = loadfx( "maps/zombie/fx_zm_vulture_glow_marathon" );
    level._effect["vulture_perk_machine_glow_mule_kick"] = loadfx( "maps/zombie/fx_zm_vulture_glow_mule" );
    level._effect["vulture_perk_machine_glow_pack_a_punch"] = loadfx( "maps/zombie/fx_zm_vulture_glow_pap" );
    level._effect["vulture_perk_machine_glow_vulture"] = loadfx( "maps/zombie/fx_zm_vulture_glow_vulture" );
    level._effect["vulture_perk_mystery_box_glow"] = loadfx( "maps/zombie/fx_zm_vulture_glow_mystery_box" );
    level._effect["vulture_perk_powerup_drop"] = loadfx( "maps/zombie/fx_zm_vulture_glow_powerup" );
    level._effect["vulture_perk_zombie_eye_glow"] = loadfx( "misc/fx_zombie_eye_vulture" );

    //  The mod's own marker icons (zm_expanded.csc draws them). Plutonium only
    //  reads a raw .efx out of mod.iwd when a SERVER script loadfx's it, so the
    //  client-only loadfx never resolved, and every one of these markers fell
    //  back to vulture_perk_wallbuy_dynamic, the crossed rifles at 47% white.
    //  That was the blown-out Wunderfizz icon. Dimming the texture could not
    //  reach it. Gate: tools\check-client-fx-precache.py.
    level._effect["vulture_perk_machine_glow_deadshot"] = loadfx( "maps/zombie/fx_zm_vulture_glow_deadshot" );
    level._effect["vulture_perk_machine_glow_flopper"] = loadfx( "maps/zombie/fx_zm_vulture_glow_flopper" );
    level._effect["vulture_perk_machine_glow_generic"] = loadfx( "maps/zombie/fx_zm_vulture_glow_generic" );
    level._effect["vulture_perk_machine_glow_wunderfizz"] = loadfx( "maps/zombie/fx_zm_vulture_glow_wunderfizz" );
    onplayerconnect_callback( ::vulture_player_connect_callback );
}

vulture_player_connect_callback()
{
    self thread end_game_turn_off_vulture_overlay();
}

end_game_turn_off_vulture_overlay()
{
    self endon( "disconnect" );
    level waittill( "end_game" );
    self thread take_vulture_perk();
}

init_vulture()
{
    setdvarint( "zombies_perk_vulture_pickup_time", 12 );
    setdvarint( "zombies_perk_vulture_pickup_time_stink", 16 );
    setdvarint( "zombies_perk_vulture_drop_chance", 65 );
    setdvarint( "zombies_perk_vulture_ammo_chance", 33 );
    setdvarint( "zombies_perk_vulture_points_chance", 33 );
    setdvarint( "zombies_perk_vulture_stink_chance", 33 );
    setdvarint( "zombies_perk_vulture_drops_max", 20 );
    setdvarint( "zombies_perk_vulture_network_drops_max", 5 );
    setdvarint( "zombies_perk_vulture_network_time_frame", 250 );
    setdvarint( "zombies_perk_vulture_spawn_stink_zombie_cooldown", 12 );
    setdvarint( "zombies_perk_vulture_max_stink_zombies", 4 );
    level.perk_vulture = spawnstruct();
    level.perk_vulture.zombie_stink_array = [];
    level.perk_vulture.drop_time_last = 0;
    level.perk_vulture.drop_slots_for_network = 0;
    level.perk_vulture.last_stink_zombie_spawned = 0;
    level.perk_vulture.use_exit_behavior = 0;
    level.perk_vulture.clientfields = spawnstruct();
    level.perk_vulture.clientfields.scriptmovers = [];
    level.perk_vulture.clientfields.scriptmovers["vulture_stink_fx"] = 0;
    level.perk_vulture.clientfields.scriptmovers["vulture_drop_fx"] = 1;
    level.perk_vulture.clientfields.scriptmovers["vulture_drop_pickup"] = 2;
    level.perk_vulture.clientfields.scriptmovers["vulture_powerup_drop"] = 3;
    level.perk_vulture.clientfields.actors = [];
    level.perk_vulture.clientfields.actors["vulture_stink_trail_fx"] = 0;
    //  v2.7.3 - INERT. Nothing sets or clears this field any more (Vulture Aid
    //  no longer changes zombie eye colour); the index map entry stays only so
    //  the name remains valid for vulture_clientfield_actor_set/clear's assert.
    level.perk_vulture.clientfields.actors["vulture_eye_glow"] = 1;
    level.perk_vulture.clientfields.toplayer = [];
    level.perk_vulture.clientfields.toplayer["vulture_perk_active"] = 0;
    registerclientfield( "toplayer", "vulture_perk_toplayer", 12000, 1, "int" );

    if ( zmqol_vulture_has_actor_field() )
        registerclientfield( "actor", "vulture_perk_actor", 12000, 2, "int" );

    if ( zmqol_vulture_has_scriptmover_field() )
        registerclientfield( "scriptmover", "vulture_perk_scriptmover", 12000, 4, "int" );

    //  v1.99.68 - the see-through machine markers. FOUR bits, scriptmover set:
    //  one code per machine kind, so the client draws the right icon at the
    //  entity the SERVER says is really there. Replaces the client-side struct
    //  guessing entirely - see zmqol_vulture_marker_scan() below.
    //  See zmqol_vulture_marker_enabled() for the gate and the
    //  measured budget. The machines themselves are flagged in
    //  scripts/zm/wunderfizz.gsc::wunderfizzSetup().
    if ( zmqol_vulture_marker_enabled() )
        registerclientfield( "scriptmover", "zmqol_vulture_marker", 12000, 4, "int" );

    registerclientfield( "zbarrier", "vulture_perk_zbarrier", 12000, 1, "int" );
    registerclientfield( "toplayer", "sndVultureStink", 12000, 1, "int" );
    registerclientfield( "world", "vulture_perk_disable_solo_quick_revive_glow", 12000, 1, "int" );

    if ( zmqol_vulture_has_disease_meter() )
        registerclientfield( "toplayer", "vulture_perk_disease_meter", 12000, 5, "float" );

    //  🛑 v2.9.22 - 7 -> 1, in step with quality_of_life.gsc and
    //  zm_expanded.csc (see the banner there). overlay_lerp width is derived
    //  from this number on both sides; the three sites must stay equal.
    //  At 1 step the finalizer SKIPS overlay_lerp entirely (the same trick
    //  v2.9.16 used on visionset_lerp) - stock Mob registers NO lerp fields
    //  at all, and its toplayer set refused visionset_slot's 3 bits on the
    //  2026-08-31 boot; these 3 are exactly that space. The stink overlay
    //  snaps instead of fading on mod-ported maps; Buried keeps native 31.
    //
    //  🛑 v2.10.9 - "Buried keeps native 31" WAS A COMMENT, NOT CODE. This call
    //  passed a flat 1 on every map, Buried included, and Buried is the one map
    //  where the client half is NOT ours: it is the map's own COMPILED
    //  _zm_perk_vulture.csc, which registers 31 (measured in the 2026-09-02
    //  8:27 AM log - client overlay_lerp Float 5 bits, server field absent).
    //  At 1 step the finalizer skips overlay_lerp server-side while the client
    //  sizes it at 5 bits, so every player is dropped at connect with
    //  EXE_CLIENT_FIELD_MISMATCH. The step count now asks the same question the
    //  rest of this file's gates ask - who owns the client half.
    maps\mp\_visionset_mgr::vsmgr_register_info( "overlay", "vulture_stink_overlay", 12000, 120, zmqol_vulture_stink_lerp_steps(), 1 );
    maps\mp\zombies\_zm_spawner::add_cusom_zombie_spawn_logic( ::vulture_zombie_spawn_func );
    register_zombie_death_event_callback( ::zombies_drop_stink_on_death );
    level thread vulture_perk_watch_mystery_box();

    //  v1.99.68 - the see-through machine markers. See the banner on the function.
    if ( zmqol_vulture_marker_enabled() )
    {
        //  🛑 v1.99.71 - WITHOUT THIS THE DVAR DOES NOT EXIST. The client reads it
        //  with getdvarintdefault(), which returns the default without ever
        //  creating the dvar - so the console answered "Unknown cmd
        //  vulture_marker_height" when the user tried to tune it live (reported
        //  2026-08-19, with a screenshot). One setdvar registers the name; the
        //  client's zmqol_vulture_marker_height_watch() does the rest. Guarded so
        //  a value typed in a previous map is not stamped back to the default.
        if ( getdvar( "vulture_marker_height" ) == "" )
            setdvar( "vulture_marker_height", 38 );

        level thread zmqol_vulture_marker_scan();
    }
    level thread vulture_perk_watch_fire_sale();
    level thread vulture_perk_watch_powerup_drops();
    level thread vulture_handle_solo_quick_revive();
    assert( !isdefined( level.exit_level_func ), "vulture perk is attempting to use level.exit_level_func, but one already exists for this level!" );
    level.exit_level_func = ::vulture_zombies_find_exit_point;
    level.perk_vulture.invalid_bonus_ammo_weapons = array( "time_bomb_zm", "time_bomb_detonator_zm" );

    if ( !isdefined( level.perk_vulture.func_zombies_find_valid_exit_locations ) )
        level.perk_vulture.func_zombies_find_valid_exit_locations = ::get_valid_exit_points_for_zombie;

    setup_splitscreen_optimizations();
    initialize_bonus_entity_pool();
    initialize_stink_entity_pool();
/#
    level.vulture_devgui_spawn_stink = ::vulture_devgui_spawn_stink;
#/
}

// ============================================================================
//  zm_qol: THE THREE FIELDS ORIGINS AND MOB CANNOT AFFORD
//
//  Vulture Aid registers eight clientfields across four sets, and two maps ran
//  out of room in THREE different sets:
//
//    zm_tomb   Client Field Set ACTOR is out of space        <- vulture_perk_actor, 2 bits
//    zm_prison Client Field Set TOPLAYER is out of space     <- vulture_perk_disease_meter, 5 bits
//    zm_tomb   Client Field Set SCRIPTMOVER is out of space  <- vulture_perk_scriptmover, 4 bits
//
//  The field named in the error is whichever one asks LAST, so the message
//  names the MAP's field as often as ours - read it as "someone before me used
//  the space".
//
//  🌟 EVERY CLIENTFIELD SET IS EXACTLY 32 BITS WIDE, and this is measured, not
//  assumed. `Black Ops 2 Grand Resources\T6-Data-Archive-main\ZM\Clientfields\`
//  holds a per-map runtime dump of every registered field and its width. Total
//  them per set and Origins classic reads:
//
//        scriptmover  32 / 32   <- ZERO free. Highest of any map in the game.
//        actor        31 / 32   <- ONE free
//        toplayer     61 / 64
//
//  Both crashes fall straight out of those numbers. Vulture's 2-bit actor field
//  fits in one free bit only if you round down, so stock's 1-bit
//  zone_capture_zombie asked after it and got the error - which is exactly what
//  checkpoint 17 saw and could not explain. And nothing whatsoever fits in
//  scriptmover, so no narrower encoding rescues it: the four flags in
//  vulture_perk_scriptmover are disjoint enough to pack into a 3-bit enum, and
//  it would not have helped, because zero free bits means zero.
//
//  📝 Treyarch hit this same wall. Origins is the ONLY map in the game that
//  sets level._no_equipment_activated_clientfield (zm_tomb.gsc:100), which
//  suppresses the 4-bit equipment_activated field every other zombies map
//  registers. Without that cut Origins would be at 36/32 on its own.
//
//  🛑 WHAT DROPPING THE SCRIPTMOVER FIELD ACTUALLY COSTS ON ORIGINS. The other
//  two drops were free - a zombie eye glow and a meter. This one is not, and it
//  should not be described as cosmetic-only:
//    vulture_stink_fx      the stink pile. Its entity is a bare tag_origin
//                          (initialize_stink_entity_pool), so the clientfield
//                          IS its entire visual - the pile becomes INVISIBLE.
//                          It still works; zombies are still distracted by it.
//    vulture_drop_fx       glow on a bonus drop. The drop itself still renders,
//    vulture_drop_pickup   because delay_showing_vulture_ent setmodel()s and
//                          show()s it independently of the field.
//    vulture_powerup_drop  the green highlight on powerups.
//  Buying any of it back means taking bits off a stock Origins system
//  (element_glow_fx 4, bryce_cake 2), which breaks the base map to decorate an
//  added perk. Not a trade this project makes.
//
//  🛑 THE CLIENT MUST DROP THE IDENTICAL FIELD. A field registered on one side
//  only makes that set one width wider on that side, which is
//  EXE_CLIENT_FIELD_MISMATCH for everyone before the map starts. The client
//  twins of these three functions are in scripts\zm\zm_expanded.csc - it is a
//  separate compilation unit so the copy is unavoidable, and it is the first
//  place to look if a clientfield error ever appears.
//
//  Note these are deliberately SEPARATE from zmqol_vulture_enabled(), which
//  answers "does this map get the perk at all". These answer "which fields can
//  this map afford", and now that both maps get the perk, the two questions
//  have different answers.
// ============================================================================
zmqol_vulture_has_actor_field()
{
    return getdvar( "mapname" ) != "zm_tomb";
}

//  v1.58.4 - ORIGINS DROPS THE DISEASE METER TOO, to pay for Tombstone.
//
//  vulture_perk_disease_meter is 5 bits in the toplayer set. Origins' toplayer
//  was measured EXACTLY FULL by a failed boot on 2026-08-07:
//
//      Trying to assign 1 bits for netfield vulture_perk_toplayer
//      but Client Field Set toplayer is out of space.
//
//  Read that the way checkpoint 20 §2 says to - the field named is whichever
//  asks LAST, not the cause. perk_tombstone (2 bits on Origins, which has
//  emp_grenade_zm) had just taken the last 2 free bits, so vulture's next 1 bit
//  had nowhere to go. That gives an exact figure: Origins had 2 free bits, and
//  with Vulture in it has 0.
//
//  Dropping the disease meter here frees 5, so Tombstone's 2 fit with 3 to
//  spare rather than 0 - deliberately not a change that lands exactly on the
//  ceiling, because the last one did and that is how the boot was lost.
//
//  The user chose this trade explicitly on 2026-08-07 ("drop a vulture cosmetic
//  for it"). Origins keeps the perk and loses the stink meter - exactly the
//  deal Mob has had since v1.55.0, using this same gate.
//
//  🛑 The client twin is zm_expanded.csc::zmqol_vulture_has_disease_meter().
//  These two decide whether a registerclientfield runs; if they disagree the
//  toplayer set is 5 bits wider on one side and everyone is dropped with
//  EXE_CLIENT_FIELD_MISMATCH before the map starts.
//  📝 zm_tomb was briefly listed here (v1.58.4) to free 5 toplayer bits for
//  Tombstone. It is gone again because v1.59.0 turns Vulture OFF on Origins
//  entirely - see zmqol_vulture_enabled() in quality_of_life.gsc - so nothing
//  in this file registers there any more and the exception would be dead and
//  misleading. Mob remains, where the perk DOES ship and only the meter is cut.
zmqol_vulture_has_disease_meter()
{
    return getdvar( "mapname" ) != "zm_prison";
}

zmqol_vulture_has_scriptmover_field()
{
    return getdvar( "mapname" ) != "zm_tomb";
}

// ============================================================================
//  zmqol_vulture_stink_lerp_steps  -  WIDTH OF overlay_lerp        (v2.10.9)
// ----------------------------------------------------------------------------
//  Same rule as zmqol_vulture_marker_enabled() above: the answer is decided by
//  WHO OWNS THE CLIENT HALF, never by who has the perk.
//
//      Buried      -> the map's own compiled client script for this perk
//                     (clientscripts/mp/zombies/_zm_perk_vulture.csc,
//                     compiled) registers 31, and this file cannot
//                     change it (it is bytecode, and the decompile is lossy -
//                     see zm_expanded.csc::zmqol_init_vulture_trimmed()).
//                     So the server matches it at 31.
//      every other -> zm_expanded.csc::zmqol_init_vulture_trimmed() supplies
//      map            the client half and registers 1, which makes the
//                     visionset manager's finalizer skip overlay_lerp on both
//                     sides. That is the v2.9.22 bit saving and it stands.
//
//  🛑 THE TWO NUMBERS BELOW ARE TWINS OF CLIENT CODE, NOT PREFERENCES. 31 is
//  the stock compiled csc's; 1 is zm_expanded.csc line ~1512. Changing either
//  without its client twin resizes overlay_lerp on one side only, which is
//  EXE_CLIENT_FIELD_MISMATCH at load for every player - the exact failure this
//  function was added to fix, and the third time Vulture has caused it.
// ============================================================================
zmqol_vulture_stink_lerp_steps()
{
    if ( getdvar( "mapname" ) == "zm_buried" )
        return 31;

    return 1;
}

// ============================================================================
//  zmqol_vulture_marker_enabled  -  gate for the Wunderfizz marker
//                                                                   (v1.99.67)
// ----------------------------------------------------------------------------
//  User, 2026-08-19: *"the wunderfizz machines still didn't have an icon for
//  vultures aid. fix that to have the same question mark icon as the mystery
//  box for the wunderfizz machine"*. Stock Vulture Aid was written for Buried,
//  which has no Wunderfizz, so no such marker exists anywhere in the game.
//
//  🛑 THE GATE IS ABOUT WHO OWNS THE CLIENT HALF, NOT ABOUT WHO HAS THE PERK.
//  This file ships raw in mod.iwd, so it shadows stock's copy on EVERY map -
//  including Buried, where the perk is Treyarch's own and the client half is
//  Buried's COMPILED _zm_perk_vulture.csc. Registering a field here that that
//  compiled script does not register is a width mismatch on the scriptmover
//  set, which is EXE_CLIENT_FIELD_MISMATCH at load for every player.
//
//  So the marker exists exactly where zm_expanded.csc::zmqol_init_vulture_trimmed()
//  supplies the client half - every map the mod enables Vulture on. Buried keeps
//  stock's perk untouched; Origins and TranZit do not run this function at all
//  (the perk is off there for clientfield-budget reasons), so they are listed
//  only to make the rule readable rather than because it changes anything.
//
//  🌟 THE BIT WAS MEASURED, NOT HOPED FOR. Stock scriptmover usage from the
//  per-map dumps in Black Ops 2 Grand Resources\...\Clientfields\: Nuketown
//  8/32, Die Rise 11/32, Mob 15/32. This mod adds 4 (vulture_perk_scriptmover)
//  and 1 (zmqol_whoswho_clone_glow) on top, plus 4 on Die Rise for the escape
//  pod - so the worst case is about 20/32 and one more bit is comfortable.
//  Buried is 25/32 stock and Origins is 32/32, which is exactly why neither of
//  them is in scope here.
//
//  🛑 THE CLIENT TWIN IS zm_expanded.csc::zmqol_vulture_marker_enabled()
//  AND IT MUST RETURN THE SAME ANSWER. If the two ever disagree the scriptmover
//  set differs in width between server and client and everyone is dropped.
// ============================================================================
zmqol_vulture_marker_enabled()
{
    map = getdvar( "mapname" );

    if ( map == "zm_buried" || map == "zm_tomb" )
        return 0;

    //  🛑 v2.7.1 - WAS "map == zm_transit", WHICH EXCLUDED EVERY TRANZIT-FAMILY
    //  SURVIVAL LOCATION TOO. User, 2026-08-28: the Vulture Aid Wunderfizz icon
    //  shows on Nuketown but not on Town. Diner/Farm/Town/Bus Depot all share
    //  mapname "zm_transit" with classic TranZit, but the perk ITSELF is only
    //  off on classic (see zmqol_vulture_enabled() in quality_of_life.gsc, the
    //  same test, copied verbatim so the two can never disagree about which
    //  locations have the perk vs. which have the marker) - the marker gate had
    //  never been updated to match when v1.84.0/v1.89.0 narrowed the perk gate
    //  from "all zm_transit" down to "classic only".
    if ( map == "zm_transit" &&
         getdvar( "ui_zm_mapstartlocation" ) == "transit" &&
         getdvar( "ui_gametype" ) != "zstandard" && getdvar( "ui_gametype" ) != "zgrief" )
        return 0;

    return 1;
}

add_additional_stink_locations_for_zone( str_zone, a_zones )
{
    if ( !isdefined( level.perk_vulture.zones_for_extra_stink_locations ) )
        level.perk_vulture.zones_for_extra_stink_locations = [];

    level.perk_vulture.zones_for_extra_stink_locations[str_zone] = a_zones;
}

vulture_register_clientfield()
{
    registerclientfield( "toplayer", "perk_vulture", 12000, 2, "int" );
}

vulture_set_clientfield( state )
{
    self setclientfieldtoplayer( "perk_vulture", state );
}

give_vulture_perk()
{
    vulture_debug_text( "player " + self getentitynumber() + " has vulture perk!" );

    if ( !isdefined( self.perk_vulture ) )
        self.perk_vulture = spawnstruct();

    self.perk_vulture.active = 1;
    self vulture_vision_toggle( 1 );
    self vulture_clientfield_toplayer_set( "vulture_perk_active" );
    self thread _vulture_perk_think();
}

take_vulture_perk()
{
    if ( isdefined( self.perk_vulture ) && ( isdefined( self.perk_vulture.active ) && self.perk_vulture.active ) )
    {
        vulture_debug_text( "player " + self getentitynumber() + " has lost vulture perk!" );
        self.perk_vulture.active = 0;

        if ( !self maps\mp\zombies\_zm_laststand::player_is_in_laststand() )
            self.ignoreme = 0;

        self vulture_vision_toggle( 0 );
        self vulture_clientfield_toplayer_clear( "vulture_perk_active" );
        self set_vulture_overlay( 0 );
        self.vulture_stink_value = 0;

        if ( zmqol_vulture_has_disease_meter() )   // zm_qol: not registered on Mob
            self setclientfieldtoplayer( "vulture_perk_disease_meter", 0 );

        self notify( "vulture_perk_lost" );
    }
}

vulture_host_migration_func()
{
    a_vulture_perk_machines = getentarray( "vending_vulture", "targetname" );

    foreach ( perk_machine in a_vulture_perk_machines )
    {
        if ( isdefined( perk_machine.model ) && perk_machine.model == "p6_zm_vending_vultureaid_on" )
        {
            perk_machine maps\mp\zombies\_zm_perks::perk_fx( undefined, 1 );
            perk_machine thread maps\mp\zombies\_zm_perks::perk_fx( "vulture_light" );
        }
    }

    foreach ( ent in level.perk_vulture.stink_ent_pool )
    {
        if ( isdefined( ent ) )
        {
            arrayremovevalue( level.perk_vulture.zombie_stink_array, ent, 0 );
            ent clear_stink_ent();
        }
    }

    foreach ( ent in level.perk_vulture.bonus_drop_ent_pool )
    {
        if ( isdefined( ent ) )
            ent clear_bonus_ent();
    }
}

vulture_perk_add_invalid_bonus_ammo_weapon( str_weapon )
{
    assert( isdefined( level.perk_vulture ), "vulture_perk_add_invalid_bonus_ammo_weapon() was called before vulture perk was initialized. Make sure this is called after the vulture perk initialization func!" );
    level.perk_vulture.invalid_bonus_ammo_weapons[level.perk_vulture.invalid_bonus_ammo_weapons.size] = str_weapon;
}

vulture_perk_machine_setup( use_trigger, perk_machine, bump_trigger, collision )
{
    use_trigger.script_sound = "mus_perks_vulture_jingle";
    use_trigger.script_string = "vulture_perk";
    use_trigger.script_label = "mus_perks_vulture_sting";
    use_trigger.target = "vending_vulture";
    perk_machine.script_string = "vulture_perk";
    perk_machine.targetname = "vending_vulture";
    bump_trigger.script_string = "vulture_perk";
}

vulture_perk_machine_think()
{
    init_vulture();

    while ( true )
    {
        machine = getentarray( "vending_vulture", "targetname" );
        machine_triggers = getentarray( "vending_vulture", "target" );
        array_thread( machine_triggers, maps\mp\zombies\_zm_perks::set_power_on, 0 );

        for ( i = 0; i < machine.size; i++ )
            machine[i] setmodel( "p6_zm_vending_vultureaid" );

        level waittill( "specialty_nomotionsensor" + "_on" );
        level notify( "specialty_nomotionsensor" + "_power_on" );

        for ( i = 0; i < machine.size; i++ )
        {
            machine[i] setmodel( "p6_zm_vending_vultureaid_on" );
            machine[i] vibrate( vectorscale( ( 0, -1, 0 ), 100.0 ), 0.3, 0.4, 3 );
            machine[i] playsound( "zmb_perks_power_on" );
            machine[i] thread maps\mp\zombies\_zm_perks::perk_fx( "vulture_light" );
            machine[i] thread maps\mp\zombies\_zm_perks::play_loop_on_machine();
        }

        array_thread( machine_triggers, maps\mp\zombies\_zm_perks::set_power_on, 1 );
        level waittill( "specialty_nomotionsensor" + "_off" );
        array_thread( machine, maps\mp\zombies\_zm_perks::turn_perk_off );
    }
}

do_vulture_death( player )
{
    if ( isdefined( self ) )
        self thread _do_vulture_death( player );
}

_do_vulture_death( player )
{
    if ( should_do_vulture_drop( self.origin ) )
    {
        str_bonus = get_vulture_drop_type();
        str_identifier = "_" + self getentitynumber() + "_" + gettime();
        v_drop_origin = groundtrace( self.origin + vectorscale( ( 0, 0, 1 ), 50.0 ), self.origin - vectorscale( ( 0, 0, -1 ), 100.0 ), 0, self )["position"];
        player thread show_debug_info( self.origin, str_identifier, str_bonus );
        self thread vulture_drop_funcs( self.origin, player, str_identifier, str_bonus );
    }
}

vulture_drop_funcs( v_origin, player, str_identifier, str_bonus )
{
    vulture_drop_count_increment();

    switch ( str_bonus )
    {
        case "ammo":
            e_temp = player _vulture_drop_model( str_identifier, "p6_zm_perk_vulture_ammo", v_origin, vectorscale( ( 0, 0, 1 ), 15.0 ) );
            self thread check_vulture_drop_pickup( e_temp, player, str_identifier, str_bonus );
            break;
        case "points":
            e_temp = player _vulture_drop_model( str_identifier, "p6_zm_perk_vulture_points", v_origin, vectorscale( ( 0, 0, 1 ), 15.0 ) );
            self thread check_vulture_drop_pickup( e_temp, player, str_identifier, str_bonus );
            break;
        case "stink":
            self _drop_zombie_stink( player, str_identifier, str_bonus );
            break;
    }
}

_drop_zombie_stink( player, str_identifier, str_bonus )
{
    self clear_zombie_stink_fx();
    e_temp = player zombie_drops_stink( self, str_identifier );
    e_temp = player _vulture_spawn_fx( str_identifier, self.origin, str_bonus, e_temp );
    clean_up_stink( e_temp );
}

zombie_drops_stink( ai_zombie, str_identifier )
{
    e_temp = ai_zombie.stink_ent;

    if ( isdefined( e_temp ) )
    {
        e_temp thread delay_showing_vulture_ent( self, ai_zombie.origin );
        level.perk_vulture.zombie_stink_array[level.perk_vulture.zombie_stink_array.size] = e_temp;
        self delay_notify( str_identifier, getdvarint( #"zombies_perk_vulture_pickup_time_stink" ) );
    }

    return e_temp;
}

delay_showing_vulture_ent( player, v_moveto_pos, str_model, func )
{
    self.drop_time = gettime();
    wait_network_frame();
    wait_network_frame();
    self.origin = v_moveto_pos;
    wait_network_frame();

    if ( isdefined( str_model ) )
        self setmodel( str_model );

    self show();

    if ( isplayer( player ) )
    {
        self setinvisibletoall();
        self setvisibletoplayer( player );
    }

    if ( isdefined( func ) )
        self [[ func ]]();
}

clean_up_stink( e_temp )
{
    e_temp vulture_clientfield_scriptmover_clear( "vulture_stink_fx" );
    arrayremovevalue( level.perk_vulture.zombie_stink_array, e_temp, 0 );
    wait 4;
    e_temp clear_stink_ent();
}

_delete_vulture_ent( n_delay )
{
    if ( !isdefined( n_delay ) )
        n_delay = 0;

    if ( n_delay > 0 )
    {
        self ghost();
        wait( n_delay );
    }

    self clear_bonus_ent();
}

_vulture_drop_model( str_identifier, str_model, v_model_origin, v_offset )
{
    if ( !isdefined( v_offset ) )
        v_offset = ( 0, 0, 0 );

    if ( !isdefined( self.perk_vulture_models ) )
        self.perk_vulture_models = [];

    e_temp = get_unused_bonus_ent();

    if ( !isdefined( e_temp ) )
    {
        self notify( str_identifier );
        return;
    }

    e_temp thread delay_showing_vulture_ent( self, v_model_origin + v_offset, str_model, ::set_vulture_drop_fx );
    self.perk_vulture_models[self.perk_vulture_models.size] = e_temp;
    e_temp setinvisibletoall();
    e_temp setvisibletoplayer( self );
    e_temp thread _vulture_drop_model_thread( str_identifier, self );
    return e_temp;
}

set_vulture_drop_fx()
{
    self vulture_clientfield_scriptmover_set( "vulture_drop_fx" );
}

_vulture_drop_model_thread( str_identifier, player )
{
    self thread _vulture_model_blink_timeout( player );
    player waittill_any( str_identifier, "death_or_disconnect", "vulture_perk_lost" );
    self vulture_clientfield_scriptmover_clear( "vulture_drop_fx" );
    n_delete_delay = 0.1;

    if ( isdefined( self.picked_up ) && self.picked_up )
    {
        self _play_vulture_drop_pickup_fx();
        n_delete_delay = 1;
    }

    if ( isdefined( player.perk_vulture_models ) )
    {
        arrayremovevalue( player.perk_vulture_models, self, 0 );
        self.perk_vulture_models = remove_undefined_from_array( player.perk_vulture_models );
    }

    self _delete_vulture_ent( n_delete_delay );
}

_vulture_model_blink_timeout( player )
{
    self endon( "death" );
    player endon( "death" );
    player endon( "disconnect" );
    self endon( "stop_vulture_behavior" );
    n_time_total = getdvarint( #"zombies_perk_vulture_pickup_time" );
    n_frames = n_time_total * 20;
    n_section = int( n_frames / 6 );
    n_flash_slow = n_section * 3;
    n_flash_medium = n_section * 4;
    n_flash_fast = n_section * 5;
    b_show = 1;
    i = 0;

    while ( i < n_frames )
    {
        if ( i < n_flash_slow )
            n_multiplier = n_flash_slow;
        else if ( i < n_flash_medium )
            n_multiplier = 10;
        else if ( i < n_flash_fast )
            n_multiplier = 5;
        else
            n_multiplier = 2;

        if ( b_show )
        {
            self show();
            self setinvisibletoall();
            self setvisibletoplayer( player );
        }
        else
            self ghost();

        b_show = !b_show;
        i = i + n_multiplier;
        wait( 0.05 * n_multiplier );
    }
}

_vulture_spawn_fx( str_identifier, v_fx_origin, str_bonus, e_temp )
{
    b_delete = 0;

    if ( !isdefined( e_temp ) )
    {
        e_temp = get_unused_bonus_ent();

        if ( !isdefined( e_temp ) )
        {
            self notify( str_identifier );
            return;
        }

        b_delete = 1;
    }

    e_temp thread delay_showing_vulture_ent( self, v_fx_origin, "tag_origin", ::clientfield_set_vulture_stink_enabled );

    if ( isplayer( self ) )
        self waittill_any( str_identifier, "disconnect", "vulture_perk_lost" );
    else
        self waittill( str_identifier );

    if ( b_delete )
        e_temp _delete_vulture_ent();

    return e_temp;
}

clientfield_set_vulture_stink_enabled()
{
    self vulture_clientfield_scriptmover_set( "vulture_stink_fx" );
}

should_do_vulture_drop( v_death_origin )
{
    b_is_inside_playable_area = check_point_in_enabled_zone( v_death_origin, 1 );
    b_ents_are_available = get_unused_bonus_ent_count() > 0;
    b_network_slots_available = level.perk_vulture.drop_slots_for_network < getdvarint( #"zombies_perk_vulture_network_drops_max" );
    n_roll = randomint( 100 );
    b_passed_roll = n_roll > 100 - getdvarint( #"zombies_perk_vulture_drop_chance" );
    b_is_stink_zombie = isdefined( self.is_stink_zombie ) && self.is_stink_zombie;
    b_should_drop = b_is_stink_zombie || b_is_inside_playable_area && b_ents_are_available && b_network_slots_available && b_passed_roll;
    return b_should_drop;
}

get_vulture_drop_type()
{
    n_chance_ammo = getdvarint( #"zombies_perk_vulture_ammo_chance" );
    n_chance_points = getdvarint( #"zombies_perk_vulture_points_chance" );
    n_chance_stink = getdvarint( #"zombies_perk_vulture_stink_chance" );
    n_total_weight = n_chance_ammo + n_chance_points;
    n_cutoff_ammo = n_chance_ammo;
    n_cutoff_points = n_chance_ammo + n_chance_points;
    n_roll = randomint( n_total_weight );

    if ( n_roll < n_cutoff_ammo )
        str_bonus = "ammo";
    else
        str_bonus = "points";

    if ( isdefined( self.is_stink_zombie ) && self.is_stink_zombie )
        str_bonus = "stink";

    return str_bonus;
}

show_debug_info( v_drop_point, str_identifier, str_bonus )
{
/#
    n_radius = 32;

    if ( str_bonus == "stink" )
        n_radius = 70;

    if ( getdvarint( #"zombies_debug_vulture_perk" ) )
    {
        self endon( str_identifier );
        vulture_debug_text( "zombie dropped " + str_bonus );

        for ( i = 0; i < get_vulture_drop_duration( str_bonus ) * 20; i++ )
        {
            circle( v_drop_point, n_radius, get_debug_circle_color( str_bonus ), 0, 1, 1 );
            wait 0.05;
        }
    }
#/
}

get_vulture_drop_duration( str_bonus )
{
    str_dvar = "zombies_perk_vulture_pickup_time";

    if ( str_bonus == "stink" )
        str_dvar = "zombies_perk_vulture_pickup_time_stink";

    n_duration = getdvarint( str_dvar );
    return n_duration;
}

get_debug_circle_color( str_bonus )
{
    switch ( str_bonus )
    {
        case "ammo":
            v_color = ( 0, 0, 1 );
            break;
        case "points":
            v_color = ( 1, 1, 0 );
            break;
        case "stink":
            v_color = ( 0, 1, 0 );
            break;
        default:
            v_color = ( 1, 1, 1 );
            break;
    }

    return v_color;
}

check_vulture_drop_pickup( e_temp, player, str_identifier, str_bonus )
{
    if ( !isdefined( e_temp ) )
        return;

    player endon( "death" );
    player endon( "disconnect" );
    e_temp endon( "death" );
    e_temp endon( "stop_vulture_behavior" );
    wait_network_frame();
    n_times_to_check = int( get_vulture_drop_duration( str_bonus ) / 0.15 );

    for ( i = 0; i < n_times_to_check; i++ )
    {
        b_player_inside_radius = distancesquared( e_temp.origin, player.origin ) < 1024;

        if ( b_player_inside_radius )
        {
            e_temp.picked_up = 1;
            break;
        }

        wait 0.15;
    }

    player notify( str_identifier );

    if ( b_player_inside_radius )
        player give_vulture_bonus( str_bonus );
}

_handle_zombie_stink( b_player_inside_radius )
{
    if ( !isdefined( self.perk_vulture.is_in_zombie_stink ) )
        self.perk_vulture.is_in_zombie_stink = 0;

    b_in_stink_last_check = self.perk_vulture.is_in_zombie_stink;
    self.perk_vulture.is_in_zombie_stink = b_player_inside_radius;

    if ( self.perk_vulture.is_in_zombie_stink )
    {
        n_current_time = gettime();

        if ( !b_in_stink_last_check )
        {
            self.perk_vulture.stink_time_entered = n_current_time;
            self toggle_stink_overlay( 1 );
            self thread stink_react_vo();
        }

        b_should_ignore_player = isdefined( self.perk_vulture.stink_time_entered ) && ( n_current_time - self.perk_vulture.stink_time_entered ) * 0.001 >= 0.0;

        if ( b_should_ignore_player )
            self.ignoreme = 1;

        if ( get_targetable_player_count() == 0 || !self are_any_players_in_adjacent_zone() )
        {
            if ( b_should_ignore_player && !level.perk_vulture.use_exit_behavior )
            {
                level.perk_vulture.use_exit_behavior = 1;
                level.default_find_exit_position_override = ::vulture_perk_should_zombies_resume_find_flesh;
                self thread vulture_zombies_find_exit_point();
            }
        }
    }
    else if ( b_in_stink_last_check )
    {
        self.perk_vulture.stink_time_exit = gettime();
        self thread _zombies_reacquire_player_after_leaving_stink();
    }
}

stink_react_vo()
{
    self endon( "death" );
    self endon( "disconnect" );
    wait 1.0;
    chance = get_response_chance( "vulture_stink" );

    if ( chance > randomintrange( 1, 100 ) )
        self maps\mp\zombies\_zm_audio::create_and_play_dialog( "general", "vulture_stink" );
}

get_targetable_player_count()
{
    n_targetable_player_count = 0;

    foreach ( player in get_players() )
    {
        if ( !isdefined( player.ignoreme ) || !player.ignoreme )
            n_targetable_player_count++;
    }

    return n_targetable_player_count;
}

are_any_players_in_adjacent_zone()
{
    b_players_in_adjacent_zone = 0;
    str_zone = self maps\mp\zombies\_zm_zonemgr::get_player_zone();

    foreach ( player in get_players() )
    {
        if ( player == self )
            continue;

        str_zone_compare = player maps\mp\zombies\_zm_zonemgr::get_player_zone();

        if ( isinarray( level.zones[str_zone].adjacent_zones, str_zone_compare ) && ( isdefined( level.zones[str_zone].adjacent_zones[str_zone_compare].is_connected ) && level.zones[str_zone].adjacent_zones[str_zone_compare].is_connected ) )
        {
            b_players_in_adjacent_zone = 1;
            break;
        }
    }

    return b_players_in_adjacent_zone;
}

toggle_stink_overlay( b_show_overlay )
{
    if ( !isdefined( self.vulture_stink_value ) )
        self.vulture_stink_value = 0;

    if ( b_show_overlay )
        self thread _ramp_up_stink_overlay();
    else
        self thread _ramp_down_stink_overlay();
}

_ramp_up_stink_overlay( b_instant_change )
{
    if ( !isdefined( b_instant_change ) )
        b_instant_change = 0;

    self notify( "vulture_perk_stink_ramp_up_done" );
    self endon( "vulture_perk_stink_ramp_up_done" );
    self endon( "death_or_disconnect" );
    self endon( "vulture_perk_lost" );
    self setclientfieldtoplayer( "sndVultureStink", 1 );

    //  zm_qol v1.41.0 - the stink audio, from the SERVER.
    //
    //  The clientfield above is stock's way of telling the client to start its
    //  own stink sounds, and the client does exactly that - but it asks for
    //  zmb_vulture_stink_player_start / _loop, which live in zmb_buried.all and
    //  do not exist on any map this mod adds Vulture Aid to. Silent, no error.
    //
    //  🛑 The client half CANNOT be edited the way the server half can. It ships
    //  as COMPILED bytecode inside zm_buried_patch.ff (magic 80 47 53 43), not
    //  raw text - correcting this project's own note that fastfiles store scripts
    //  as raw text, which is true of some and not of this one. Its alias strings
    //  are patchable in place at equal length, but that means editing bytecode
    //  with a possible header checksum, to fix something the server can simply do
    //  itself.
    //
    //  So the mod plays its own copies here instead. The clientfield is left
    //  alone, so the client's visual half is untouched and Buried, which has the
    //  real aliases, is completely unaffected.
    self thread zmqol_vulture_stink_audio();

    if ( !isdefined( level.perk_vulture.stink_change_increment ) )
        level.perk_vulture.stink_change_increment = pow( 2, 5 ) * 0.25 / 8;

    while ( self.perk_vulture.is_in_zombie_stink )
    {
        self.vulture_stink_value = self.vulture_stink_value + level.perk_vulture.stink_change_increment;

        if ( self.vulture_stink_value > pow( 2, 5 ) - 1 )
            self.vulture_stink_value = pow( 2, 5 ) - 1;

        fraction = self _get_disease_meter_fraction();

        if ( zmqol_vulture_has_disease_meter() )   // zm_qol: not registered on Mob
            self setclientfieldtoplayer( "vulture_perk_disease_meter", fraction );

        self set_vulture_overlay( fraction );
        vulture_debug_text( "disease counter = " + self.vulture_stink_value );
        wait 0.25;
    }
}

//  🛑 zm_qol: THE STINK OVERLAY YIELDS TO ZOMBIE BLOOD.
//
//  User report, via a tester: with Zombie Blood active, walking into the green
//  stink cloud HIDES Zombie Blood's screen effect.
//
//  Measured cause, not a theory. The visionset manager's "overlay" type is
//  single-winner per player: get_first_active_name() (_visionset_mgr.gsc:361)
//  walks sorted_prio_keys - sorted DESCENDING by priority - and returns the FIRST
//  active one, and update_clientfields() then sends that one slot index. So the
//  whole overlay ladder is winner-take-all:
//
//      200  zombie_time_bomb_overlay
//      120  vulture_stink_overlay   <- this one
//      120  zm_afterlife_filter
//       75  zm_ai_avogadro_electrified
//       61  zm_trap_burn
//       60  zm_trap_electric
//       50  zm_ai_screecher_blur
//       20  zm_transit_burn
//       16  zm_powerup_zombie_blood_overlay   <- bottom of the ladder
//
//  Both numbers are FAITHFUL to stock - Buried registers the stink at 120
//  (_zm_perk_vulture.gsc:106) and Origins registers Zombie Blood's overlay at 16
//  (_zm_powerup_zombie_blood.gsc:26). Nothing was mis-ported.
//
//  🌟 VANILLA HAS NO OPINION HERE. Vulture Aid is Buried-only and Zombie Blood is
//  Origins-only, so the two never coexist in stock BO2 and there is no stock
//  behaviour to match. This mod created the pairing by putting both on every map,
//  so resolving it is not re-tuning a ported perk - there is no original to
//  deviate from.
//
//  🛑 WHY NOT JUST RAISE ZOMBIE BLOOD'S PRIORITY. Because 16 is the bottom of the
//  ladder for a reason: lifting it over 120 would ALSO put it over the afterlife
//  filter, the avogadro electrocution and both trap/burn overlays - so being set
//  on fire or electrocuted while holding Zombie Blood would stop showing the
//  damage feedback. That trades a cosmetic bug for a gameplay-feedback one. Only
//  the specific pair the mod invented is resolved here; every other overlay keeps
//  its stock relationship to both effects.
//
//  The ramp loops above and below call this every 0.25s for as long as the player
//  is in the stink (ramp-up) or the meter is above zero (ramp-down), so this
//  re-evaluates continuously: pick Zombie Blood up inside the cloud and the stink
//  overlay drops within a tick; let it expire while still standing in the cloud
//  and the stink overlay comes back on the next tick. Nothing else about the perk
//  changes - the disease meter, the stink value, the zombie aggro and the stink
//  audio all still update on their normal schedule, and no clientfield
//  registration is touched, so client symmetry and the bit budget are unaffected.
set_vulture_overlay( fraction )
{
    state = level.vsmgr["overlay"].info["vulture_stink_overlay"].state;

    if ( fraction > 0 && !( self zmqol_vulture_zombie_blood_active() ) )
        state maps\mp\_visionset_mgr::vsmgr_set_state_active( self, 1 - fraction );
    else
        state maps\mp\_visionset_mgr::vsmgr_set_state_inactive( self );
}

//  Is Zombie Blood currently running on this player?
//
//  zombie_vars["zombie_powerup_zombie_blood_on"] is the flag the powerup itself
//  owns - quality_of_life.gsc's zmqol_zb_powerup() sets it to 1 on pickup and back
//  to 0 when the timer expires, in the same function that activates and
//  deactivates the Zombie Blood visionset and overlay, so it cannot drift out of
//  step with what is on screen. quality_of_life.gsc:7338 already tests it exactly
//  this way.
//
//  🛑 isdefined-guarded on purpose. zmqol_zb_init_player_vars() is registered as an
//  onplayerconnect callback from INSIDE zmqol_enable_zombie_blood(), which returns
//  early on maps where Zombie Blood is not enabled - so on those maps the key is
//  never initialised and a bare read would be an undefined-variable error. Absent
//  means "no Zombie Blood here", which is the correct answer.
zmqol_vulture_zombie_blood_active()
{
    if ( !isdefined( self.zombie_vars ) )
        return 0;

    if ( !isdefined( self.zombie_vars[ "zombie_powerup_zombie_blood_on" ] ) )
        return 0;

    return self.zombie_vars[ "zombie_powerup_zombie_blood_on" ];
}

_get_disease_meter_fraction()
{
    return self.vulture_stink_value / ( pow( 2, 5 ) - 1 );
}

_ramp_down_stink_overlay( b_instant_change )
{
    if ( !isdefined( b_instant_change ) )
        b_instant_change = 0;

    self notify( "vulture_perk_stink_ramp_down_done" );
    self endon( "vulture_perk_stink_ramp_down_done" );
    self endon( "death_or_disconnect" );
    self endon( "vulture_perk_lost" );
    self setclientfieldtoplayer( "sndVultureStink", 0 );

    //  Leaving the stink - see the note at the ramp-up above.
    self notify( "zmqol_vulture_stink_off" );
    self playsound( "zmqol_vult_stink_stop" );

    if ( !isdefined( level.perk_vulture.stink_change_decrement ) )
        level.perk_vulture.stink_change_decrement = pow( 2, 5 ) * 0.25 / 4;

    while ( !self.perk_vulture.is_in_zombie_stink && self.vulture_stink_value > 0 )
    {
        self.vulture_stink_value = self.vulture_stink_value - level.perk_vulture.stink_change_decrement;

        if ( self.vulture_stink_value < 0 )
            self.vulture_stink_value = 0;

        fraction = self _get_disease_meter_fraction();
        self set_vulture_overlay( fraction );

        if ( zmqol_vulture_has_disease_meter() )   // zm_qol: not registered on Mob
            self setclientfieldtoplayer( "vulture_perk_disease_meter", fraction );

        vulture_debug_text( "disease counter = " + self.vulture_stink_value );
        wait 0.25;
    }
}

_zombies_reacquire_player_after_leaving_stink()
{
    self endon( "death_or_disconnect" );
    self notify( "vulture_perk_stop_zombie_reacquire_player" );
    self endon( "vulture_perk_stop_zombie_reacquire_player" );
    self toggle_stink_overlay( 0 );

    while ( self.vulture_stink_value > 0 )
    {
        vulture_debug_text( "zombies ignoring player..." );
        wait 0.25;
    }

    self.ignoreme = 0;
    level.perk_vulture.use_exit_behavior = 0;
}

vulture_perk_should_zombies_resume_find_flesh()
{
    b_should_find_flesh = !is_player_in_zombie_stink();
    return b_should_find_flesh;
}

is_player_in_zombie_stink()
{
    a_players = get_players();
    b_player_in_zombie_stink = 0;

    for ( i = 0; !b_player_in_zombie_stink && i < a_players.size; i++ )
    {
        if ( isdefined( a_players[i].is_in_zombie_stink ) && a_players[i].is_in_zombie_stink )
            b_player_in_zombie_stink = 1;
    }

    return b_player_in_zombie_stink;
}

give_vulture_bonus( str_bonus )
{
    switch ( str_bonus )
    {
        case "ammo":
            self give_bonus_ammo();
            break;
        case "points":
            self give_bonus_points();
            break;
        case "stink":
            self give_bonus_stink();
            break;
        default:
            assert( "invalid bonus string '" + str_bonus + "' used in give_vulture_bonus()!" );
            break;
    }
}

give_bonus_ammo()
{
    str_weapon_current = self getcurrentweapon();

    if ( str_weapon_current != "none" )
    {
        n_heat_value = self isweaponoverheating( 1, str_weapon_current );
        n_fuel_total = weaponfuellife( str_weapon_current );
        b_is_fuel_weapon = n_fuel_total > 0;
        b_is_overheating_weapon = n_heat_value > 0;

        if ( b_is_overheating_weapon )
        {
            n_ammo_refunded = randomintrange( 1, 3 );
            b_weapon_is_overheating = self isweaponoverheating();
            self setweaponoverheating( b_weapon_is_overheating, n_heat_value - n_ammo_refunded );
        }
        else if ( b_is_fuel_weapon )
        {
            n_fuel_used = self getweaponammofuel( str_weapon_current );
            n_fuel_refunded = randomintrange( int( n_fuel_total * 0.01 ), int( n_fuel_total * 0.03 ) );
            self setweaponammofuel( str_weapon_current, n_fuel_used - n_fuel_refunded );
            n_ammo_refunded = n_fuel_refunded / n_fuel_total * 100;
        }
        else if ( is_valid_ammo_bonus_weapon( str_weapon_current ) )
        {
            n_ammo_count_current = self getweaponammostock( str_weapon_current );
            n_ammo_count_max = weaponmaxammo( str_weapon_current );
            n_ammo_refunded = clamp( int( n_ammo_count_max * randomfloatrange( 0.0, 0.025 ) ), 1, n_ammo_count_max );
            b_is_custom_weapon = self handle_custom_weapon_refunds( str_weapon_current );

            if ( !b_is_custom_weapon )
                self setweaponammostock( str_weapon_current, n_ammo_count_current + n_ammo_refunded );
        }

        self playsoundtoplayer( "zmqol_vult_pickup_ammo", self );
        chance = get_response_chance( "vulture_ammo_drop" );

        if ( chance > randomintrange( 1, 100 ) )
            self thread maps\mp\zombies\_zm_audio::create_and_play_dialog( "general", "vulture_ammo_drop" );

/#
        if ( getdvarint( #"zombies_debug_vulture_perk" ) )
        {
            if ( !isdefined( n_ammo_refunded ) )
                n_ammo_refunded = 0;

            vulture_debug_text( str_weapon_current + " bullets given: " + n_ammo_refunded );
        }
#/
    }
}

is_valid_ammo_bonus_weapon( str_weapon )
{
    return !( is_placeable_mine( str_weapon ) || maps\mp\zombies\_zm_equipment::is_placeable_equipment( str_weapon ) || isinarray( level.perk_vulture.invalid_bonus_ammo_weapons, str_weapon ) );
}

_play_vulture_drop_pickup_fx()
{
    self vulture_clientfield_scriptmover_set( "vulture_drop_pickup" );

    //  🛑 v1.42.0 - THE playsound THAT USED TO BE HERE IS GONE, and the paragraph
    //  justifying it was wrong about where Buried's chime comes from.
    //
    //  v1.41.1 said the chime was "played CLIENT-side off this very clientfield".
    //  It is not. Stock's handler for this clientfield is
    //  _zm_perk_vulture.csc::vulture_drop_pickup() and its entire body is one
    //  playfx - no sound of any kind. So this line was inventing a third sound
    //  Buried never makes, fired from the DROP entity in 3D while Buried's real
    //  chime is a 2D layer on the player.
    //
    //  Where the chime actually comes from is the alias table, which nobody had
    //  read all the way across: zmb_vulture_drop_pickup_ammo carries
    //  zmb_vulture_drop_pickup in its SECONDARY column, so one playsoundtoplayer
    //  on the ammo alias fires both halves by itself. The mod's copy inherited
    //  that column verbatim - pointing at Buried's alias, which exists in
    //  zmb_buried.all and nowhere else - so on the five added maps the secondary
    //  resolved to nothing and only the rustle played. That is the "it has a
    //  sound effect rn but it's not the right one".
    //
    //  Fixed in soundbank\mod.all.aliases.additions.csv by repointing Secondary
    //  at zmqol_vult_pickup, the mod's own copy of the same payload, which ships
    //  in mod.all and therefore loads on every map. give_bonus_ammo() and
    //  give_bonus_points() need no change - they already play the alias that now
    //  carries the layer, exactly as Buried does.
    //
    //  🛑 The reusable part: an alias is ~60 columns and Secondary is one of them.
    //  Diff YOUR row against the stock row field by field before concluding the
    //  sound is missing - here the payloads, volumes and curves were already
    //  byte-identical and the whole bug was column 3.
}

give_bonus_points( v_fx_origin )
{
    n_multiplier = randomintrange( 1, 5 );
    self maps\mp\zombies\_zm_score::player_add_points( "vulture", 5 * n_multiplier );
    self playsoundtoplayer( "zmqol_vult_pickup_money", self );
    chance = get_response_chance( "vulture_money_drop" );

    if ( chance > randomintrange( 1, 100 ) )
        self thread maps\mp\zombies\_zm_audio::create_and_play_dialog( "general", "vulture_money_drop" );
}

give_bonus_stink( v_drop_origin )
{
    self _handle_zombie_stink( 0 );
}

_vulture_perk_think()
{
    self endon( "death" );
    self endon( "disconnect" );
    self endon( "vulture_perk_lost" );

    while ( true )
    {
        b_player_in_zombie_stink = 0;

        if ( !isdefined( level.perk_vulture.zombie_stink_array ) )
            level.perk_vulture.zombie_stink_array = [];

        if ( level.perk_vulture.zombie_stink_array.size > 0 )
        {
            a_close_points = arraysort( level.perk_vulture.zombie_stink_array, self.origin, 1, 300 );

            if ( a_close_points.size > 0 )
                b_player_in_zombie_stink = self _is_player_in_zombie_stink( a_close_points );
        }

        self _handle_zombie_stink( b_player_in_zombie_stink );
        wait( randomfloatrange( 0.25, 0.5 ) );
    }
}

_is_player_in_zombie_stink( a_points )
{
    b_is_in_stink = 0;

    for ( i = 0; i < a_points.size; i++ )
    {
        if ( distancesquared( a_points[i].origin, self.origin ) < 4900 )
            b_is_in_stink = 1;
    }

    return b_is_in_stink;
}

vulture_drop_count_increment()
{
    level.perk_vulture.drop_slots_for_network++;
    level thread _decrement_network_slots_after_time();
}

_decrement_network_slots_after_time()
{
    wait( getdvarint( #"zombies_perk_vulture_network_time_frame" ) * 0.001 );
    level.perk_vulture.drop_slots_for_network--;
}

vulture_zombie_spawn_func()
{
    self endon( "death" );
    //  v2.7.3 - VULTURE AID NO LONGER TOUCHES ZOMBIE EYE COLOUR. The
    //  `self thread add_zombie_eye_glow();` that stood here set actor
    //  clientfield bit 1 (vulture_eye_glow) on every zombie, which the client
    //  renders as misc/fx_zombie_eye_vulture - the blue eye. Cutting the WRITE
    //  is the root-cause fix: with the bit never set, the client's
    //  actors_eye_glow array stays empty, so vulture_vision_enable()'s
    //  "foreach zombie ... _zombie_eye_glow_enable()" pass on perk pickup has
    //  nothing to enable. The clientfield REGISTRATION is deliberately left
    //  alone on both sides - symmetry and the 2-bit actor budget are unchanged.
    self waittill( "completed_emerging_into_playable_area" );

    if ( self should_zombie_have_stink() )
    {
        self stink_zombie_array_add();
/#
        if ( isdefined( self.stink_ent ) )
        {
            while ( true )
            {
                if ( getdvarint( #"zombies_debug_vulture_perk" ) )
                    debugstar( self.origin, 2, ( 0, 1, 0 ) );

                wait 0.1;
            }
        }
#/
    }
}

zombies_drop_stink_on_death()
{
    if ( isdefined( self.attacker ) && isplayer( self.attacker ) && self.attacker hasperk( "specialty_nomotionsensor" ) )
        self thread do_vulture_death( self.attacker );
    else if ( isdefined( self.is_stink_zombie ) && self.is_stink_zombie && isdefined( self.stink_ent ) )
    {
        str_identifier = "_" + self getentitynumber() + "_" + gettime();
        self thread _drop_zombie_stink( level, str_identifier, "stink" );
    }
}

clear_zombie_stink_fx()
{
    self vulture_clientfield_actor_clear( "vulture_stink_trail_fx" );
}

stink_zombie_array_add()
{
    if ( get_unused_stink_ent_count() > 0 )
    {
        self.stink_ent = get_unused_stink_ent();

        if ( isdefined( self.stink_ent ) )
        {
            self.stink_ent.owner = self;
            wait_network_frame();
            wait_network_frame();
            self.stink_ent thread _show_debug_location();
            self vulture_clientfield_actor_set( "vulture_stink_trail_fx" );
            level.perk_vulture.last_stink_zombie_spawned = gettime();
            self.is_stink_zombie = 1;
        }
    }
    else
        self.is_stink_zombie = 0;
}

should_zombie_have_stink()
{
    b_is_zombie = isdefined( self.animname ) && self.animname == "zombie";
    b_cooldown_up = gettime() - level.perk_vulture.last_stink_zombie_spawned > getdvarint( #"zombies_perk_vulture_spawn_stink_zombie_cooldown" ) * 1000;
    b_roll_passed = 100 - randomint( 100 ) > 50;
    b_stink_ent_available = get_unused_stink_ent_count() > 0;
    b_should_have_stink = b_is_zombie && b_roll_passed && b_cooldown_up && b_stink_ent_available;
    return b_should_have_stink;
}

vulture_debug_text( str_text )
{
/#
    if ( getdvarint( #"zombies_debug_vulture_perk" ) )
        iprintln( str_text );
#/
}

vulture_clientfield_scriptmover_set( str_field_name )
{
    if ( !zmqol_vulture_has_scriptmover_field() )   // zm_qol: not registered on Origins
        return;

    assert( isdefined( level.perk_vulture.clientfields.scriptmovers[str_field_name] ), str_field_name + " is not a valid client field for vulture perk!" );
    n_value = self getclientfield( "vulture_perk_scriptmover" );
    n_value = n_value | 1 << level.perk_vulture.clientfields.scriptmovers[str_field_name];
    self setclientfield( "vulture_perk_scriptmover", n_value );
}

vulture_clientfield_scriptmover_clear( str_field_name )
{
    if ( !zmqol_vulture_has_scriptmover_field() )   // zm_qol: not registered on Origins
        return;

    assert( isdefined( level.perk_vulture.clientfields.scriptmovers[str_field_name] ), str_field_name + " is not a valid client field for vulture perk!" );
    n_value = self getclientfield( "vulture_perk_scriptmover" );
    n_value = n_value & ~( 1 << level.perk_vulture.clientfields.scriptmovers[str_field_name] );
    self setclientfield( "vulture_perk_scriptmover", n_value );
}

vulture_clientfield_actor_set( str_field_name )
{
    if ( !zmqol_vulture_has_actor_field() )   // zm_qol: not registered on Origins
        return;

    assert( isdefined( level.perk_vulture.clientfields.actors[str_field_name] ), str_field_name + " is not a valid field for vulture_clientfield_actor_set!" );
    n_value = getclientfield( "vulture_perk_actor" );
    n_value = n_value | 1 << level.perk_vulture.clientfields.actors[str_field_name];
    self setclientfield( "vulture_perk_actor", n_value );
}

vulture_clientfield_actor_clear( str_field_name )
{
    if ( !zmqol_vulture_has_actor_field() )   // zm_qol: not registered on Origins
        return;

    assert( isdefined( level.perk_vulture.clientfields.actors[str_field_name] ), str_field_name + " is not a valid field for vulture_clientfield_actor_clear!" );
    n_value = getclientfield( "vulture_perk_actor" );
    n_value = n_value & ~( 1 << level.perk_vulture.clientfields.actors[str_field_name] );
    self setclientfield( "vulture_perk_actor", n_value );
}

vulture_clientfield_toplayer_set( str_field_name )
{
    assert( isdefined( level.perk_vulture.clientfields.toplayer[str_field_name] ), str_field_name + " is not a valid client field for vulture perk!" );
    n_value = self getclientfieldtoplayer( "vulture_perk_toplayer" );
    n_value = n_value | 1 << level.perk_vulture.clientfields.toplayer[str_field_name];
    self setclientfieldtoplayer( "vulture_perk_toplayer", n_value );
}

vulture_clientfield_toplayer_clear( str_field_name )
{
    assert( isdefined( level.perk_vulture.clientfields.toplayer[str_field_name] ), str_field_name + " is not a valid client field for vulture perk!" );
    n_value = self getclientfieldtoplayer( "vulture_perk_toplayer" );
    n_value = n_value & ~( 1 << level.perk_vulture.clientfields.toplayer[str_field_name] );
    self setclientfieldtoplayer( "vulture_perk_toplayer", n_value );
}

vulture_perk_watch_mystery_box()
{
    //  ========================================================================
    //  🛑 v1.99.68 - WAIT FOR THE BOX. THIS LOOP USED TO EXIT INSTANTLY.
    //
    //  User, 2026-08-19: *"the mystery box itself doesn't"* have a Vulture Aid
    //  icon. Stock's body is one wait_network_frame() and then a `while` whose
    //  condition tests level.chests - and this function is threaded from
    //  init_vulture(), the perk's own init thread. On Buried the box happens to
    //  exist by then. On a map where _zm_magicbox has not built level.chests
    //  yet, the condition is false on its FIRST evaluation, the function returns,
    //  and the box is never marked for the rest of the match - silently, because
    //  nothing errors.
    //
    //  🌟 The fix waits for the thing the loop already depends on rather than
    //  changing what the loop does. Everything below this block is stock.
    //  ========================================================================
    n_tries = 0;

    while ( ( !isdefined( level.chests ) || level.chests.size == 0 || !isdefined( level.chest_index ) ) && n_tries < 1200 )
    {
        wait 0.05;
        n_tries++;
    }

    wait_network_frame();

    while ( isdefined( level.chests ) && level.chests.size > 0 && isdefined( level.chest_index ) )
    {
        level.chests[level.chest_index].zbarrier vulture_perk_shows_mystery_box( 1 );
        flag_wait( "moving_chest_now" );
        level.chests[level.chest_index].zbarrier vulture_perk_shows_mystery_box( 0 );
        flag_waitopen( "moving_chest_now" );
    }
}

vulture_perk_shows_mystery_box( b_show )
{
    self setclientfield( "vulture_perk_zbarrier", b_show );
}

vulture_perk_watch_fire_sale()
{
    //  v1.99.68 - same silent-exit as vulture_perk_watch_mystery_box() above:
    //  the `while` tests level.chests on its first evaluation and this is an
    //  init thread. Wait for the box before entering it.
    n_tries = 0;

    while ( ( !isdefined( level.chests ) || level.chests.size == 0 ) && n_tries < 1200 )
    {
        wait 0.05;
        n_tries++;
    }

    wait_network_frame();

    while ( isdefined( level.chests ) && level.chests.size > 0 )
    {
        level waittill( "powerup fire sale" );

        for ( i = 0; i < level.chests.size; i++ )
        {
            if ( i != level.chest_index )
                level.chests[i] thread vulture_fire_sale_box_fx_enable();
        }

        level waittill( "fire_sale_off" );

        for ( i = 0; i < level.chests.size; i++ )
        {
            if ( i != level.chest_index )
                level.chests[i] thread vulture_fire_sale_box_fx_disable();
        }
    }
}

vulture_fire_sale_box_fx_enable()
{
    if ( self.zbarrier.state == "arriving" )
        self.zbarrier waittill( "arrived" );

    self.zbarrier setclientfield( "vulture_perk_zbarrier", 1 );
}

vulture_fire_sale_box_fx_disable()
{
    self.zbarrier setclientfield( "vulture_perk_zbarrier", 0 );
}

vulture_perk_watch_powerup_drops()
{
    while ( true )
    {
        level waittill( "powerup_dropped", m_powerup );
        m_powerup thread _powerup_drop_think();
    }
}

_powerup_drop_think()
{
    e_temp = spawn( "script_model", self.origin );
    e_temp setmodel( "tag_origin" );
    e_temp vulture_clientfield_scriptmover_set( "vulture_powerup_drop" );
    self waittill_any( "powerup_timedout", "powerup_grabbed", "death" );
    e_temp vulture_clientfield_scriptmover_clear( "vulture_powerup_drop" );
    wait_network_frame();
    wait_network_frame();
    wait_network_frame();
    e_temp delete();
}

vulture_zombies_find_exit_point()
{
/#
    if ( getdvarint( #"zombies_debug_vulture_perk" ) > 0 )
    {
        foreach ( struct in level.enemy_dog_locations )
            debugstar( struct.origin, 200, ( 1, 1, 1 ) );
    }
#/
    a_zombies = get_round_enemy_array();

    for ( i = 0; i < a_zombies.size; i++ )
        a_zombies[i] thread zombie_goes_to_exit_location();
}

zombie_goes_to_exit_location()
{
    self endon( "death" );

    if ( !( isdefined( self.completed_emerging_into_playable_area ) && self.completed_emerging_into_playable_area ) )
    {
        self waittill( "completed_emerging_into_playable_area" );
        wait 1;
    }

    s_goal = _get_zombie_exit_point();
    self notify( "stop_find_flesh" );
    self notify( "zombie_acquire_enemy" );

    if ( isdefined( s_goal ) )
        self setgoalpos( s_goal.origin );

    while ( true )
    {
        b_passed_override = 1;

        if ( isdefined( level.default_find_exit_position_override ) )
            b_passed_override = [[ level.default_find_exit_position_override ]]();

        if ( !flag( "wait_and_revive" ) && b_passed_override )
            break;

        wait 0.1;
    }

    self thread maps\mp\zombies\_zm_ai_basic::find_flesh();
}

_get_zombie_exit_point()
{
    player = get_players()[0];
    n_dot_best = 9999999;
    a_exit_points = self [[ level.perk_vulture.func_zombies_find_valid_exit_locations ]]();
    assert( a_exit_points.size > 0, "_get_zombie_exit_point() couldn't find any zombie exit points for player at " + player.origin + "! Add more dog_locations!" );

    for ( i = 0; i < a_exit_points.size; i++ )
    {
        v_to_player = vectornormalize( player.origin - self.origin );
        v_to_goal = a_exit_points[i].origin - self.origin;
        n_dot = vectordot( v_to_player, v_to_goal );

        if ( n_dot < n_dot_best && distancesquared( player.origin, a_exit_points[i].origin ) > 360000 )
        {
            nd_best = a_exit_points[i];
            n_dot_best = n_dot;
        }

/#
        if ( getdvarint( #"zombies_debug_vulture_perk" ) )
            debugstar( a_exit_points[i].origin, 200, ( 1, 0, 0 ) );
#/
    }

    return nd_best;
}

get_valid_exit_points_for_zombie()
{
    a_exit_points = level.enemy_dog_locations;

    if ( isdefined( level.perk_vulture.zones_for_extra_stink_locations ) && level.perk_vulture.zones_for_extra_stink_locations.size > 0 )
    {
        a_zones_with_extra_stink_locations = getarraykeys( level.perk_vulture.zones_for_extra_stink_locations );

        foreach ( zone in level.active_zone_names )
        {
            if ( isinarray( a_zones_with_extra_stink_locations, zone ) )
            {
                a_zones_temp = level.perk_vulture.zones_for_extra_stink_locations[zone];

                for ( i = 0; i < a_zones_temp.size; i++ )
                    a_exit_points = arraycombine( a_exit_points, get_zone_dog_locations( a_zones_temp[i] ), 0, 0 );
            }
        }
    }

    return a_exit_points;
}

get_zone_dog_locations( str_zone )
{
    a_dog_locations = [];

    if ( isdefined( level.zones[str_zone] ) && isdefined( level.zones[str_zone].dog_locations ) )
        a_dog_locations = level.zones[str_zone].dog_locations;

    return a_dog_locations;
}

vulture_vision_toggle( b_enable )
{

}

vulture_handle_solo_quick_revive()
{
    flag_wait( "initial_blackscreen_passed" );

    if ( flag( "solo_game" ) )
    {
        flag_wait( "solo_revive" );
        setclientfield( "vulture_perk_disable_solo_quick_revive_glow", 1 );
    }
}

vulture_devgui_spawn_stink()
{
/#
    player = gethostplayer();
    forward_dir = vectornormalize( anglestoforward( player.angles ) );
    target_pos = player.origin + forward_dir * 100 + vectorscale( ( 0, 0, 1 ), 50.0 );
    target_pos_down = target_pos + vectorscale( ( 0, 0, -1 ), 150.0 );
    str_bonus = "stink";
    str_identifier = "_" + "test_" + gettime();
    drop_pos = groundtrace( target_pos, target_pos_down, 0, player )["position"];
    setdvarint( "zombies_debug_vulture_perk", 1 );
    player thread show_debug_info( drop_pos, str_identifier, str_bonus );
    e_temp = player maps\mp\zombies\_zm_perk_vulture::zombie_drops_stink( drop_pos, str_identifier );
    e_temp = player maps\mp\zombies\_zm_perk_vulture::_vulture_spawn_fx( str_identifier, drop_pos, str_bonus, e_temp );
    maps\mp\zombies\_zm_perk_vulture::clean_up_stink( e_temp );
#/
}

setup_splitscreen_optimizations()
{
    if ( level.splitscreen && getdvarint( #"splitscreen_playerCount" ) > 2 )
    {
        setdvarint( "zombies_perk_vulture_drops_max", int( getdvarint( #"zombies_perk_vulture_drops_max" ) * 0.5 ) );
        setdvarint( "zombies_perk_vulture_spawn_stink_zombie_cooldown", int( getdvarint( #"zombies_perk_vulture_spawn_stink_zombie_cooldown" ) * 2 ) );
        setdvarint( "zombies_perk_vulture_max_stink_zombies", int( getdvarint( #"zombies_perk_vulture_max_stink_zombies" ) * 0.5 ) );
    }
}

initialize_bonus_entity_pool()
{
    n_ent_pool_size = getdvarint( #"zombies_perk_vulture_drops_max" );
    level.perk_vulture.bonus_drop_ent_pool = [];

    for ( i = 0; i < n_ent_pool_size; i++ )
    {
        e_temp = spawn( "script_model", ( 0, 0, 0 ) );
        e_temp setmodel( "tag_origin" );
        e_temp.targetname = "vulture_perk_bonus_pool_ent";
        e_temp.in_use = 0;
        level.perk_vulture.bonus_drop_ent_pool[level.perk_vulture.bonus_drop_ent_pool.size] = e_temp;
    }
}

get_unused_bonus_ent()
{
    e_found = undefined;

    for ( i = 0; i < level.perk_vulture.bonus_drop_ent_pool.size && !isdefined( e_found ); i++ )
    {
        if ( !level.perk_vulture.bonus_drop_ent_pool[i].in_use )
        {
            e_found = level.perk_vulture.bonus_drop_ent_pool[i];
            e_found.in_use = 1;
        }
    }

    return e_found;
}

get_unused_bonus_ent_count()
{
    n_found = 0;

    for ( i = 0; i < level.perk_vulture.bonus_drop_ent_pool.size; i++ )
    {
        if ( !level.perk_vulture.bonus_drop_ent_pool[i].in_use )
            n_found++;
    }

    return n_found;
}

clear_bonus_ent()
{
    self notify( "stop_vulture_behavior" );
    self vulture_clientfield_scriptmover_clear( "vulture_drop_fx" );
    self.in_use = 0;
    self setmodel( "tag_origin" );
    self ghost();
}

initialize_stink_entity_pool()
{
    n_ent_pool_size = getdvarint( #"zombies_perk_vulture_max_stink_zombies" );
    level.perk_vulture.stink_ent_pool = [];

    for ( i = 0; i < n_ent_pool_size; i++ )
    {
        e_temp = spawn( "script_model", ( 0, 0, 0 ) );
        e_temp setmodel( "tag_origin" );
        e_temp.targetname = "vulture_perk_bonus_pool_ent";
        e_temp.in_use = 0;
        level.perk_vulture.stink_ent_pool[level.perk_vulture.stink_ent_pool.size] = e_temp;
    }
}

get_unused_stink_ent_count()
{
    n_found = 0;

    for ( i = 0; i < level.perk_vulture.stink_ent_pool.size; i++ )
    {
        if ( !level.perk_vulture.stink_ent_pool[i].in_use )
        {
            n_found++;
            continue;
        }

        if ( !isdefined( level.perk_vulture.stink_ent_pool[i].owner ) && !isdefined( level.perk_vulture.stink_ent_pool[i].drop_time ) )
        {
            level.perk_vulture.stink_ent_pool[i] clear_stink_ent();
            n_found++;
        }
    }

    return n_found;
}

get_unused_stink_ent()
{
    e_found = undefined;

    for ( i = 0; i < level.perk_vulture.stink_ent_pool.size && !isdefined( e_found ); i++ )
    {
        if ( !level.perk_vulture.stink_ent_pool[i].in_use )
        {
            e_found = level.perk_vulture.stink_ent_pool[i];
            e_found.in_use = 1;
            vulture_debug_text( "vulture stink >> ent " + e_found getentitynumber() + " in use" );
        }
    }

    return e_found;
}

clear_stink_ent()
{
    vulture_debug_text( "vulture stink >> ent " + self getentitynumber() + " CLEAR" );
    self vulture_clientfield_scriptmover_clear( "vulture_stink_fx" );
    self notify( "stop_vulture_behavior" );
    self.in_use = 0;
    self.drop_time = undefined;
    self.owner = undefined;
    self setmodel( "tag_origin" );
    self ghost();
}

_show_debug_location()
{
/#
    while ( self.in_use )
    {
        if ( getdvarint( #"zombies_debug_vulture_perk" ) > 0 )
        {
            debugstar( self.origin, 1, ( 0, 0, 1 ) );
            print3d( self.origin, self getentitynumber(), ( 0, 0, 1 ), 1, 1, 1 );
        }

        wait 0.05;
    }
#/
}

handle_custom_weapon_refunds( str_weapon )
{
    b_is_custom_weapon = 0;

    if ( issubstr( str_weapon, "knife_ballistic" ) )
    {
        self _refund_oldest_ballistic_knife( str_weapon );
        b_is_custom_weapon = 1;
    }

    return b_is_custom_weapon;
}

_refund_oldest_ballistic_knife( str_weapon )
{
    self endon( "death_or_disconnect" );
    self endon( "vulture_perk_lost" );

    if ( isdefined( self.weaponobjectwatcherarray ) && self.weaponobjectwatcherarray.size > 0 )
    {
        b_found_weapon_object = 0;

        for ( i = 0; i < self.weaponobjectwatcherarray.size; i++ )
        {
            if ( isdefined( self.weaponobjectwatcherarray[i].weapon ) && self.weaponobjectwatcherarray[i].weapon == str_weapon )
            {
                s_found = self.weaponobjectwatcherarray[i];
                break;
            }
        }

        if ( isdefined( s_found ) )
        {
            if ( isdefined( s_found.objectarray ) && s_found.objectarray.size > 0 )
            {
                e_oldest = undefined;

                for ( i = 0; i < s_found.objectarray.size; i++ )
                {
                    if ( isdefined( s_found.objectarray[i] ) )
                    {
                        if ( !isdefined( s_found.objectarray[i].retrievabletrigger ) || !isdefined( s_found.objectarray[i].retrievabletrigger.owner ) || s_found.objectarray[i].retrievabletrigger.owner != self || !isdefined( s_found.objectarray[i].birthtime ) )
                            continue;

                        if ( !isdefined( e_oldest ) )
                            e_oldest = s_found.objectarray[i];

                        if ( s_found.objectarray[i].birthtime < e_oldest.birthtime )
                            e_oldest = s_found.objectarray[i];
                    }
                }

                if ( isdefined( e_oldest ) )
                {
                    e_oldest.retrievabletrigger.force_pickup = 1;
                    e_oldest.retrievabletrigger notify( "trigger", self );
                }
            }
        }
    }
}

// ============================================================================
//  zmqol_vulture_stink_audio  -  zm_qol addition, not stock
//
//  The one-shot on entering the mist plus the loop for as long as you are in it,
//  using the mod's own copies of Buried's aliases (see the note at the
//  setclientfieldtoplayer( "sndVultureStink", 1 ) call for why the server does
//  this rather than the client).
//
//  The emitter is a spawned script_origin rather than the player, so
//  stoploopsound has something to stop that is not also carrying every other
//  sound the player makes. It is cleaned up on every way out of the stink,
//  including death and disconnect, or it leaks an entity per dose.
// ============================================================================
zmqol_vulture_stink_audio()
{
    self endon( "death_or_disconnect" );
    self endon( "vulture_perk_lost" );
    level endon( "end_game" );

    self playsound( "zmqol_vult_stink_start" );

    e_snd = spawn( "script_origin", self.origin );
    e_snd playloopsound( "zmqol_vult_stink_ploop", 0.5 );

    e_snd thread zmqol_vulture_stink_audio_follow( self );

    self waittill_any( "zmqol_vulture_stink_off", "death_or_disconnect", "vulture_perk_lost" );

    e_snd notify( "zmqol_stink_snd_done" );
    e_snd stoploopsound( 0.5 );
    wait 1;

    if ( isdefined( e_snd ) )
        e_snd delete();
}

//  Keep the emitter on the player so the loop pans with them.
zmqol_vulture_stink_audio_follow( player )
{
    self endon( "zmqol_stink_snd_done" );
    level endon( "end_game" );

    while ( isdefined( player ) )
    {
        self.origin = player.origin;
        wait 0.1;
    }
}

// ============================================================================
//  zmqol_vulture_marker_scan  -  the server tells the client where the machines
//                                really are                        (v1.99.68)
// ----------------------------------------------------------------------------
//  User, 2026-08-19, screenshot: Speed Cola and the other Nuketown machines had
//  NO Vulture Aid marker at all, while wall buys and the Wunderfizz did.
//
//  🛑 WHY THE OLD, CLIENT-ONLY ROUTE COULD NOT WORK HERE. zm_expanded.csc built
//  its marker list from getstructarray( "zm_perk_machine", "targetname" ) and
//  matched script_string against "<gametype>_perks_<location>". Nuketown does
//  not use those structs at all: zm_nuked_perks::init_nuked_perks() DELETES
//  every one of them and drops its machines onto randomly chosen
//  zm_random_machine pads at runtime. Nothing in the map file says where a
//  machine will end up, so no client-side derivation can ever find them - and
//  the same is true of Die Rise's moving elevator perks.
//
//  🌟 THE SERVER ALREADY HOLDS THE ANSWER, AND STOCK PUBLISHES IT. Every perk
//  machine on every map gets a use trigger with targetname "zombie_vending" and
//  a direct entity reference to its own model: use_trigger.machine = perk_machine
//  ( _zm_perks.gsc:2904 ), set inside perk_machine_spawn_init before the
//  per-perk switch. So this needs no map knowledge, no struct matching and no
//  per-map list - it asks the game which machines exist and marks each one.
//
//  📝 The client draws the marker at the entity's CURRENT origin whenever the
//  player enables Vulture vision, so a machine that moves after being marked is
//  still drawn in the right place next time the markers go up.
//
//  🛑 zmqol_not_ready IS NUKETOWN'S PARKED FLAG. perks_from_the_sky() lifts every
//  machine 8000 units into the sky at map start and drops them later; marking one
//  while it is up there would put a floating icon in the clouds. zm_nuked.gsc
//  sets that flag while parked and clears it on landing. No other map defines it.
//
//  ⚠️ Cost: one pass every 2 seconds over about a dozen triggers, writing a
//  clientfield only when the value actually changes.
// ============================================================================
zmqol_vulture_marker_scan()
{
    level endon( "end_game" );

    for ( ;; )
    {
        a_trigs = getentarray( "zombie_vending", "targetname" );
        n_marked = 0;

        for ( i = 0; i < a_trigs.size; i++ )
        {
            trig = a_trigs[i];

            if ( !isdefined( trig ) || !isdefined( trig.machine ) )
                continue;

            if ( isdefined( trig.machine.zmqol_not_ready ) && trig.machine.zmqol_not_ready )
                continue;

            n_code = zmqol_vulture_marker_code( trig.script_noteworthy );

            if ( isdefined( trig.machine.zmqol_marker_code ) && trig.machine.zmqol_marker_code == n_code )
                continue;

            trig.machine.zmqol_marker_code = n_code;
            trig.machine setclientfield( "zmqol_vulture_marker", n_code );
            n_marked++;

            //  🌟 DIAGNOSTIC ONLY (v1.99.70) - no behaviour change. It names the
            //  perk and the code for every machine the scan marks, so "wrong
            //  icon on that machine" can be read out of the user's own log
            //  instead of guessed at from a screenshot. Code 10 is the neutral
            //  fallback - any perk with no fx_zm_vulture_glow_* of its own.
            str_dbg = "(undefined)";

            if ( isdefined( trig.script_noteworthy ) )
                str_dbg = trig.script_noteworthy;

            println( "[zm_qol] vulture marker: " + str_dbg + " -> code " + n_code );
        }

        if ( !isdefined( level.zmqol_marker_said ) && n_marked > 0 )
        {
            //  One line, once - it names how many machines the server actually
            //  found and marked, which is the only way to tell "the scan missed
            //  them" from "the player already owns that perk, so stock hides the
            //  icon by design".
            level.zmqol_marker_said = 1;
            println( "[zm_qol] vulture markers: " + n_marked + " machine(s) marked" );
        }

        wait 2;
    }
}

//  🛑 THE CODES ARE A CONTRACT WITH zm_expanded.csc::zmqol_vulture_marker_fx().
//  Change one side and the wrong icon appears on the wrong machine. 1 is the
//  Wunderfizz, written by scripts/zm/wunderfizz.gsc rather than by the scan.
zmqol_vulture_marker_code( str_perk )
{
    if ( !isdefined( str_perk ) )
        return 10;

    switch ( str_perk )
    {
        case "specialty_armorvest":               return 2;
        case "specialty_rof":                     return 3;
        case "specialty_quickrevive":             return 4;
        case "specialty_fastreload":              return 5;
        case "specialty_weapupgrade":             return 6;
        case "specialty_longersprint":            return 7;
        case "specialty_additionalprimaryweapon": return 8;
        case "specialty_nomotionsensor":          return 9;

        //  v1.99.71 - the two Treyarch never drew. Both used to fall through to
        //  10, whose effect is fx_zm_vulture_glow_question = crossed rifles.
        //  zm_qol ships fx_zm_vulture_glow_deadshot / _flopper as raw .efx.
        case "specialty_deadshot":                return 11;
        case "specialty_flakjacket":              return 12;

        //  v1.99.72 - real machines on some maps, no icon anywhere in BO2. All
        //  three draw the skull; naming them separately is what lets the client
        //  hide each one when its own perk is bought, exactly like stock.
        //  🛑 15 IS THE CEILING - the clientfield is 4 bits.
        case "specialty_scavenger":               return 13;
        case "specialty_grenadepulldeath":        return 14;
        case "specialty_finalstand":              return 15;
    }

    return 10;
}
